USE cloud_signage_present;

START TRANSACTION;

SET @owner_admin_id := 1;
SET @countdown_seconds := 12;
SET @reveal_duration := 6;
SET @created_at := UTC_TIMESTAMP();

CREATE TEMPORARY TABLE tmp_popular_music_questions_200 (
    sort_order INT UNSIGNED NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option ENUM('A', 'B', 'C', 'D') NOT NULL
);

INSERT INTO tmp_popular_music_questions_200
    (sort_order, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
    (1, 'Which British band released Hey Jude in 1968?', 'The Rolling Stones', 'The Beatles', 'The Who', 'The Kinks', 'B'),
    (2, 'Who was known as the King of Pop?', 'Prince', 'Michael Jackson', 'Elvis Presley', 'David Bowie', 'B'),
    (3, 'Which singer released Like a Virgin in 1984?', 'Cyndi Lauper', 'Madonna', 'Whitney Houston', 'Cher', 'B'),
    (4, 'Which band recorded Bohemian Rhapsody?', 'Queen', 'ELO', 'The Eagles', 'Foreigner', 'A'),
    (5, 'Who sang Respect in its famous 1967 version?', 'Aretha Franklin', 'Diana Ross', 'Tina Turner', 'Gladys Knight', 'A'),
    (6, 'Which artist released Purple Rain?', 'Prince', 'Stevie Wonder', 'Lionel Richie', 'George Michael', 'A'),
    (7, 'Which group featured the members Agnetha, Bjorn, Benny and Anni-Frid?', 'Boney M.', 'ABBA', 'Bee Gees', 'Ace of Base', 'B'),
    (8, 'Who sang the 1992 hit I Will Always Love You?', 'Celine Dion', 'Whitney Houston', 'Mariah Carey', 'Toni Braxton', 'B'),
    (9, 'Which band released Hotel California?', 'Fleetwood Mac', 'Eagles', 'Chicago', 'Journey', 'B'),
    (10, 'Which singer was the lead vocalist of Nirvana?', 'Eddie Vedder', 'Kurt Cobain', 'Chris Cornell', 'Billy Corgan', 'B'),
    (11, 'Who recorded Dancing Queen?', 'ABBA', 'The Carpenters', 'Blondie', 'Bananarama', 'A'),
    (12, 'Which artist released Born in the U.S.A.?', 'Bruce Springsteen', 'Billy Joel', 'John Mellencamp', 'Tom Petty', 'A'),
    (13, 'Which duo released Wake Me Up Before You Go-Go?', 'Pet Shop Boys', 'Wham!', 'Erasure', 'Tears for Fears', 'B'),
    (14, 'Who sang Rolling in the Deep?', 'Adele', 'Duffy', 'Amy Winehouse', 'Leona Lewis', 'A'),
    (15, 'Which band released Smells Like Teen Spirit?', 'Pearl Jam', 'Nirvana', 'Soundgarden', 'Green Day', 'B'),
    (16, 'Which artist released the album Thriller?', 'Prince', 'Michael Jackson', 'Lionel Richie', 'Janet Jackson', 'B'),
    (17, 'Who sang Jolene?', 'Dolly Parton', 'Linda Ronstadt', 'Patsy Cline', 'Shania Twain', 'A'),
    (18, 'Which British singer released Shape of You?', 'Sam Smith', 'Ed Sheeran', 'Lewis Capaldi', 'George Ezra', 'B'),
    (19, 'Which band released Sweet Child o'' Mine?', 'Bon Jovi', 'Aerosmith', 'Guns N'' Roses', 'Def Leppard', 'C'),
    (20, 'Who recorded Tiny Dancer?', 'Billy Joel', 'Elton John', 'Rod Stewart', 'Phil Collins', 'B'),
    (21, 'Which singer released Toxic?', 'Britney Spears', 'Christina Aguilera', 'Pink', 'Kylie Minogue', 'A'),
    (22, 'Which band was fronted by Freddie Mercury?', 'Queen', 'The Police', 'Genesis', 'U2', 'A'),
    (23, 'Who sang Umbrella featuring Jay-Z?', 'Beyonce', 'Rihanna', 'Alicia Keys', 'Ciara', 'B'),
    (24, 'Which band released Wonderwall?', 'Blur', 'Oasis', 'Pulp', 'Suede', 'B'),
    (25, 'Who recorded Superstition?', 'Marvin Gaye', 'Stevie Wonder', 'Smokey Robinson', 'Otis Redding', 'B'),
    (26, 'Which artist released Firework?', 'Katy Perry', 'Lady Gaga', 'Kesha', 'Kelly Clarkson', 'A'),
    (27, 'Which group released Stayin'' Alive?', 'Bee Gees', 'Earth, Wind & Fire', 'Chicago', 'KC and the Sunshine Band', 'A'),
    (28, 'Who sang Someone Like You?', 'Adele', 'Leona Lewis', 'Jessie J', 'Emeli Sande', 'A'),
    (29, 'Which artist recorded Hound Dog in a famous 1950s version that remained hugely influential into the 1960s?', 'Jerry Lee Lewis', 'Elvis Presley', 'Buddy Holly', 'Roy Orbison', 'B'),
    (30, 'Which band released With or Without You?', 'U2', 'Simple Minds', 'INXS', 'R.E.M.', 'A'),
    (31, 'Who released the album Rumours with Fleetwood Mac?', 'Stevie Nicks', 'Fleetwood Mac', 'Heart', 'America', 'B'),
    (32, 'Which singer recorded Material Girl?', 'Madonna', 'Debbie Gibson', 'Cyndi Lauper', 'Belinda Carlisle', 'A'),
    (33, 'Which artist released Blinding Lights?', 'Drake', 'The Weeknd', 'Post Malone', 'Bruno Mars', 'B'),
    (34, 'Who sang Piano Man?', 'Billy Joel', 'Elton John', 'Paul Simon', 'James Taylor', 'A'),
    (35, 'Which band released Every Breath You Take?', 'The Police', 'Dire Straits', 'The Cars', 'Genesis', 'A'),
    (36, 'Who recorded Respect Yourself?', 'The Staple Singers', 'The Supremes', 'Martha and the Vandellas', 'The Ronettes', 'A'),
    (37, 'Which singer released Since U Been Gone?', 'Kelly Clarkson', 'Pink', 'Avril Lavigne', 'Hilary Duff', 'A'),
    (38, 'Which band released Livin'' on a Prayer?', 'Bon Jovi', 'Journey', 'Europe', 'Poison', 'A'),
    (39, 'Who sang Rehab?', 'Amy Winehouse', 'Adele', 'Duffy', 'Lily Allen', 'A'),
    (40, 'Which artist released Rocket Man?', 'David Bowie', 'Elton John', 'Rod Stewart', 'George Michael', 'B'),
    (41, 'Which duo released The Sound of Silence?', 'Simon & Garfunkel', 'Hall & Oates', 'The Righteous Brothers', 'Air Supply', 'A'),
    (42, 'Who recorded No Scrubs?', 'TLC', 'Destiny''s Child', 'SWV', 'En Vogue', 'A'),
    (43, 'Which band released Don''t Stop Believin''?', 'Journey', 'Foreigner', 'Boston', 'REO Speedwagon', 'A'),
    (44, 'Who sang Shake It Off?', 'Katy Perry', 'Taylor Swift', 'Selena Gomez', 'Ariana Grande', 'B'),
    (45, 'Which singer released the album 21?', 'Adele', 'Amy Winehouse', 'Dido', 'Sia', 'A'),
    (46, 'Which band recorded September?', 'Earth, Wind & Fire', 'KC and the Sunshine Band', 'Heatwave', 'Commodores', 'A'),
    (47, 'Who sang I Wanna Dance with Somebody?', 'Whitney Houston', 'Janet Jackson', 'Paula Abdul', 'Gloria Estefan', 'A'),
    (48, 'Which artist released Happy?', 'Bruno Mars', 'Pharrell Williams', 'Justin Timberlake', 'Usher', 'B'),
    (49, 'Which band released Karma Chameleon?', 'Culture Club', 'Duran Duran', 'ABC', 'A Flock of Seagulls', 'A'),
    (50, 'Who recorded California Love with Dr. Dre?', 'Snoop Dogg', 'Tupac Shakur', 'Ice Cube', 'Nas', 'B'),
    (51, 'Which singer released the song Halo?', 'Rihanna', 'Beyonce', 'Alicia Keys', 'Mariah Carey', 'B'),
    (52, 'Which band released Waterloo?', 'ABBA', 'Bucks Fizz', 'Steps', 'Bananarama', 'A'),
    (53, 'Who sang My Heart Will Go On?', 'Celine Dion', 'Whitney Houston', 'Mariah Carey', 'Shania Twain', 'A'),
    (54, 'Which artist recorded Let''s Dance?', 'David Bowie', 'Prince', 'George Michael', 'Bryan Ferry', 'A'),
    (55, 'Which group released Waterfalls?', 'TLC', 'En Vogue', 'Salt-N-Pepa', 'Destiny''s Child', 'A'),
    (56, 'Who sang Billie Jean?', 'Prince', 'Michael Jackson', 'Stevie Wonder', 'Rick James', 'B'),
    (57, 'Which band released Clocks?', 'Keane', 'Travis', 'Coldplay', 'Snow Patrol', 'C'),
    (58, 'Who recorded Like a Prayer?', 'Madonna', 'Cher', 'Annie Lennox', 'Pat Benatar', 'A'),
    (59, 'Which artist released Uptown Funk with Mark Ronson?', 'Bruno Mars', 'The Weeknd', 'Usher', 'Justin Timberlake', 'A'),
    (60, 'Which singer was known as the Queen of Soul?', 'Aretha Franklin', 'Diana Ross', 'Tina Turner', 'Gladys Knight', 'A'),
    (61, 'Which band released Losing My Religion?', 'R.E.M.', 'U2', 'INXS', 'The Cure', 'A'),
    (62, 'Who sang Poker Face?', 'Lady Gaga', 'Kesha', 'Katy Perry', 'P!nk', 'A'),
    (63, 'Which artist recorded 9 to 5?', 'Dolly Parton', 'Loretta Lynn', 'Tammy Wynette', 'Patsy Cline', 'A'),
    (64, 'Which band released One?', 'U2', 'Metallica', 'Radiohead', 'Coldplay', 'A'),
    (65, 'Who recorded Crazy in Love featuring Jay-Z?', 'Beyonce', 'Rihanna', 'Ashanti', 'Mary J. Blige', 'A'),
    (66, 'Which singer released Roar?', 'Katy Perry', 'Kesha', 'Pink', 'Kelly Clarkson', 'A'),
    (67, 'Which band recorded Another Brick in the Wall?', 'Pink Floyd', 'Led Zeppelin', 'The Who', 'Genesis', 'A'),
    (68, 'Who sang Fast Car?', 'Alanis Morissette', 'Tracy Chapman', 'Sheryl Crow', 'Joan Armatrading', 'B'),
    (69, 'Which artist released As It Was?', 'Harry Styles', 'Shawn Mendes', 'Niall Horan', 'Justin Bieber', 'A'),
    (70, 'Which group released I Want It That Way?', 'Backstreet Boys', 'NSYNC', 'Westlife', 'Boyzone', 'A'),
    (71, 'Who recorded Girls Just Want to Have Fun?', 'Cyndi Lauper', 'Madonna', 'Debbie Gibson', 'Belinda Carlisle', 'A'),
    (72, 'Which singer released Thank U, Next?', 'Ariana Grande', 'Selena Gomez', 'Demi Lovato', 'Camila Cabello', 'A'),
    (73, 'Which band released The Final Countdown?', 'Europe', 'Scorpions', 'Bon Jovi', 'Def Leppard', 'A'),
    (74, 'Who sang Don''t Stop Me Now?', 'Freddie Mercury with Queen', 'David Bowie', 'Elton John', 'Mick Jagger', 'A'),
    (75, 'Which artist recorded Just the Way You Are in 2010?', 'Bruno Mars', 'Jason Mraz', 'John Legend', 'Ed Sheeran', 'A'),
    (76, 'Which singer released Nothing Compares 2 U in a famous 1990 version?', 'Sinead O''Connor', 'Annie Lennox', 'Dolores O''Riordan', 'Sheryl Crow', 'A'),
    (77, 'Which band released Good Vibrations in 1966?', 'The Beach Boys', 'The Byrds', 'The Hollies', 'The Monkees', 'A'),
    (78, 'Who recorded Crazy?', 'Seal', 'Gnarls Barkley', 'Alicia Keys', 'John Legend', 'B'),
    (79, 'Which artist released Flowers in 2023?', 'Taylor Swift', 'Dua Lipa', 'Miley Cyrus', 'Ariana Grande', 'C'),
    (80, 'Which band recorded Mr. Brightside?', 'The Killers', 'Kings of Leon', 'Franz Ferdinand', 'The Strokes', 'A'),
    (81, 'Who sang Smooth featuring Santana?', 'Rob Thomas', 'Ricky Martin', 'Enrique Iglesias', 'Marc Anthony', 'A'),
    (82, 'Which singer released Chandelier?', 'Sia', 'Lorde', 'P!nk', 'Ellie Goulding', 'A'),
    (83, 'Which artist recorded Space Oddity?', 'David Bowie', 'Elton John', 'Marc Bolan', 'Bryan Ferry', 'A'),
    (84, 'Which group released End of the Road?', 'Boyz II Men', 'Jodeci', 'New Edition', 'Color Me Badd', 'A'),
    (85, 'Who sang Levitating?', 'Dua Lipa', 'Ava Max', 'Doja Cat', 'Rita Ora', 'A'),
    (86, 'Which band released Go Your Own Way?', 'Fleetwood Mac', 'Eagles', 'Heart', 'The Doobie Brothers', 'A'),
    (87, 'Who recorded You Oughta Know?', 'Alanis Morissette', 'Sheryl Crow', 'Melissa Etheridge', 'Fiona Apple', 'A'),
    (88, 'Which singer released All About That Bass?', 'Meghan Trainor', 'Ariana Grande', 'Katy Perry', 'Lizzo', 'A'),
    (89, 'Which band recorded Message in a Bottle?', 'The Police', 'U2', 'Dire Straits', 'The Pretenders', 'A'),
    (90, 'Who sang Believe in a 1998 dance-pop hit?', 'Cher', 'Madonna', 'Kylie Minogue', 'Anastacia', 'A'),
    (91, 'Which artist released 24K Magic?', 'Bruno Mars', 'The Weeknd', 'Justin Timberlake', 'Drake', 'A'),
    (92, 'Which singer recorded Son of a Preacher Man?', 'Dusty Springfield', 'Petula Clark', 'Dionne Warwick', 'Cilla Black', 'A'),
    (93, 'Which band released Enter Sandman?', 'Metallica', 'Megadeth', 'Anthrax', 'Slayer', 'A'),
    (94, 'Who sang Irreplaceable?', 'Beyonce', 'Rihanna', 'Alicia Keys', 'Kelly Rowland', 'A'),
    (95, 'Which artist released Take on Me?', 'a-ha', 'Duran Duran', 'Simple Minds', 'Tears for Fears', 'A'),
    (96, 'Which singer recorded Vision of Love?', 'Mariah Carey', 'Whitney Houston', 'Celine Dion', 'Toni Braxton', 'A'),
    (97, 'Which band released Basket Case?', 'Green Day', 'Blink-182', 'The Offspring', 'Sum 41', 'A'),
    (98, 'Who sang Royals?', 'Lorde', 'Sia', 'Halsey', 'Lana Del Rey', 'A'),
    (99, 'Which artist released When Doves Cry?', 'Prince', 'Michael Jackson', 'David Bowie', 'George Michael', 'A'),
    (100, 'Which group recorded No Diggity?', 'Blackstreet', 'Boyz II Men', 'Bell Biv DeVoe', 'TLC', 'A'),
    (101, 'Who sang Valerie with Mark Ronson?', 'Duffy', 'Adele', 'Amy Winehouse', 'Joss Stone', 'C'),
    (102, 'Which singer released Drivers License?', 'Olivia Rodrigo', 'Billie Eilish', 'Tate McRae', 'Conan Gray', 'A'),
    (103, 'Which band recorded Under Pressure with David Bowie?', 'Queen', 'Genesis', 'U2', 'Foreigner', 'A'),
    (104, 'Who sang Man! I Feel Like a Woman!?', 'Shania Twain', 'Faith Hill', 'LeAnn Rimes', 'Carrie Underwood', 'A'),
    (105, 'Which artist released Everybody Wants to Rule the World?', 'Tears for Fears', 'Simple Minds', 'Pet Shop Boys', 'Talk Talk', 'A'),
    (106, 'Which singer recorded Complicated?', 'Avril Lavigne', 'Michelle Branch', 'Kelly Clarkson', 'Pink', 'A'),
    (107, 'Which band released You Really Got Me?', 'The Kinks', 'The Who', 'The Animals', 'The Yardbirds', 'A'),
    (108, 'Who sang No One?', 'Alicia Keys', 'Beyonce', 'Rihanna', 'Ashanti', 'A'),
    (109, 'Which artist released Don''t Start Now?', 'Dua Lipa', 'Ava Max', 'Miley Cyrus', 'Lizzo', 'A'),
    (110, 'Which singer recorded Summer of ''69?', 'Bryan Adams', 'Bruce Springsteen', 'John Mellencamp', 'Bon Jovi', 'A'),
    (111, 'Which band released Zombie?', 'The Cranberries', 'Garbage', 'No Doubt', 'Republica', 'A'),
    (112, 'Who sang Wannabe?', 'Spice Girls', 'All Saints', 'TLC', 'Destiny''s Child', 'A'),
    (113, 'Which artist released The Gambler?', 'Kenny Rogers', 'Willie Nelson', 'Johnny Cash', 'Glen Campbell', 'A'),
    (114, 'Which singer recorded Hello in 2015?', 'Adele', 'Sam Smith', 'Sia', 'Ellie Goulding', 'A'),
    (115, 'Which band released Radioactive?', 'Imagine Dragons', 'OneRepublic', 'Coldplay', 'Fall Out Boy', 'A'),
    (116, 'Who sang Total Eclipse of the Heart?', 'Bonnie Tyler', 'Kim Wilde', 'Belinda Carlisle', 'Pat Benatar', 'A'),
    (117, 'Which artist released Kiss?', 'Prince', 'George Michael', 'Michael Jackson', 'David Bowie', 'A'),
    (118, 'Which singer recorded Unwritten?', 'Natasha Bedingfield', 'Dido', 'Jamelia', 'Corinne Bailey Rae', 'A'),
    (119, 'Which band released The Scientist?', 'Coldplay', 'Travis', 'Keane', 'Snow Patrol', 'A'),
    (120, 'Who sang Before He Cheats?', 'Carrie Underwood', 'Miranda Lambert', 'Taylor Swift', 'Kelly Clarkson', 'A'),
    (121, 'Which artist released Rebel Rebel?', 'David Bowie', 'T. Rex', 'Iggy Pop', 'Roxy Music', 'A'),
    (122, 'Which singer recorded Back to Black?', 'Amy Winehouse', 'Duffy', 'Adele', 'Paloma Faith', 'A'),
    (123, 'Which band released Sweet Dreams (Are Made of This)?', 'Eurythmics', 'Pet Shop Boys', 'Human League', 'Soft Cell', 'A'),
    (124, 'Who sang Just Dance?', 'Lady Gaga', 'Kesha', 'Katy Perry', 'Rihanna', 'A'),
    (125, 'Which artist released Lose Yourself?', 'Eminem', 'Dr. Dre', '50 Cent', 'Jay-Z', 'A'),
    (126, 'Which singer recorded Torn?', 'Natalie Imbruglia', 'Alanis Morissette', 'Meredith Brooks', 'Shania Twain', 'A'),
    (127, 'Which band released Brown Eyed Girl?', 'Van Morrison', 'Them', 'The Doors', 'The Byrds', 'A'),
    (128, 'Who sang Grenade?', 'Bruno Mars', 'Jason Derulo', 'Ne-Yo', 'Taio Cruz', 'A'),
    (129, 'Which artist released Bad Romance?', 'Lady Gaga', 'Katy Perry', 'Rihanna', 'Pink', 'A'),
    (130, 'Which singer recorded If I Ain''t Got You?', 'Alicia Keys', 'Beyonce', 'Ashanti', 'Mariah Carey', 'A'),
    (131, 'Which band released Owner of a Lonely Heart?', 'Yes', 'Asia', 'Genesis', 'Rush', 'A'),
    (132, 'Who sang Chasing Cars?', 'Snow Patrol', 'Coldplay', 'Keane', 'The Fray', 'A'),
    (133, 'Which artist released Take Me Home, Country Roads?', 'John Denver', 'James Taylor', 'Don McLean', 'Glen Campbell', 'A'),
    (134, 'Which singer recorded Tik Tok?', 'Kesha', 'Katy Perry', 'Lady Gaga', 'Avril Lavigne', 'A'),
    (135, 'Which band released The Chain?', 'Fleetwood Mac', 'Eagles', 'Heart', 'Boston', 'A'),
    (136, 'Who sang Heart of Glass?', 'Blondie', 'The Pretenders', 'Pat Benatar', 'Bananarama', 'A'),
    (137, 'Which artist released Sorry?', 'Justin Bieber', 'Ed Sheeran', 'Shawn Mendes', 'Harry Styles', 'A'),
    (138, 'Which singer recorded Hero in 2001?', 'Mariah Carey', 'Enrique Iglesias', 'Whitney Houston', 'Celine Dion', 'A'),
    (139, 'Which band released Everybody (Backstreet''s Back)?', 'Backstreet Boys', 'NSYNC', 'Take That', 'Boyzone', 'A'),
    (140, 'Who sang Price Tag featuring B.o.B?', 'Jessie J', 'Kesha', 'Rita Ora', 'Lily Allen', 'A'),
    (141, 'Which artist released Achy Breaky Heart?', 'Billy Ray Cyrus', 'Alan Jackson', 'Tim McGraw', 'Garth Brooks', 'A'),
    (142, 'Which singer recorded Watermelon Sugar?', 'Shawn Mendes', 'Harry Styles', 'Niall Horan', 'Charlie Puth', 'B'),
    (143, 'Which band released Baba O''Riley?', 'The Who', 'Led Zeppelin', 'The Kinks', 'Deep Purple', 'A'),
    (144, 'Who sang Don''t Know Why?', 'Norah Jones', 'Diana Krall', 'Katie Melua', 'Alicia Keys', 'A'),
    (145, 'Which artist released Freedom! ''90?', 'George Michael', 'Prince', 'Michael Jackson', 'Phil Collins', 'A'),
    (146, 'Which singer recorded Poker Face?', 'Lady Gaga', 'Rihanna', 'Katy Perry', 'Pink', 'A'),
    (147, 'Which band released Eye of the Tiger?', 'Survivor', 'Journey', 'Foreigner', 'Boston', 'A'),
    (148, 'Who sang Havana featuring Young Thug?', 'Camila Cabello', 'Selena Gomez', 'Ariana Grande', 'Dua Lipa', 'A'),
    (149, 'Which artist released Ring of Fire?', 'Johnny Cash', 'Willie Nelson', 'Merle Haggard', 'Waylon Jennings', 'A'),
    (150, 'Which singer recorded Black Velvet?', 'Alannah Myles', 'Bonnie Tyler', 'Pat Benatar', 'Kim Carnes', 'A'),
    (151, 'Which band released Friday I''m in Love?', 'The Cure', 'New Order', 'The Smiths', 'Depeche Mode', 'A'),
    (152, 'Who sang Work featuring Drake?', 'Rihanna', 'Beyonce', 'SZA', 'Ciara', 'A'),
    (153, 'Which artist released Piano in the Dark?', 'Brenda Russell', 'Anita Baker', 'Sade', 'Toni Braxton', 'A'),
    (154, 'Which singer recorded Jar of Hearts?', 'Christina Perri', 'Sara Bareilles', 'Colbie Caillat', 'Pink', 'A'),
    (155, 'Which band released Dreams in 1977?', 'Fleetwood Mac', 'Heart', 'Boston', 'Journey', 'A'),
    (156, 'Who sang Un-break My Heart?', 'Toni Braxton', 'Mariah Carey', 'Celine Dion', 'Whitney Houston', 'A'),
    (157, 'Which artist released Old Town Road?', 'Lil Nas X', 'Post Malone', 'Drake', 'Kane Brown', 'A'),
    (158, 'Which singer recorded Stay With Me?', 'Sam Smith', 'Lewis Capaldi', 'James Arthur', 'John Legend', 'A'),
    (159, 'Which band released Every Rose Has Its Thorn?', 'Poison', 'Bon Jovi', 'Def Leppard', 'Motley Crue', 'A'),
    (160, 'Who sang If I Could Turn Back Time?', 'Cher', 'Tina Turner', 'Madonna', 'Pat Benatar', 'A'),
    (161, 'Which artist released Wrecking Ball?', 'Miley Cyrus', 'Kesha', 'Pink', 'Kelly Clarkson', 'A'),
    (162, 'Which singer recorded Fastlove?', 'George Michael', 'Seal', 'Michael Bolton', 'Robbie Williams', 'A'),
    (163, 'Which band released Iris?', 'Goo Goo Dolls', 'Third Eye Blind', 'Matchbox Twenty', 'Train', 'A'),
    (164, 'Who sang Kiss Me?', 'Sixpence None the Richer', 'The Corrs', 'Natalie Imbruglia', 'Texas', 'A'),
    (165, 'Which artist released Easy on Me?', 'Adele', 'Sia', 'Sam Smith', 'Lana Del Rey', 'A'),
    (166, 'Which singer recorded Wake Me Up?', 'Avicii', 'Calvin Harris', 'David Guetta', 'Kygo', 'A'),
    (167, 'Which band released Another One Bites the Dust?', 'Queen', 'The Rolling Stones', 'Aerosmith', 'Kiss', 'A'),
    (168, 'Who sang Complicated?', 'Avril Lavigne', 'Michelle Branch', 'Kelly Clarkson', 'P!nk', 'A'),
    (169, 'Which artist released Islands in the Stream with Dolly Parton?', 'Kenny Rogers', 'Willie Nelson', 'George Jones', 'Charlie Rich', 'A'),
    (170, 'Which singer recorded Bleeding Love?', 'Leona Lewis', 'Adele', 'Jordin Sparks', 'Jessie J', 'A'),
    (171, 'Which band released Africa?', 'Toto', 'Journey', 'Foreigner', 'Chicago', 'A'),
    (172, 'Who sang Stronger (What Doesn''t Kill You)?', 'Kelly Clarkson', 'Pink', 'Katy Perry', 'Demi Lovato', 'A'),
    (173, 'Which artist released We Belong Together?', 'Mariah Carey', 'Beyonce', 'Alicia Keys', 'Whitney Houston', 'A'),
    (174, 'Which singer recorded Time After Time?', 'Cyndi Lauper', 'Madonna', 'Belinda Carlisle', 'Kim Wilde', 'A'),
    (175, 'Which band released Song 2?', 'Blur', 'Oasis', 'Pulp', 'Suede', 'A'),
    (176, 'Who sang Need You Now?', 'Lady A', 'The Chicks', 'Little Big Town', 'Sugarland', 'A'),
    (177, 'Which artist released The Way You Make Me Feel?', 'Michael Jackson', 'Prince', 'Bobby Brown', 'George Michael', 'A'),
    (178, 'Which singer recorded Say My Name?', 'Destiny''s Child', 'TLC', 'En Vogue', 'SWV', 'A'),
    (179, 'Which band released Mr. Blue Sky?', 'Electric Light Orchestra', 'Supertramp', '10cc', 'The Alan Parsons Project', 'A'),
    (180, 'Who sang Rolling in the Deep?', 'Adele', 'Amy Winehouse', 'Duffy', 'Sia', 'A'),
    (181, 'Which artist released Cry Me a River?', 'Justin Timberlake', 'Robin Thicke', 'Usher', 'Bruno Mars', 'A'),
    (182, 'Which singer recorded Sk8er Boi?', 'Avril Lavigne', 'Pink', 'Kelly Clarkson', 'Ashlee Simpson', 'A'),
    (183, 'Which band released New York, New York in a famous version by Frank Sinatra?', 'The Rat Pack', 'It was Frank Sinatra solo', 'Chicago', 'Barry Manilow', 'B'),
    (184, 'Who sang Call Me Maybe?', 'Carly Rae Jepsen', 'Katy Perry', 'Demi Lovato', 'Selena Gomez', 'A'),
    (185, 'Which artist released Dancing on My Own?', 'Robyn', 'Dua Lipa', 'Ellie Goulding', 'Kylie Minogue', 'A'),
    (186, 'Which singer recorded Because the Night?', 'Patti Smith', 'Debbie Harry', 'Chrissie Hynde', 'Pat Benatar', 'A'),
    (187, 'Which band released Run to You?', 'Bryan Adams', 'Bon Jovi', 'Foreigner', 'Journey', 'A'),
    (188, 'Who sang Set Fire to the Rain?', 'Adele', 'Leona Lewis', 'Sia', 'Emeli Sande', 'A'),
    (189, 'Which artist released Don''t Stop ''Til You Get Enough?', 'Michael Jackson', 'Prince', 'Rick James', 'Stevie Wonder', 'A'),
    (190, 'Which singer recorded Love Story?', 'Taylor Swift', 'Carrie Underwood', 'Miley Cyrus', 'Kesha', 'A'),
    (191, 'Which band released Everybody Wants to Rule the World?', 'Tears for Fears', 'Simple Minds', 'Duran Duran', 'Spandau Ballet', 'A'),
    (192, 'Who sang Rehab?', 'Amy Winehouse', 'Adele', 'Duffy', 'Joss Stone', 'A'),
    (193, 'Which artist released Adore You?', 'Harry Styles', 'Shawn Mendes', 'Justin Bieber', 'Troye Sivan', 'A'),
    (194, 'Which singer recorded Smooth Operator?', 'Sade', 'Anita Baker', 'Basia', 'Whitney Houston', 'A'),
    (195, 'Which band released Beat It?', 'Michael Jackson''s backing band is not credited; the artist is Michael Jackson', 'Queen', 'Journey', 'Hall & Oates', 'A'),
    (196, 'Who sang Since U Been Gone?', 'Kelly Clarkson', 'Pink', 'Avril Lavigne', 'Hilary Duff', 'A'),
    (197, 'Which artist released Die With a Smile as a 2020s-era collaboration single?', 'Lady Gaga and Bruno Mars', 'Dua Lipa and Elton John', 'Beyonce and Ed Sheeran', 'Taylor Swift and The Weeknd', 'A'),
    (198, 'Which singer recorded Put Your Records On?', 'Corinne Bailey Rae', 'Alicia Keys', 'Joss Stone', 'Norah Jones', 'A'),
    (199, 'Which band released Jump in 1984?', 'Van Halen', 'Bon Jovi', 'Foreigner', 'Europe', 'A'),
    (200, 'Who sang Flowers in 2023?', 'Miley Cyrus', 'Dua Lipa', 'Taylor Swift', 'Ariana Grande', 'A');

INSERT INTO quiz_questions
    (owner_admin_id, question_text, option_a, option_b, option_c, option_d, correct_option, countdown_seconds, reveal_duration, active, created_at, updated_at)
SELECT
    @owner_admin_id,
    t.question_text,
    t.option_a,
    t.option_b,
    t.option_c,
    t.option_d,
    t.correct_option,
    @countdown_seconds,
    @reveal_duration,
    1,
    @created_at,
    @created_at
FROM tmp_popular_music_questions_200 t
WHERE NOT EXISTS (
    SELECT 1
    FROM quiz_questions q
    WHERE q.owner_admin_id = @owner_admin_id
      AND q.question_text = t.question_text
);

DROP TEMPORARY TABLE tmp_popular_music_questions_200;

COMMIT;
