USE cloud_signage_present;

START TRANSACTION;

SET @owner_admin_id := 1;
SET @countdown_seconds := 12;
SET @reveal_duration := 6;
SET @created_at := UTC_TIMESTAMP();

CREATE TEMPORARY TABLE tmp_lateral_reasoning_questions_500 (
    sort_order INT UNSIGNED NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option ENUM('A', 'B', 'C', 'D') NOT NULL
);

INSERT INTO tmp_lateral_reasoning_questions_500
    (sort_order, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
    (1, 'What comes next in this geometric sequence: 2, 4, 8, 16, 32?', '84', '64', '58', '60', 'B'),
    (2, 'What comes next in this geometric sequence: 3, 9, 27, 81, 243?', '777', '789', '729', '759', 'C'),
    (3, 'What comes next in this geometric sequence: 4, 16, 64, 256, 1024?', '4066', '4114', '4096', '4132', 'C'),
    (4, 'What comes next in this geometric sequence: 5, 10, 20, 40, 80?', '160', '158', '208', '135', 'A'),
    (5, 'What comes next in this geometric sequence: 6, 18, 54, 162, 486?', '1506', '1456', '1458', '1408', 'C'),
    (6, 'What comes next in this geometric sequence: 7, 28, 112, 448, 1792?', '7161', '7168', '7144', '7218', 'B'),
    (7, 'What comes next in this geometric sequence: 8, 16, 32, 64, 128?', '264', '232', '206', '256', 'D'),
    (8, 'What comes next in this geometric sequence: 9, 27, 81, 243, 729?', '2195', '2187', '2235', '2223', 'B'),
    (9, 'What comes next in this geometric sequence: 10, 40, 160, 640, 2560?', '10240', '10250', '10180', '10190', 'A'),
    (10, 'What comes next in this geometric sequence: 11, 22, 44, 88, 176?', '345', '352', '355', '372', 'B'),
    (11, 'What comes next in this geometric sequence: 12, 36, 108, 324, 972?', '2914', '2976', '2916', '2910', 'C'),
    (12, 'What comes next in this geometric sequence: 13, 52, 208, 832, 3328?', '13316', '13337', '13312', '13304', 'C'),
    (13, 'What comes next in this geometric sequence: 14, 28, 56, 112, 224?', '448', '398', '463', '466', 'A'),
    (14, 'What comes next in this geometric sequence: 15, 45, 135, 405, 1215?', '3645', '3655', '3648', '3670', 'A'),
    (15, 'What comes next in this geometric sequence: 16, 64, 256, 1024, 4096?', '16432', '16444', '16402', '16384', 'D'),
    (16, 'What comes next in this arithmetic sequence: 3, 5, 7, 9, 11?', '38', '-5', '-27', '13', 'D'),
    (17, 'What comes next in this arithmetic sequence: 5, 8, 11, 14, 17?', '-10', '68', '20', '0', 'C'),
    (18, 'What comes next in this arithmetic sequence: 7, 11, 15, 19, 23?', '33', '27', '37', '52', 'B'),
    (19, 'What comes next in this arithmetic sequence: 9, 14, 19, 24, 29?', '34', '42', '22', '9', 'A'),
    (20, 'What comes next in this arithmetic sequence: 11, 17, 23, 29, 35?', '29', '41', '33', '17', 'B'),
    (21, 'What comes next in this arithmetic sequence: 13, 15, 17, 19, 21?', '24', '23', '43', '16', 'B'),
    (22, 'What comes next in this arithmetic sequence: 15, 18, 21, 24, 27?', '23', '-30', '30', '50', 'C'),
    (23, 'What comes next in this arithmetic sequence: 17, 21, 25, 29, 33?', '-11', '49', '57', '37', 'D'),
    (24, 'What comes next in this arithmetic sequence: 19, 24, 29, 34, 39?', '20', '68', '47', '44', 'D'),
    (25, 'What comes next in this arithmetic sequence: 21, 27, 33, 39, 45?', '51', '15', '1', '57', 'A'),
    (26, 'What comes next in this arithmetic sequence: 23, 25, 27, 29, 31?', '33', '41', '9', '-7', 'A'),
    (27, 'What comes next in this arithmetic sequence: 25, 28, 31, 34, 37?', '44', '-10', '43', '40', 'D'),
    (28, 'What comes next in this arithmetic sequence: 27, 31, 35, 39, 43?', '67', '48', '47', '41', 'C'),
    (29, 'What comes next in this arithmetic sequence: 29, 34, 39, 44, 49?', '114', '50', '54', '49', 'C'),
    (30, 'What comes next in this arithmetic sequence: 31, 37, 43, 49, 55?', '41', '67', '61', '62', 'C'),
    (31, 'What is the missing number in this descending sequence: 90, 88, 86, 84, 82?', '62', '75', '116', '80', 'D'),
    (32, 'What is the missing number in this descending sequence: 87, 84, 81, 78, 75?', '77', '36', '22', '72', 'D'),
    (33, 'What is the missing number in this descending sequence: 84, 80, 76, 72, 68?', '52', '64', '72', '60', 'B'),
    (34, 'What is the missing number in this descending sequence: 81, 76, 71, 66, 61?', '-4', '104', '57', '56', 'D'),
    (35, 'What is the missing number in this descending sequence: 78, 72, 66, 60, 54?', '0', '66', '-12', '48', 'D'),
    (36, 'What is the missing number in this descending sequence: 75, 68, 61, 54, 47?', '42', '58', '40', '65', 'C'),
    (37, 'What is the missing number in this descending sequence: 72, 70, 68, 66, 64?', '80', '66', '69', '62', 'D'),
    (38, 'What is the missing number in this descending sequence: 69, 66, 63, 60, 57?', '54', '18', '59', '64', 'A'),
    (39, 'What is the missing number in this descending sequence: 66, 62, 58, 54, 50?', '46', '36', '96', '64', 'A'),
    (40, 'What is the missing number in this descending sequence: 63, 58, 53, 48, 43?', '13', '2', '38', '78', 'C'),
    (41, 'What is the missing number in this descending sequence: 60, 54, 48, 42, 36?', '23', '0', '10', '30', 'D'),
    (42, 'What is the missing number in this descending sequence: 57, 50, 43, 36, 29?', '22', '52', '16', '62', 'A'),
    (43, 'What is the missing number in this descending sequence: 54, 52, 50, 48, 46?', '44', '14', '19', '20', 'A'),
    (44, 'What is the missing number in this descending sequence: 51, 48, 45, 42, 39?', '36', '34', '41', '-12', 'A'),
    (45, 'What is the missing number in this descending sequence: 48, 44, 40, 36, 32?', '28', '26', '52', '8', 'A'),
    (46, 'What comes next in this increasing-gaps sequence: 1, 2, 4, 7, 11?', '8', '52', '16', '6', 'C'),
    (47, 'What comes next in this increasing-gaps sequence: 2, 4, 7, 11, 16?', '29', '22', '82', '-8', 'B'),
    (48, 'What comes next in this increasing-gaps sequence: 3, 6, 10, 15, 21?', '-22', '-2', '23', '28', 'D'),
    (49, 'What comes next in this increasing-gaps sequence: 4, 8, 13, 19, 26?', '40', '64', '34', '43', 'C'),
    (50, 'What comes next in this increasing-gaps sequence: 5, 10, 16, 23, 31?', '31', '55', '33', '40', 'D'),
    (51, 'What comes next in this increasing-gaps sequence: 6, 7, 9, 12, 16?', '21', '-39', '17', '81', 'A'),
    (52, 'What comes next in this increasing-gaps sequence: 7, 9, 12, 16, 21?', '27', '29', '2', '25', 'A'),
    (53, 'What comes next in this increasing-gaps sequence: 8, 11, 15, 20, 26?', '-15', '28', '69', '33', 'D'),
    (54, 'What comes next in this increasing-gaps sequence: 9, 13, 18, 24, 31?', '32', '36', '33', '39', 'D'),
    (55, 'What comes next in this increasing-gaps sequence: 10, 15, 21, 28, 36?', '43', '30', '45', '-3', 'C'),
    (56, 'What comes next in this increasing-gaps sequence: 11, 12, 14, 17, 21?', '11', '56', '26', '8', 'C'),
    (57, 'What comes next in this increasing-gaps sequence: 12, 14, 17, 21, 26?', '32', '41', '44', '36', 'A'),
    (58, 'What comes next in this increasing-gaps sequence: 13, 16, 20, 25, 31?', '58', '62', '38', '-2', 'C'),
    (59, 'What comes next in this increasing-gaps sequence: 14, 18, 23, 29, 36?', '52', '44', '38', '47', 'B'),
    (60, 'What comes next in this increasing-gaps sequence: 15, 20, 26, 33, 41?', '50', '70', '42', '58', 'A'),
    (61, 'What is the missing number in this double-and-add sequence: 2, 5, 11, 23, 47?', '93', '95', '113', '75', 'B'),
    (62, 'What is the missing number in this double-and-add sequence: 3, 8, 18, 38, 78?', '183', '160', '162', '158', 'D'),
    (63, 'What is the missing number in this double-and-add sequence: 4, 11, 25, 53, 109?', '225', '245', '221', '261', 'C'),
    (64, 'What is the missing number in this double-and-add sequence: 5, 14, 32, 68, 140?', '308', '224', '280', '284', 'D'),
    (65, 'What is the missing number in this double-and-add sequence: 6, 17, 39, 83, 171?', '332', '323', '347', '340', 'C'),
    (66, 'What is the missing number in this double-and-add sequence: 7, 20, 46, 98, 202?', '400', '434', '410', '430', 'C'),
    (67, 'What is the missing number in this double-and-add sequence: 8, 23, 53, 113, 233?', '467', '497', '473', '443', 'C'),
    (68, 'What is the missing number in this double-and-add sequence: 9, 19, 39, 79, 159?', '319', '334', '313', '301', 'A'),
    (69, 'What is the missing number in this double-and-add sequence: 10, 22, 46, 94, 190?', '332', '382', '376', '362', 'B'),
    (70, 'What is the missing number in this double-and-add sequence: 11, 25, 53, 109, 221?', '444', '450', '443', '445', 'D'),
    (71, 'What is the missing number in this double-and-add sequence: 12, 28, 60, 124, 252?', '556', '518', '508', '488', 'C'),
    (72, 'What is the missing number in this double-and-add sequence: 13, 31, 67, 139, 283?', '559', '564', '511', '571', 'D'),
    (73, 'What is the missing number in this double-and-add sequence: 14, 34, 74, 154, 314?', '634', '610', '682', '646', 'A'),
    (74, 'What is the missing number in this double-and-add sequence: 15, 37, 81, 169, 345?', '704', '712', '637', '697', 'D'),
    (75, 'What is the missing number in this double-and-add sequence: 16, 33, 67, 135, 271?', '561', '543', '541', '573', 'B'),
    (76, 'What comes next in this square-number sequence: 7, 12, 19, 28, 39?', '52', '64', '16', '88', 'A'),
    (77, 'What comes next in this square-number sequence: 13, 20, 29, 40, 53?', '68', '28', '74', '118', 'A'),
    (78, 'What comes next in this square-number sequence: 21, 30, 41, 54, 69?', '66', '84', '86', '80', 'C'),
    (79, 'What comes next in this square-number sequence: 31, 42, 55, 70, 87?', '146', '81', '106', '108', 'C'),
    (80, 'What comes next in this square-number sequence: 43, 56, 71, 88, 107?', '68', '119', '118', '128', 'D'),
    (81, 'What comes next in this square-number sequence: 52, 67, 84, 103, 124?', '147', '165', '144', '156', 'A'),
    (82, 'What comes next in this square-number sequence: 68, 85, 104, 125, 148?', '137', '168', '173', '171', 'C'),
    (83, 'What comes next in this square-number sequence: 86, 105, 126, 149, 174?', '194', '202', '171', '201', 'D'),
    (84, 'What comes next in this square-number sequence: 106, 127, 150, 175, 202?', '227', '231', '255', '235', 'B'),
    (85, 'What comes next in this square-number sequence: 128, 151, 176, 203, 232?', '265', '223', '266', '263', 'D'),
    (86, 'What comes next in this square-number sequence: 147, 172, 199, 228, 259?', '295', '292', '244', '340', 'B'),
    (87, 'What comes next in this square-number sequence: 173, 200, 229, 260, 293?', '328', '321', '338', '313', 'A'),
    (88, 'What comes next in this square-number sequence: 201, 230, 261, 294, 329?', '346', '359', '366', '360', 'C'),
    (89, 'What comes next in this square-number sequence: 231, 262, 295, 330, 367?', '400', '410', '406', '430', 'C'),
    (90, 'What comes next in this square-number sequence: 263, 296, 331, 368, 407?', '448', '458', '388', '488', 'A'),
    (91, 'What comes next in this triangular-number sequence: 3, 5, 8, 12, 17?', '23', '3', '-1', '53', 'A'),
    (92, 'What comes next in this triangular-number sequence: 6, 9, 13, 18, 24?', '31', '46', '-9', '39', 'A'),
    (93, 'What comes next in this triangular-number sequence: 10, 14, 19, 25, 32?', '28', '45', '40', '64', 'C'),
    (94, 'What comes next in this triangular-number sequence: 15, 20, 26, 33, 41?', '49', '50', '14', '55', 'B'),
    (95, 'What comes next in this triangular-number sequence: 17, 23, 30, 38, 47?', '57', '17', '51', '33', 'A'),
    (96, 'What comes next in this triangular-number sequence: 24, 31, 39, 48, 58?', '61', '45', '69', '79', 'C'),
    (97, 'What comes next in this triangular-number sequence: 32, 40, 49, 59, 70?', '52', '79', '82', '80', 'C'),
    (98, 'What comes next in this triangular-number sequence: 41, 50, 60, 71, 83?', '72', '126', '88', '96', 'D'),
    (99, 'What comes next in this triangular-number sequence: 47, 57, 68, 80, 93?', '167', '102', '116', '107', 'D'),
    (100, 'What comes next in this triangular-number sequence: 58, 69, 81, 94, 108?', '123', '127', '119', '131', 'A'),
    (101, 'What comes next in this triangular-number sequence: 70, 82, 95, 109, 124?', '131', '140', '130', '170', 'B'),
    (102, 'What comes next in this triangular-number sequence: 83, 96, 110, 125, 141?', '167', '183', '158', '138', 'C'),
    (103, 'What comes next in this triangular-number sequence: 93, 107, 122, 138, 155?', '173', '193', '203', '155', 'A'),
    (104, 'What comes next in this triangular-number sequence: 108, 123, 139, 156, 174?', '193', '178', '184', '191', 'A'),
    (105, 'What comes next in this triangular-number sequence: 124, 140, 157, 175, 194?', '214', '189', '204', '220', 'A'),
    (106, 'What is the next number in this Fibonacci-style sequence: 1, 2, 3, 5, 8?', '13', '10', '-11', '38', 'A'),
    (107, 'What is the next number in this Fibonacci-style sequence: 2, 3, 5, 8, 13?', '-4', '46', '21', '36', 'C'),
    (108, 'What is the next number in this Fibonacci-style sequence: 3, 4, 7, 11, 18?', '38', '29', '41', '-7', 'B'),
    (109, 'What is the next number in this Fibonacci-style sequence: 4, 5, 9, 14, 23?', '40', '37', '73', '87', 'B'),
    (110, 'What is the next number in this Fibonacci-style sequence: 5, 6, 11, 17, 28?', '46', '21', '60', '45', 'D'),
    (111, 'What is the next number in this Fibonacci-style sequence: 6, 7, 13, 20, 33?', '49', '63', '53', '52', 'C'),
    (112, 'What is the next number in this Fibonacci-style sequence: 7, 8, 15, 23, 38?', '68', '61', '56', '64', 'B'),
    (113, 'What is the next number in this Fibonacci-style sequence: 8, 9, 17, 26, 43?', '79', '59', '69', '76', 'C'),
    (114, 'What is the next number in this Fibonacci-style sequence: 9, 10, 19, 29, 48?', '77', '79', '52', '86', 'A'),
    (115, 'What is the next number in this Fibonacci-style sequence: 10, 11, 21, 32, 53?', '90', '145', '55', '85', 'D'),
    (116, 'What is the next number in this Fibonacci-style sequence: 11, 12, 23, 35, 58?', '118', '53', '93', '91', 'C'),
    (117, 'What is the next number in this Fibonacci-style sequence: 12, 13, 25, 38, 63?', '81', '101', '151', '125', 'B'),
    (118, 'What is the next number in this Fibonacci-style sequence: 13, 14, 27, 41, 68?', '145', '101', '107', '109', 'D'),
    (119, 'What is the next number in this Fibonacci-style sequence: 14, 15, 29, 44, 73?', '165', '114', '117', '109', 'C'),
    (120, 'What is the next number in this Fibonacci-style sequence: 15, 16, 31, 47, 78?', '173', '175', '124', '125', 'D'),
    (121, 'What comes next in this alternating sequence: 2, 50, 4, 47, 6?', '60', '10', '58', '7', 'B'),
    (122, 'What comes next in this alternating sequence: 3, 52, 6, 48, 9?', '11', '35', '15', '51', 'C'),
    (123, 'What comes next in this alternating sequence: 4, 54, 8, 49, 12?', '20', '15', '2', '-5', 'A'),
    (124, 'What comes next in this alternating sequence: 5, 56, 10, 50, 15?', '25', '15', '-15', '7', 'A'),
    (125, 'What comes next in this alternating sequence: 6, 58, 8, 51, 10?', '-4', '39', '14', '26', 'C'),
    (126, 'What comes next in this alternating sequence: 7, 60, 10, 57, 13?', '19', '43', '-29', '14', 'A'),
    (127, 'What comes next in this alternating sequence: 8, 62, 12, 58, 16?', '42', '-24', '34', '24', 'D'),
    (128, 'What comes next in this alternating sequence: 9, 64, 14, 59, 19?', '53', '89', '39', '29', 'D'),
    (129, 'What comes next in this alternating sequence: 10, 66, 12, 60, 14?', '-22', '54', '25', '18', 'D'),
    (130, 'What comes next in this alternating sequence: 11, 68, 14, 61, 17?', '8', '23', '24', '-37', 'B'),
    (131, 'What comes next in this alternating sequence: 12, 70, 16, 67, 20?', '28', '52', '78', '22', 'A'),
    (132, 'What comes next in this alternating sequence: 13, 72, 18, 68, 23?', '73', '33', '40', '9', 'B'),
    (133, 'What comes next in this alternating sequence: 14, 74, 16, 69, 18?', '72', '7', '22', '-14', 'C'),
    (134, 'What comes next in this alternating sequence: 15, 76, 18, 70, 21?', '32', '-33', '34', '27', 'D'),
    (135, 'What comes next in this alternating sequence: 16, 78, 20, 71, 24?', '32', '80', '22', '31', 'A'),
    (136, 'What is the missing number in this falling-step sequence: 75, 72, 68, 63, 57?', '60', '35', '42', '50', 'D'),
    (137, 'What is the missing number in this falling-step sequence: 73, 69, 64, 58, 51?', '45', '34', '43', '67', 'C'),
    (138, 'What is the missing number in this falling-step sequence: 71, 66, 60, 53, 45?', '-24', '18', '32', '36', 'D'),
    (139, 'What is the missing number in this falling-step sequence: 69, 63, 56, 48, 39?', '32', '77', '29', '4', 'C'),
    (140, 'What is the missing number in this falling-step sequence: 67, 60, 52, 43, 33?', '32', '52', '13', '22', 'D'),
    (141, 'What is the missing number in this falling-step sequence: 65, 57, 48, 38, 27?', '15', '21', '55', '10', 'A'),
    (142, 'What is the missing number in this falling-step sequence: 63, 54, 44, 33, 21?', '-16', '8', '12', '-7', 'B'),
    (143, 'What is the missing number in this falling-step sequence: 61, 51, 40, 28, 15?', '1', '-47', '-8', '16', 'A'),
    (144, 'What is the missing number in this falling-step sequence: 59, 48, 36, 23, 9?', '19', '-16', '-21', '-6', 'D'),
    (145, 'What is the missing number in this falling-step sequence: 57, 45, 32, 18, 3?', '-12', '-13', '-18', '-16', 'B'),
    (146, 'What is the missing number in this falling-step sequence: 55, 42, 28, 13, -3?', '-20', '-26', '-5', '-70', 'A'),
    (147, 'What is the missing number in this falling-step sequence: 53, 39, 24, 8, -9?', '-42', '-23', '13', '-27', 'D'),
    (148, 'What is the missing number in this falling-step sequence: 51, 36, 20, 3, -15?', '-34', '26', '-58', '-26', 'A'),
    (149, 'What is the missing number in this falling-step sequence: 49, 33, 16, -2, -21?', '-61', '-41', '-40', '-23', 'B'),
    (150, 'What is the missing number in this falling-step sequence: 47, 30, 12, -7, -27?', '-50', '-48', '-56', '-39', 'B'),
    (151, 'What comes next in this triple-minus-one sequence: 3, 8, 23, 68, 203?', '605', '633', '558', '608', 'D'),
    (152, 'What comes next in this triple-minus-one sequence: 4, 11, 32, 95, 284?', '839', '851', '827', '861', 'B'),
    (153, 'What comes next in this triple-minus-one sequence: 5, 14, 41, 122, 365?', '1093', '1088', '1094', '1064', 'C'),
    (154, 'What comes next in this triple-minus-one sequence: 6, 17, 50, 149, 446?', '1345', '1289', '1343', '1337', 'D'),
    (155, 'What comes next in this triple-minus-one sequence: 7, 20, 59, 176, 527?', '1578', '1580', '1588', '1556', 'B'),
    (156, 'What comes next in this triple-minus-one sequence: 8, 23, 68, 203, 608?', '1815', '1775', '1827', '1823', 'D'),
    (157, 'What comes next in this triple-minus-one sequence: 9, 26, 77, 230, 689?', '2060', '2116', '2006', '2066', 'D'),
    (158, 'What comes next in this triple-minus-one sequence: 10, 29, 86, 257, 770?', '2333', '2309', '2306', '2321', 'B'),
    (159, 'What comes next in this triple-minus-one sequence: 11, 32, 95, 284, 851?', '2545', '2559', '2552', '2548', 'C'),
    (160, 'What comes next in this triple-minus-one sequence: 12, 35, 104, 311, 932?', '2796', '2795', '2810', '2780', 'B'),
    (161, 'What comes next in this triple-minus-one sequence: 13, 38, 113, 338, 1013?', '3042', '3041', '3038', '3032', 'C'),
    (162, 'What comes next in this triple-minus-one sequence: 14, 41, 122, 365, 1094?', '3273', '3251', '3278', '3281', 'D'),
    (163, 'What comes next in this triple-minus-one sequence: 15, 44, 131, 392, 1175?', '3524', '3525', '3494', '3512', 'A'),
    (164, 'What comes next in this triple-minus-one sequence: 16, 47, 140, 419, 1256?', '3761', '3767', '3766', '3777', 'B'),
    (165, 'What comes next in this triple-minus-one sequence: 17, 50, 149, 446, 1337?', '4012', '3970', '4010', '4007', 'C'),
    (166, 'What is the next number in this mixed-pattern sequence: 2, 5, 4, 9, 10?', '11', '18', '26', '14', 'D'),
    (167, 'What is the next number in this mixed-pattern sequence: 3, 7, 6, 13, 15?', '20', '44', '24', '30', 'A'),
    (168, 'What is the next number in this mixed-pattern sequence: 4, 9, 8, 17, 20?', '35', '62', '26', '-24', 'C'),
    (169, 'What is the next number in this mixed-pattern sequence: 5, 11, 7, 15, 13?', '15', '-1', '22', '17', 'D'),
    (170, 'What is the next number in this mixed-pattern sequence: 6, 9, 9, 15, 18?', '-25', '73', '15', '23', 'D'),
    (171, 'What is the next number in this mixed-pattern sequence: 7, 11, 11, 19, 23?', '34', '29', '39', '19', 'B'),
    (172, 'What is the next number in this mixed-pattern sequence: 8, 13, 10, 17, 16?', '19', '-16', '20', '70', 'C'),
    (173, 'What is the next number in this mixed-pattern sequence: 9, 15, 12, 21, 21?', '41', '26', '16', '18', 'B'),
    (174, 'What is the next number in this mixed-pattern sequence: 10, 13, 14, 21, 26?', '44', '32', '37', '12', 'B'),
    (175, 'What is the next number in this mixed-pattern sequence: 11, 15, 13, 19, 19?', '23', '28', '-13', '31', 'A'),
    (176, 'What is the next number in this mixed-pattern sequence: 12, 17, 15, 23, 24?', '65', '39', '35', '29', 'D'),
    (177, 'What is the next number in this mixed-pattern sequence: 13, 19, 17, 27, 29?', '31', '-15', '35', '20', 'C'),
    (178, 'What is the next number in this mixed-pattern sequence: 14, 17, 16, 21, 22?', '26', '23', '24', '-22', 'A'),
    (179, 'What is the next number in this mixed-pattern sequence: 15, 19, 18, 25, 27?', '82', '12', '47', '32', 'D'),
    (180, 'What is the next number in this mixed-pattern sequence: 16, 21, 20, 29, 32?', '13', '38', '23', '40', 'B'),
    (181, 'If today is Tuesday, what day will it be in 8 days?', 'Thursday', 'Friday', 'Wednesday', 'Monday', 'C'),
    (182, 'If today is Thursday, what day will it be in 11 days?', 'Saturday', 'Thursday', 'Tuesday', 'Monday', 'D'),
    (183, 'If today is Saturday, what day will it be in 14 days?', 'Monday', 'Saturday', 'Sunday', 'Thursday', 'B'),
    (184, 'If today is Monday, what day will it be in 17 days?', 'Tuesday', 'Friday', 'Wednesday', 'Thursday', 'D'),
    (185, 'If today is Wednesday, what day will it be in 20 days?', 'Monday', 'Thursday', 'Friday', 'Tuesday', 'D'),
    (186, 'If today is Friday, what day will it be in 23 days?', 'Wednesday', 'Monday', 'Saturday', 'Sunday', 'D'),
    (187, 'If today is Sunday, what day will it be in 26 days?', 'Wednesday', 'Tuesday', 'Sunday', 'Friday', 'D'),
    (188, 'If today is Tuesday, what day will it be in 29 days?', 'Sunday', 'Wednesday', 'Tuesday', 'Monday', 'B'),
    (189, 'If today is Thursday, what day will it be in 32 days?', 'Thursday', 'Monday', 'Friday', 'Wednesday', 'B'),
    (190, 'If today is Saturday, what day will it be in 35 days?', 'Wednesday', 'Friday', 'Saturday', 'Tuesday', 'C'),
    (191, 'If today is Monday, what day will it be in 38 days?', 'Thursday', 'Sunday', 'Monday', 'Friday', 'A'),
    (192, 'If today is Wednesday, what day will it be in 41 days?', 'Thursday', 'Wednesday', 'Sunday', 'Tuesday', 'D'),
    (193, 'If today is Friday, what day will it be in 44 days?', 'Sunday', 'Friday', 'Saturday', 'Tuesday', 'A'),
    (194, 'If today is Sunday, what day will it be in 47 days?', 'Thursday', 'Sunday', 'Friday', 'Tuesday', 'C'),
    (195, 'If today is Tuesday, what day will it be in 50 days?', 'Sunday', 'Saturday', 'Wednesday', 'Friday', 'C'),
    (196, 'If today is Thursday, what day will it be in 53 days?', 'Saturday', 'Thursday', 'Friday', 'Monday', 'D'),
    (197, 'If today is Saturday, what day will it be in 56 days?', 'Wednesday', 'Saturday', 'Thursday', 'Tuesday', 'B'),
    (198, 'If today is Monday, what day will it be in 59 days?', 'Wednesday', 'Sunday', 'Thursday', 'Friday', 'C'),
    (199, 'If today is Wednesday, what day will it be in 62 days?', 'Thursday', 'Wednesday', 'Tuesday', 'Monday', 'C'),
    (200, 'If today is Friday, what day will it be in 65 days?', 'Friday', 'Sunday', 'Wednesday', 'Monday', 'B'),
    (201, 'If today is Sunday, what day will it be in 68 days?', 'Friday', 'Saturday', 'Thursday', 'Sunday', 'A'),
    (202, 'If today is Tuesday, what day will it be in 71 days?', 'Monday', 'Wednesday', 'Saturday', 'Friday', 'B'),
    (203, 'If today is Thursday, what day will it be in 74 days?', 'Monday', 'Sunday', 'Tuesday', 'Friday', 'A'),
    (204, 'If today is Saturday, what day will it be in 77 days?', 'Tuesday', 'Wednesday', 'Saturday', 'Friday', 'C'),
    (205, 'If today is Monday, what day will it be in 80 days?', 'Sunday', 'Tuesday', 'Thursday', 'Wednesday', 'C'),
    (206, 'If today is Wednesday, what day was it 9 days ago?', 'Thursday', 'Saturday', 'Monday', 'Tuesday', 'C'),
    (207, 'If today is Saturday, what day was it 13 days ago?', 'Friday', 'Tuesday', 'Sunday', 'Thursday', 'C'),
    (208, 'If today is Tuesday, what day was it 17 days ago?', 'Saturday', 'Wednesday', 'Sunday', 'Friday', 'A'),
    (209, 'If today is Friday, what day was it 21 days ago?', 'Friday', 'Monday', 'Tuesday', 'Saturday', 'A'),
    (210, 'If today is Monday, what day was it 25 days ago?', 'Sunday', 'Monday', 'Saturday', 'Thursday', 'D'),
    (211, 'If today is Thursday, what day was it 29 days ago?', 'Saturday', 'Wednesday', 'Sunday', 'Tuesday', 'B'),
    (212, 'If today is Sunday, what day was it 33 days ago?', 'Saturday', 'Monday', 'Tuesday', 'Wednesday', 'C'),
    (213, 'If today is Wednesday, what day was it 37 days ago?', 'Monday', 'Thursday', 'Wednesday', 'Tuesday', 'A'),
    (214, 'If today is Saturday, what day was it 41 days ago?', 'Monday', 'Sunday', 'Tuesday', 'Saturday', 'B'),
    (215, 'If today is Tuesday, what day was it 45 days ago?', 'Thursday', 'Saturday', 'Wednesday', 'Friday', 'B'),
    (216, 'If today is Friday, what day was it 49 days ago?', 'Thursday', 'Monday', 'Friday', 'Sunday', 'C'),
    (217, 'If today is Monday, what day was it 53 days ago?', 'Sunday', 'Tuesday', 'Saturday', 'Thursday', 'D'),
    (218, 'If today is Thursday, what day was it 57 days ago?', 'Saturday', 'Thursday', 'Wednesday', 'Monday', 'C'),
    (219, 'If today is Sunday, what day was it 61 days ago?', 'Tuesday', 'Sunday', 'Friday', 'Saturday', 'A'),
    (220, 'If today is Wednesday, what day was it 65 days ago?', 'Thursday', 'Monday', 'Sunday', 'Wednesday', 'B'),
    (221, 'If today is Saturday, what day was it 69 days ago?', 'Sunday', 'Saturday', 'Tuesday', 'Friday', 'A'),
    (222, 'If today is Tuesday, what day was it 73 days ago?', 'Sunday', 'Saturday', 'Thursday', 'Friday', 'B'),
    (223, 'If today is Friday, what day was it 77 days ago?', 'Monday', 'Wednesday', 'Thursday', 'Friday', 'D'),
    (224, 'If today is Monday, what day was it 81 days ago?', 'Thursday', 'Wednesday', 'Monday', 'Friday', 'A'),
    (225, 'If today is Thursday, what day was it 85 days ago?', 'Tuesday', 'Friday', 'Wednesday', 'Monday', 'C'),
    (226, 'If today is Sunday, what day was it 89 days ago?', 'Thursday', 'Sunday', 'Tuesday', 'Saturday', 'C'),
    (227, 'If today is Wednesday, what day was it 93 days ago?', 'Friday', 'Wednesday', 'Thursday', 'Monday', 'D'),
    (228, 'If today is Saturday, what day was it 97 days ago?', 'Saturday', 'Wednesday', 'Thursday', 'Sunday', 'D'),
    (229, 'If today is Tuesday, what day was it 101 days ago?', 'Thursday', 'Monday', 'Saturday', 'Sunday', 'C'),
    (230, 'If today is Friday, what day was it 105 days ago?', 'Tuesday', 'Friday', 'Wednesday', 'Thursday', 'B'),
    (231, 'If it is 08:05 now, what time will it be in 35 minutes?', '07:55', '08:40', '09:10', '09:20', 'B'),
    (232, 'If it is 08:22 now, what time will it be in 42 minutes?', '09:04', '08:09', '08:54', '08:14', 'A'),
    (233, 'If it is 08:39 now, what time will it be in 49 minutes?', '09:48', '10:28', '07:58', '09:28', 'D'),
    (234, 'If it is 08:56 now, what time will it be in 56 minutes?', '09:12', '09:52', '10:47', '11:22', 'B'),
    (235, 'If it is 09:13 now, what time will it be in 63 minutes?', '09:01', '10:46', '11:11', '10:16', 'D'),
    (236, 'If it is 09:30 now, what time will it be in 70 minutes?', '10:40', '09:50', '09:55', '10:45', 'A'),
    (237, 'If it is 09:47 now, what time will it be in 77 minutes?', '11:49', '11:19', '11:14', '11:04', 'D'),
    (238, 'If it is 10:04 now, what time will it be in 84 minutes?', '12:28', '11:28', '10:48', '11:33', 'B'),
    (239, 'If it is 10:21 now, what time will it be in 91 minutes?', '12:52', '11:52', '10:22', '10:57', 'B'),
    (240, 'If it is 10:38 now, what time will it be in 98 minutes?', '12:16', '12:41', '13:46', '11:16', 'A'),
    (241, 'If it is 10:55 now, what time will it be in 105 minutes?', '12:55', '11:10', '12:40', '13:55', 'C'),
    (242, 'If it is 11:12 now, what time will it be in 112 minutes?', '13:04', '12:24', '12:34', '12:14', 'A'),
    (243, 'If it is 11:29 now, what time will it be in 119 minutes?', '14:28', '14:43', '12:43', '13:28', 'D'),
    (244, 'If it is 11:46 now, what time will it be in 126 minutes?', '13:52', '14:17', '14:22', '13:22', 'A'),
    (245, 'If it is 12:03 now, what time will it be in 133 minutes?', '14:16', '13:31', '14:51', '14:26', 'A'),
    (246, 'If it is 12:20 now, what time will it be in 140 minutes?', '15:55', '15:40', '14:40', '14:30', 'C'),
    (247, 'If it is 12:37 now, what time will it be in 147 minutes?', '14:54', '14:44', '15:54', '15:04', 'D'),
    (248, 'If it is 12:54 now, what time will it be in 154 minutes?', '15:28', '15:53', '14:53', '15:18', 'A'),
    (249, 'If it is 13:11 now, what time will it be in 161 minutes?', '16:12', '15:02', '14:22', '15:52', 'D'),
    (250, 'If it is 13:28 now, what time will it be in 168 minutes?', '15:36', '16:26', '17:06', '16:16', 'D'),
    (251, 'If it is 13:45 now, what time will it be in 175 minutes?', '16:40', '16:50', '15:25', '18:10', 'A'),
    (252, 'If it is 14:02 now, what time will it be in 182 minutes?', '17:04', '17:29', '16:39', '18:34', 'A'),
    (253, 'If it is 14:19 now, what time will it be in 189 minutes?', '17:28', '18:08', '18:18', '17:58', 'A'),
    (254, 'If it is 14:36 now, what time will it be in 196 minutes?', '18:17', '17:37', '17:47', '17:52', 'D'),
    (255, 'If it is 14:53 now, what time will it be in 203 minutes?', '18:06', '19:06', '18:16', '18:56', 'C'),
    (256, 'How many minutes are there between 06:20 and 07:55?', '95', '77', '59', '135', 'A'),
    (257, 'How many minutes are there between 06:31 and 08:15?', '111', '68', '95', '104', 'D'),
    (258, 'How many minutes are there between 06:42 and 08:35?', '111', '113', '143', '115', 'B'),
    (259, 'How many minutes are there between 06:53 and 08:55?', '129', '122', '140', '131', 'B'),
    (260, 'How many minutes are there between 07:04 and 09:15?', '138', '71', '134', '131', 'D'),
    (261, 'How many minutes are there between 07:15 and 09:35?', '140', '80', '142', '131', 'A'),
    (262, 'How many minutes are there between 07:26 and 09:55?', '124', '142', '113', '149', 'D'),
    (263, 'How many minutes are there between 07:37 and 10:15?', '158', '138', '218', '148', 'A'),
    (264, 'How many minutes are there between 07:48 and 10:35?', '192', '172', '167', '152', 'C'),
    (265, 'How many minutes are there between 07:59 and 10:55?', '176', '171', '178', '206', 'A'),
    (266, 'How many minutes are there between 08:10 and 11:15?', '185', '184', '210', '173', 'A'),
    (267, 'How many minutes are there between 08:21 and 11:35?', '158', '198', '203', '194', 'D'),
    (268, 'How many minutes are there between 08:32 and 11:55?', '197', '206', '203', '218', 'C'),
    (269, 'How many minutes are there between 08:43 and 12:15?', '230', '192', '204', '212', 'D'),
    (270, 'How many minutes are there between 08:54 and 12:35?', '231', '221', '220', '246', 'B'),
    (271, 'How many minutes are there between 09:05 and 12:55?', '234', '242', '229', '230', 'D'),
    (272, 'How many minutes are there between 09:16 and 13:15?', '254', '275', '239', '269', 'C'),
    (273, 'How many minutes are there between 09:27 and 13:35?', '247', '223', '224', '248', 'D'),
    (274, 'How many minutes are there between 09:38 and 13:55?', '293', '256', '232', '257', 'D'),
    (275, 'How many minutes are there between 09:49 and 14:15?', '266', '251', '272', '286', 'A'),
    (276, 'How many minutes are there between 10:00 and 14:35?', '275', '267', '245', '311', 'A'),
    (277, 'How many minutes are there between 10:11 and 14:55?', '264', '284', '236', '309', 'B'),
    (278, 'How many minutes are there between 10:22 and 15:15?', '285', '301', '333', '293', 'D'),
    (279, 'How many minutes are there between 10:33 and 15:35?', '302', '311', '298', '309', 'A'),
    (280, 'How many minutes are there between 10:44 and 15:55?', '299', '263', '311', '317', 'C'),
    (281, 'Which word comes first alphabetically: cloud, cucumber, ember, or apple?', 'yarn', 'apple', 'meadow', 'spider', 'B'),
    (282, 'Which word comes first alphabetically: helmet, suitcase, glacier, or temple?', 'glacier', 'feather', 'comet', 'banana', 'A'),
    (283, 'Which word comes first alphabetically: hammer, mountain, spoon, or scarf?', 'pizza', 'mint', 'hammer', 'cucumber', 'C'),
    (284, 'Which word comes first alphabetically: jelly, cushion, apricot, or school?', 'kettle', 'apricot', 'melon', 'table', 'B'),
    (285, 'Which word comes first alphabetically: pocket, silver, biscuit, or yogurt?', 'berry', 'crystal', 'walnut', 'biscuit', 'D'),
    (286, 'Which word comes first alphabetically: shelter, tomato, diamond, or palace?', 'mountain', 'suitcase', 'marble', 'diamond', 'D'),
    (287, 'Which word comes first alphabetically: shovel, mountain, tomato, or kettle?', 'coral', 'kettle', 'rocket', 'tractor', 'B'),
    (288, 'Which word comes first alphabetically: marble, xylophone, pizza, or orchid?', 'donkey', 'meadow', 'comet', 'marble', 'D'),
    (289, 'Which word comes first alphabetically: turtle, wizard, cucumber, or shadow?', 'quartz', 'cucumber', 'pumpkin', 'ocean', 'B'),
    (290, 'Which word comes first alphabetically: signal, spoon, carrot, or bridge?', 'bridge', 'violin', 'orchid', 'napkin', 'A'),
    (291, 'Which word comes first alphabetically: candle, melon, blanket, or pocket?', 'blanket', 'cherry', 'napkin', 'pencil', 'A'),
    (292, 'Which word comes first alphabetically: lemon, mint, kettle, or orchid?', 'jungle', 'kettle', 'glacier', 'simple', 'B'),
    (293, 'Which word comes first alphabetically: helmet, orchid, scarf, or bottle?', 'ginger', 'blanket', 'bottle', 'dolphin', 'C'),
    (294, 'Which word comes first alphabetically: summer, thunder, cucumber, or apple?', 'garlic', 'apple', 'orchid', 'spring', 'B'),
    (295, 'Which word comes first alphabetically: shelter, noodle, lantern, or spoon?', 'lantern', 'melon', 'valley', 'pizza', 'A'),
    (296, 'Which word comes first alphabetically: season, pancake, zephyr, or suitcase?', 'pancake', 'cottage', 'shadow', 'ginger', 'A'),
    (297, 'Which word comes first alphabetically: walnut, shelter, turtle, or yellow?', 'ember', 'shelter', 'crystal', 'ladder', 'B'),
    (298, 'Which word comes first alphabetically: temple, melon, palace, or button?', 'ocean', 'button', 'quartz', 'ginger', 'B'),
    (299, 'Which word comes first alphabetically: orchard, tractor, shelter, or yellow?', 'orchard', 'hammer', 'silver', 'zebra', 'A'),
    (300, 'Which word comes first alphabetically: mountain, pancake, violin, or jelly?', 'salad', 'jelly', 'cucumber', 'garlic', 'B'),
    (301, 'Which word comes first alphabetically: apricot, zipper, cherry, or pizza?', 'cloud', 'yarn', 'zebra', 'apricot', 'D'),
    (302, 'Which word comes first alphabetically: meadow, paper, candle, or river?', 'quartz', 'feather', 'apricot', 'candle', 'D'),
    (303, 'Which word comes first alphabetically: forest, yarn, tomato, or dolphin?', 'dolphin', 'pizza', 'iceberg', 'orchid', 'A'),
    (304, 'Which word comes first alphabetically: melon, coral, yellow, or dragon?', 'suitcase', 'shelter', 'coral', 'spoon', 'C'),
    (305, 'Which word comes first alphabetically: coffee, table, planet, or iceberg?', 'school', 'scarf', 'cushion', 'coffee', 'D'),
    (306, 'Which word is the longest: xylophone, bridge, cottage, or river?', 'ribbon', 'xylophone', 'apricot', 'rabbit', 'B'),
    (307, 'Which word is the longest: yarn, teapot, berry, or lantern?', 'lantern', 'school', 'scarf', 'biscuit', 'A'),
    (308, 'Which word is the longest: xylophone, garden, berry, or satchel?', 'xylophone', 'velvet', 'button', 'satchel', 'A'),
    (309, 'Which word is the longest: spring, umbrella, table, or iceberg?', 'jungle', 'pancake', 'umbrella', 'candle', 'C'),
    (310, 'Which word is the longest: xylophone, mint, quartz, or pancake?', 'lantern', 'comet', 'xylophone', 'orange', 'C'),
    (311, 'Which word is the longest: jelly, whistle, cucumber, or tomato?', 'biscuit', 'cucumber', 'castle', 'pizza', 'B'),
    (312, 'Which word is the longest: button, xylophone, tractor, or paper?', 'garden', 'xylophone', 'cloud', 'island', 'B'),
    (313, 'Which word is the longest: suitcase, blanket, mosaic, or mint?', 'whistle', 'winter', 'teapot', 'suitcase', 'D'),
    (314, 'Which word is the longest: crystal, parcel, mountain, or apple?', 'galaxy', 'mountain', 'garlic', 'bridge', 'B'),
    (315, 'Which word is the longest: salad, pumpkin, mountain, or simple?', 'jacket', 'mountain', 'ladder', 'temple', 'B'),
    (316, 'Which word is the longest: ocean, island, cucumber, or whisper?', 'pillow', 'marble', 'cucumber', 'helmet', 'C'),
    (317, 'Which word is the longest: cucumber, ember, spider, or cushion?', 'silver', 'ladder', 'cushion', 'cucumber', 'D'),
    (318, 'Which word is the longest: table, ribbon, cottage, or mint?', 'spring', 'cottage', 'helmet', 'garlic', 'B'),
    (319, 'Which word is the longest: coral, pancake, bucket, or yarn?', 'noodle', 'tomato', 'jelly', 'pancake', 'D'),
    (320, 'Which word is the longest: feather, planet, suitcase, or spoon?', 'scarf', 'blanket', 'satchel', 'suitcase', 'D'),
    (321, 'Which word is the longest: ticket, umbrella, cottage, or yarn?', 'garden', 'pumpkin', 'umbrella', 'melon', 'C'),
    (322, 'Which word is the longest: grape, pancake, palace, or yarn?', 'scarf', 'pancake', 'bridge', 'flame', 'B'),
    (323, 'Which word is the longest: lemon, apricot, spider, or yarn?', 'shelter', 'island', 'apricot', 'winter', 'C'),
    (324, 'Which word is the longest: comet, umbrella, pancake, or island?', 'lilac', 'diamond', 'umbrella', 'dragon', 'C'),
    (325, 'Which word is the longest: salad, orange, mint, or cottage?', 'thunder', 'simple', 'castle', 'cottage', 'D'),
    (326, 'Which word is the longest: pumpkin, pebble, lilac, or xylophone?', 'cloud', 'xylophone', 'teapot', 'satchel', 'B'),
    (327, 'Which word is the longest: mountain, thunder, walnut, or berry?', 'mountain', 'river', 'blanket', 'lantern', 'A'),
    (328, 'Which word is the longest: ticket, biscuit, mountain, or coral?', 'mountain', 'yogurt', 'coral', 'garlic', 'A'),
    (329, 'Which word is the longest: wagon, garlic, mountain, or thunder?', 'mountain', 'coral', 'tractor', 'spring', 'A'),
    (330, 'Which word is the longest: yarn, pumpkin, rabbit, or zebra?', 'pumpkin', 'table', 'umbrella', 'castle', 'A'),
    (331, 'Which word has the most vowels: harbor, xylophone, mountain, or zephyr?', 'turtle', 'donkey', 'mountain', 'pebble', 'C'),
    (332, 'Which word has the most vowels: mountain, donkey, apricot, or scarf?', 'velvet', 'mountain', 'forest', 'spring', 'B'),
    (333, 'Which word has the most vowels: garlic, zephyr, mountain, or glacier?', 'violin', 'guitar', 'mountain', 'banana', 'C'),
    (334, 'Which word has the most vowels: noodle, scarf, salad, or mountain?', 'bottle', 'yogurt', 'mountain', 'meadow', 'C'),
    (335, 'Which word has the most vowels: jelly, wizard, avocado, or cushion?', 'winter', 'pumpkin', 'berry', 'avocado', 'D'),
    (336, 'Which word has the most vowels: zephyr, mountain, coffee, or bucket?', 'mountain', 'cottage', 'signal', 'comet', 'A'),
    (337, 'Which word has the most vowels: ocean, scarf, avocado, or ember?', 'dolphin', 'avocado', 'signal', 'pillow', 'B'),
    (338, 'Which word has the most vowels: bridge, suitcase, biscuit, or yarn?', 'yarn', 'suitcase', 'jacket', 'jungle', 'B'),
    (339, 'Which word has the most vowels: mountain, xylophone, marble, or crystal?', 'coffee', 'tomato', 'jelly', 'mountain', 'D'),
    (340, 'Which word has the most vowels: avocado, meadow, yarn, or zipper?', 'avocado', 'yogurt', 'simple', 'ticket', 'A'),
    (341, 'Which word has the most vowels: feather, suitcase, quartz, or yarn?', 'yarn', 'suitcase', 'river', 'pizza', 'B'),
    (342, 'Which word has the most vowels: yarn, biscuit, mountain, or shadow?', 'shadow', 'ticket', 'zebra', 'mountain', 'D'),
    (343, 'Which word has the most vowels: temple, scarf, feather, or avocado?', 'shelter', 'cloud', 'meadow', 'avocado', 'D'),
    (344, 'Which word has the most vowels: comet, season, avocado, or crystal?', 'shadow', 'avocado', 'apricot', 'rocket', 'B'),
    (345, 'Which word has the most vowels: yogurt, cottage, mountain, or cherry?', 'carpet', 'cottage', 'mountain', 'walnut', 'C'),
    (346, 'Which word has the most vowels: zephyr, pumpkin, meadow, or avocado?', 'zipper', 'jacket', 'avocado', 'marble', 'C'),
    (347, 'Which word has the most vowels: yarn, biscuit, mountain, or dolphin?', 'garden', 'noodle', 'mountain', 'salad', 'C'),
    (348, 'Which word has the most vowels: candle, guitar, berry, or suitcase?', 'summer', 'jelly', 'season', 'suitcase', 'D'),
    (349, 'Which word has the most vowels: iceberg, bottle, suitcase, or cherry?', 'kettle', 'valley', 'feather', 'suitcase', 'D'),
    (350, 'Which word has the most vowels: crystal, tomato, velvet, or mountain?', 'rainbow', 'mountain', 'jacket', 'mint', 'B'),
    (351, 'Which word has the most vowels: suitcase, mint, rocket, or tomato?', 'suitcase', 'pancake', 'lantern', 'ribbon', 'A'),
    (352, 'Which word has the most vowels: pancake, yarn, mountain, or window?', 'mountain', 'ladder', 'guitar', 'garlic', 'A'),
    (353, 'Which word has the most vowels: avocado, scarf, parcel, or mosaic?', 'tomato', 'harbor', 'avocado', 'cucumber', 'C'),
    (354, 'Which word has the most vowels: suitcase, biscuit, pebble, or zephyr?', 'spoon', 'suitcase', 'meadow', 'pebble', 'B'),
    (355, 'Which word has the most vowels: spring, mountain, pumpkin, or noodle?', 'mountain', 'castle', 'coral', 'forest', 'A'),
    (356, 'Which word contains a double letter: apple, spring, mint, or mountain?', 'mountain', 'apple', 'mint', 'spring', 'B'),
    (357, 'Which word contains a double letter: teapot, apricot, bottle, or orchid?', 'apricot', 'bottle', 'teapot', 'orchid', 'B'),
    (358, 'Which word contains a double letter: donkey, yogurt, spider, or butter?', 'butter', 'donkey', 'yogurt', 'spider', 'A'),
    (359, 'Which word contains a double letter: shovel, ocean, tractor, or coffee?', 'tractor', 'ocean', 'shovel', 'coffee', 'D'),
    (360, 'Which word contains a double letter: yogurt, island, salad, or doodle?', 'island', 'doodle', 'salad', 'yogurt', 'B'),
    (361, 'Which word contains a double letter: happy, ember, apricot, or guitar?', 'ember', 'apricot', 'guitar', 'happy', 'D'),
    (362, 'Which word contains a double letter: window, little, season, or signal?', 'signal', 'season', 'little', 'window', 'C'),
    (363, 'Which word contains a double letter: rocket, avocado, letter, or crystal?', 'avocado', 'crystal', 'rocket', 'letter', 'D'),
    (364, 'Which word contains a double letter: flame, zebra, rabbit, or kernel?', 'kernel', 'rabbit', 'zebra', 'flame', 'B'),
    (365, 'Which word contains a double letter: dragon, yellow, donkey, or paper?', 'donkey', 'yellow', 'paper', 'dragon', 'B'),
    (366, 'Which word contains a double letter: bubble, satchel, helmet, or garden?', 'helmet', 'bubble', 'garden', 'satchel', 'B'),
    (367, 'Which word contains a double letter: rainbow, salad, cuddle, or cushion?', 'salad', 'cushion', 'rainbow', 'cuddle', 'D'),
    (368, 'Which word contains a double letter: garden, kernel, dinner, or table?', 'table', 'garden', 'kernel', 'dinner', 'D'),
    (369, 'Which word contains a double letter: lemon, diamond, fossil, or guitar?', 'diamond', 'lemon', 'fossil', 'guitar', 'C'),
    (370, 'Which word contains a double letter: temple, salad, whistle, or kettle?', 'temple', 'whistle', 'salad', 'kettle', 'D'),
    (371, 'Which word contains a double letter: matter, whistle, paper, or winter?', 'paper', 'matter', 'winter', 'whistle', 'B'),
    (372, 'Which word contains a double letter: yogurt, shelter, merry, or biscuit?', 'yogurt', 'shelter', 'biscuit', 'merry', 'D'),
    (373, 'Which word contains a double letter: puzzle, pumpkin, velvet, or comet?', 'puzzle', 'velvet', 'comet', 'pumpkin', 'A'),
    (374, 'Which word contains a double letter: ripple, shadow, turtle, or shovel?', 'shadow', 'shovel', 'turtle', 'ripple', 'D'),
    (375, 'Which word contains a double letter: meadow, velvet, sunny, or garden?', 'garden', 'sunny', 'meadow', 'velvet', 'B'),
    (376, 'Which word contains a double letter: galaxy, ginger, supper, or glacier?', 'galaxy', 'ginger', 'glacier', 'supper', 'D'),
    (377, 'Which word contains a double letter: palace, pencil, lilac, or tunnel?', 'lilac', 'tunnel', 'pencil', 'palace', 'B'),
    (378, 'Which word contains a double letter: cucumber, rocket, melon, or wallet?', 'wallet', 'rocket', 'melon', 'cucumber', 'A'),
    (379, 'Which word contains a double letter: table, whistle, dragon, or melon?', 'melon', 'table', 'whistle', 'dragon', 'C'),
    (380, 'Which word contains a double letter: tractor, window, ginger, or yarn?', 'window', 'yarn', 'tractor', 'ginger', 'A'),
    (381, 'All blabs are brabs. No brabs are clabs. Which must be true?', 'Some clabs are blabs.', 'All blabs are clabs.', 'Some blabs are clabs.', 'No blabs are clabs.', 'D'),
    (382, 'Some crabs are drabs. All drabs are flabs. Which must be true?', 'Some crabs are flabs.', 'All crabs are flabs.', 'Some flabs are not crabs.', 'No crabs are flabs.', 'A'),
    (383, 'No frabs are glabs. Some glabs are grabs. Which must be true?', 'No grabs are frabs.', 'Some grabs are not frabs.', 'All grabs are frabs.', 'Some grabs are frabs.', 'B'),
    (384, 'All plabs are prabs. Some plabs are skabs. Which must be true?', 'Some skabs are not prabs.', 'Some skabs are prabs.', 'All skabs are prabs.', 'No skabs are prabs.', 'B'),
    (385, 'All slabs are smabs. No smabs are snabs. Which must be true?', 'Some snabs are slabs.', 'All slabs are snabs.', 'No slabs are snabs.', 'Some slabs are snabs.', 'C'),
    (386, 'Some spabs are stabs. All stabs are swabs. Which must be true?', 'No spabs are swabs.', 'Some swabs are not spabs.', 'All spabs are swabs.', 'Some spabs are swabs.', 'D'),
    (387, 'No trabs are twabs. Some twabs are blebs. Which must be true?', 'All blebs are trabs.', 'No blebs are trabs.', 'Some blebs are trabs.', 'Some blebs are not trabs.', 'D'),
    (388, 'All brebs are clebs. Some brebs are crebs. Which must be true?', 'No crebs are clebs.', 'Some crebs are clebs.', 'All crebs are clebs.', 'Some crebs are not clebs.', 'B'),
    (389, 'All drebs are flebs. No flebs are frebs. Which must be true?', 'Some frebs are drebs.', 'No drebs are frebs.', 'Some drebs are frebs.', 'All drebs are frebs.', 'B'),
    (390, 'Some glebs are grebs. All grebs are plebs. Which must be true?', 'All glebs are plebs.', 'Some glebs are plebs.', 'Some plebs are not glebs.', 'No glebs are plebs.', 'B'),
    (391, 'No prebs are skebs. Some skebs are slebs. Which must be true?', 'Some slebs are prebs.', 'No slebs are prebs.', 'All slebs are prebs.', 'Some slebs are not prebs.', 'D'),
    (392, 'All smebs are snebs. Some smebs are spebs. Which must be true?', 'All spebs are snebs.', 'Some spebs are not snebs.', 'No spebs are snebs.', 'Some spebs are snebs.', 'D'),
    (393, 'All stebs are swebs. No swebs are trebs. Which must be true?', 'No stebs are trebs.', 'All stebs are trebs.', 'Some stebs are trebs.', 'Some trebs are stebs.', 'A'),
    (394, 'Some twebs are blibs. All blibs are bribs. Which must be true?', 'All twebs are bribs.', 'Some twebs are bribs.', 'No twebs are bribs.', 'Some bribs are not twebs.', 'B'),
    (395, 'No clibs are cribs. Some cribs are dribs. Which must be true?', 'Some dribs are clibs.', 'All dribs are clibs.', 'No dribs are clibs.', 'Some dribs are not clibs.', 'D'),
    (396, 'All flibs are fribs. Some flibs are glibs. Which must be true?', 'Some glibs are not fribs.', 'All glibs are fribs.', 'Some glibs are fribs.', 'No glibs are fribs.', 'C'),
    (397, 'All gribs are plibs. No plibs are pribs. Which must be true?', 'No gribs are pribs.', 'Some pribs are gribs.', 'Some gribs are pribs.', 'All gribs are pribs.', 'A'),
    (398, 'Some skibs are slibs. All slibs are smibs. Which must be true?', 'Some skibs are smibs.', 'All skibs are smibs.', 'Some smibs are not skibs.', 'No skibs are smibs.', 'A'),
    (399, 'No snibs are spibs. Some spibs are stibs. Which must be true?', 'Some stibs are not snibs.', 'No stibs are snibs.', 'Some stibs are snibs.', 'All stibs are snibs.', 'A'),
    (400, 'All swibs are tribs. Some swibs are twibs. Which must be true?', 'Some twibs are tribs.', 'All twibs are tribs.', 'Some twibs are not tribs.', 'No twibs are tribs.', 'A'),
    (401, 'All blobs are brobs. No brobs are clobs. Which must be true?', 'No blobs are clobs.', 'Some clobs are blobs.', 'Some blobs are clobs.', 'All blobs are clobs.', 'A'),
    (402, 'Some crobs are drobs. All drobs are flobs. Which must be true?', 'No crobs are flobs.', 'Some flobs are not crobs.', 'All crobs are flobs.', 'Some crobs are flobs.', 'D'),
    (403, 'No frobs are globs. Some globs are grobs. Which must be true?', 'All grobs are frobs.', 'Some grobs are not frobs.', 'Some grobs are frobs.', 'No grobs are frobs.', 'B'),
    (404, 'All plobs are probs. Some plobs are skobs. Which must be true?', 'Some skobs are not probs.', 'All skobs are probs.', 'No skobs are probs.', 'Some skobs are probs.', 'D'),
    (405, 'All slobs are smobs. No smobs are snobs. Which must be true?', 'All slobs are snobs.', 'Some snobs are slobs.', 'Some slobs are snobs.', 'No slobs are snobs.', 'D'),
    (406, 'Some spobs are stobs. All stobs are swobs. Which must be true?', 'No spobs are swobs.', 'Some spobs are swobs.', 'All spobs are swobs.', 'Some swobs are not spobs.', 'B'),
    (407, 'No trobs are twobs. Some twobs are blubs. Which must be true?', 'Some blubs are not trobs.', 'Some blubs are trobs.', 'No blubs are trobs.', 'All blubs are trobs.', 'A'),
    (408, 'All brubs are clubs. Some brubs are crubs. Which must be true?', 'Some crubs are not clubs.', 'No crubs are clubs.', 'All crubs are clubs.', 'Some crubs are clubs.', 'D'),
    (409, 'All drubs are flubs. No flubs are frubs. Which must be true?', 'Some drubs are frubs.', 'All drubs are frubs.', 'No drubs are frubs.', 'Some frubs are drubs.', 'C'),
    (410, 'Some glubs are grubs. All grubs are plubs. Which must be true?', 'All glubs are plubs.', 'Some plubs are not glubs.', 'Some glubs are plubs.', 'No glubs are plubs.', 'C'),
    (411, 'No prubs are skubs. Some skubs are slubs. Which must be true?', 'Some slubs are prubs.', 'Some slubs are not prubs.', 'All slubs are prubs.', 'No slubs are prubs.', 'B'),
    (412, 'All smubs are snubs. Some smubs are spubs. Which must be true?', 'No spubs are snubs.', 'Some spubs are snubs.', 'All spubs are snubs.', 'Some spubs are not snubs.', 'B'),
    (413, 'All stubs are swubs. No swubs are trubs. Which must be true?', 'No stubs are trubs.', 'Some trubs are stubs.', 'All stubs are trubs.', 'Some stubs are trubs.', 'A'),
    (414, 'Some twubs are blads. All blads are brads. Which must be true?', 'All twubs are brads.', 'Some twubs are brads.', 'No twubs are brads.', 'Some brads are not twubs.', 'B'),
    (415, 'No clads are crads. Some crads are drads. Which must be true?', 'No drads are clads.', 'Some drads are not clads.', 'Some drads are clads.', 'All drads are clads.', 'B'),
    (416, 'All flads are frads. Some flads are glads. Which must be true?', 'No glads are frads.', 'All glads are frads.', 'Some glads are frads.', 'Some glads are not frads.', 'C'),
    (417, 'All grads are plads. No plads are prads. Which must be true?', 'Some prads are grads.', 'No grads are prads.', 'All grads are prads.', 'Some grads are prads.', 'B'),
    (418, 'Some skads are slads. All slads are smads. Which must be true?', 'No skads are smads.', 'Some skads are smads.', 'Some smads are not skads.', 'All skads are smads.', 'B'),
    (419, 'No snads are spads. Some spads are stads. Which must be true?', 'Some stads are not snads.', 'No stads are snads.', 'Some stads are snads.', 'All stads are snads.', 'A'),
    (420, 'All swads are trads. Some swads are twads. Which must be true?', 'Some twads are trads.', 'Some twads are not trads.', 'No twads are trads.', 'All twads are trads.', 'A'),
    (421, 'All bleds are breds. No breds are cleds. Which must be true?', 'Some bleds are cleds.', 'No bleds are cleds.', 'All bleds are cleds.', 'Some cleds are bleds.', 'B'),
    (422, 'Some creds are dreds. All dreds are fleds. Which must be true?', 'Some creds are fleds.', 'All creds are fleds.', 'No creds are fleds.', 'Some fleds are not creds.', 'A'),
    (423, 'No freds are gleds. Some gleds are greds. Which must be true?', 'All greds are freds.', 'No greds are freds.', 'Some greds are freds.', 'Some greds are not freds.', 'D'),
    (424, 'All pleds are preds. Some pleds are skeds. Which must be true?', 'No skeds are preds.', 'All skeds are preds.', 'Some skeds are not preds.', 'Some skeds are preds.', 'D'),
    (425, 'All sleds are smeds. No smeds are sneds. Which must be true?', 'No sleds are sneds.', 'Some sleds are sneds.', 'Some sneds are sleds.', 'All sleds are sneds.', 'A'),
    (426, 'Some speds are steds. All steds are sweds. Which must be true?', 'Some sweds are not speds.', 'No speds are sweds.', 'Some speds are sweds.', 'All speds are sweds.', 'C'),
    (427, 'No treds are tweds. Some tweds are blids. Which must be true?', 'All blids are treds.', 'No blids are treds.', 'Some blids are treds.', 'Some blids are not treds.', 'D'),
    (428, 'All brids are clids. Some brids are crids. Which must be true?', 'Some crids are clids.', 'All crids are clids.', 'Some crids are not clids.', 'No crids are clids.', 'A'),
    (429, 'All drids are flids. No flids are frids. Which must be true?', 'All drids are frids.', 'Some frids are drids.', 'Some drids are frids.', 'No drids are frids.', 'D'),
    (430, 'Some glids are grids. All grids are plids. Which must be true?', 'Some glids are plids.', 'Some plids are not glids.', 'No glids are plids.', 'All glids are plids.', 'A'),
    (431, 'No prids are skids. Some skids are slids. Which must be true?', 'No slids are prids.', 'Some slids are not prids.', 'All slids are prids.', 'Some slids are prids.', 'B'),
    (432, 'All smids are snids. Some smids are spids. Which must be true?', 'All spids are snids.', 'No spids are snids.', 'Some spids are not snids.', 'Some spids are snids.', 'D'),
    (433, 'All stids are swids. No swids are trids. Which must be true?', 'All stids are trids.', 'No stids are trids.', 'Some trids are stids.', 'Some stids are trids.', 'B'),
    (434, 'Some twids are blods. All blods are brods. Which must be true?', 'All twids are brods.', 'Some twids are brods.', 'No twids are brods.', 'Some brods are not twids.', 'B'),
    (435, 'No clods are crods. Some crods are drods. Which must be true?', 'Some drods are clods.', 'All drods are clods.', 'Some drods are not clods.', 'No drods are clods.', 'C'),
    (436, 'All flods are frods. Some flods are glods. Which must be true?', 'Some glods are not frods.', 'Some glods are frods.', 'No glods are frods.', 'All glods are frods.', 'B'),
    (437, 'All grods are plods. No plods are prods. Which must be true?', 'Some prods are grods.', 'All grods are prods.', 'No grods are prods.', 'Some grods are prods.', 'C'),
    (438, 'Some skods are slods. All slods are smods. Which must be true?', 'All skods are smods.', 'No skods are smods.', 'Some skods are smods.', 'Some smods are not skods.', 'C'),
    (439, 'No snods are spods. Some spods are stods. Which must be true?', 'No stods are snods.', 'All stods are snods.', 'Some stods are snods.', 'Some stods are not snods.', 'D'),
    (440, 'All swods are trods. Some swods are twods. Which must be true?', 'Some twods are trods.', 'Some twods are not trods.', 'No twods are trods.', 'All twods are trods.', 'A'),
    (441, 'All bluds are bruds. No bruds are cluds. Which must be true?', 'No bluds are cluds.', 'All bluds are cluds.', 'Some bluds are cluds.', 'Some cluds are bluds.', 'A'),
    (442, 'Some cruds are druds. All druds are fluds. Which must be true?', 'No cruds are fluds.', 'Some fluds are not cruds.', 'All cruds are fluds.', 'Some cruds are fluds.', 'D'),
    (443, 'No fruds are gluds. Some gluds are gruds. Which must be true?', 'Some gruds are not fruds.', 'No gruds are fruds.', 'All gruds are fruds.', 'Some gruds are fruds.', 'A'),
    (444, 'All pluds are pruds. Some pluds are skuds. Which must be true?', 'Some skuds are not pruds.', 'Some skuds are pruds.', 'No skuds are pruds.', 'All skuds are pruds.', 'B'),
    (445, 'All sluds are smuds. No smuds are snuds. Which must be true?', 'Some snuds are sluds.', 'Some sluds are snuds.', 'All sluds are snuds.', 'No sluds are snuds.', 'D'),
    (446, 'Some spuds are studs. All studs are swuds. Which must be true?', 'Some spuds are swuds.', 'All spuds are swuds.', 'No spuds are swuds.', 'Some swuds are not spuds.', 'A'),
    (447, 'No truds are twuds. Some twuds are blags. Which must be true?', 'Some blags are not truds.', 'No blags are truds.', 'All blags are truds.', 'Some blags are truds.', 'A'),
    (448, 'All brags are clags. Some brags are crags. Which must be true?', 'No crags are clags.', 'Some crags are clags.', 'All crags are clags.', 'Some crags are not clags.', 'B'),
    (449, 'All drags are flags. No flags are frags. Which must be true?', 'Some drags are frags.', 'All drags are frags.', 'Some frags are drags.', 'No drags are frags.', 'D'),
    (450, 'Some glags are grags. All grags are plags. Which must be true?', 'No glags are plags.', 'Some glags are plags.', 'All glags are plags.', 'Some plags are not glags.', 'B'),
    (451, 'No prags are skags. Some skags are slags. Which must be true?', 'All slags are prags.', 'Some slags are prags.', 'No slags are prags.', 'Some slags are not prags.', 'D'),
    (452, 'All smags are snags. Some smags are spags. Which must be true?', 'Some spags are snags.', 'Some spags are not snags.', 'All spags are snags.', 'No spags are snags.', 'A'),
    (453, 'All stags are swags. No swags are trags. Which must be true?', 'Some trags are stags.', 'Some stags are trags.', 'No stags are trags.', 'All stags are trags.', 'C'),
    (454, 'Some twags are blegs. All blegs are bregs. Which must be true?', 'No twags are bregs.', 'All twags are bregs.', 'Some bregs are not twags.', 'Some twags are bregs.', 'D'),
    (455, 'No clegs are cregs. Some cregs are dregs. Which must be true?', 'No dregs are clegs.', 'Some dregs are clegs.', 'All dregs are clegs.', 'Some dregs are not clegs.', 'D'),
    (456, 'All flegs are fregs. Some flegs are glegs. Which must be true?', 'All glegs are fregs.', 'Some glegs are fregs.', 'Some glegs are not fregs.', 'No glegs are fregs.', 'B'),
    (457, 'All gregs are plegs. No plegs are pregs. Which must be true?', 'Some gregs are pregs.', 'No gregs are pregs.', 'Some pregs are gregs.', 'All gregs are pregs.', 'B'),
    (458, 'Some skegs are slegs. All slegs are smegs. Which must be true?', 'Some skegs are smegs.', 'All skegs are smegs.', 'Some smegs are not skegs.', 'No skegs are smegs.', 'A'),
    (459, 'No snegs are spegs. Some spegs are stegs. Which must be true?', 'All stegs are snegs.', 'Some stegs are snegs.', 'Some stegs are not snegs.', 'No stegs are snegs.', 'C'),
    (460, 'All swegs are tregs. Some swegs are twegs. Which must be true?', 'No twegs are tregs.', 'Some twegs are tregs.', 'Some twegs are not tregs.', 'All twegs are tregs.', 'B'),
    (461, 'The more you take away from me, the bigger I become. What am I?', 'mountain', 'chair', 'guitar', 'hole', 'D'),
    (462, 'What gets larger when you remove material from it?', 'engine', 'hole', 'turtle', 'radio', 'B'),
    (463, 'What is always running out but can never be caught?', 'flower', 'guitar', 'cloud', 'time', 'D'),
    (464, 'What disappears the moment you try to save it?', 'time', 'ladder', 'knife', 'orange', 'A'),
    (465, 'What is full of holes and still holds water?', 'sponge', 'bucket', 'table', 'lamp', 'A'),
    (466, 'What soaks up liquid while staying full of gaps?', 'sponge', 'carpet', 'nugget', 'yarn', 'A'),
    (467, 'What has hands but cannot clap?', 'ladder', 'rocket', 'mountain', 'clock', 'D'),
    (468, 'What ticks away but never takes a step?', 'utensil', 'clock', 'ink', 'pebble', 'B'),
    (469, 'What has keys but cannot open a door?', 'piano', 'sword', 'forest', 'basket', 'A'),
    (470, 'What can be played but never eaten?', 'piano', 'wallet', 'kite', 'apple', 'A'),
    (471, 'What can unlock a door but cannot enter it?', 'yacht', 'bottle', 'dollar', 'key', 'D'),
    (472, 'What small object fits a lock but has no legs?', 'key', 'ticket', 'glove', 'engine', 'A'),
    (473, 'What can show you the world while staying flat?', 'nugget', 'map', 'yarn', 'ladder', 'B'),
    (474, 'What fits in your hand and can still guide a journey?', 'kite', 'wallet', 'apple', 'map', 'D'),
    (475, 'What repeats your voice without learning your words?', 'door', 'island', 'echo', 'pebble', 'C'),
    (476, 'What answers when you shout but has no mouth?', 'nugget', 'feather', 'echo', 'kettle', 'C'),
    (477, 'What follows you all day in the light?', 'apple', 'harp', 'shadow', 'basket', 'C'),
    (478, 'What disappears when the lights go out?', 'vase', 'shadow', 'apple', 'needle', 'B'),
    (479, 'What do you lose every time you speak?', 'breath', 'basket', 'lemon', 'quilt', 'A'),
    (480, 'What can you see on a cold morning but cannot hold?', 'breath', 'cloud', 'marble', 'orange', 'A'),
    (481, 'What has pages but no pulse?', 'yarn', 'book', 'lizard', 'wheel', 'B'),
    (482, 'What can tell a story without speaking?', 'nugget', 'feather', 'book', 'orange', 'C'),
    (483, 'What runs but never walks?', 'bottle', 'river', 'lemon', 'bucket', 'B'),
    (484, 'What gets deeper as it moves on?', 'knife', 'table', 'river', 'crown', 'C'),
    (485, 'What can travel the world while staying in one corner?', 'helmet', 'planet', 'stamp', 'apple', 'C'),
    (486, 'What tiny thing sticks to send a letter?', 'jigsaw', 'wand', 'ink', 'stamp', 'D'),
    (487, 'What gives light and grows shorter while working?', 'bridge', 'door', 'candle', 'lemon', 'C'),
    (488, 'What melts as it helps you see?', 'bottle', 'chair', 'radio', 'candle', 'D'),
    (489, 'What opens above you when the sky turns wet?', 'jigsaw', 'bucket', 'carpet', 'umbrella', 'D'),
    (490, 'What keeps rain off your head without being a roof?', 'apple', 'needle', 'umbrella', 'glove', 'C'),
    (491, 'What makes you cry and has layers?', 'onion', 'forest', 'sword', 'yacht', 'A'),
    (492, 'What vegetable has rings inside?', 'guitar', 'onion', 'mountain', 'rocket', 'B'),
    (493, 'What has a shell but is not a beach shell?', 'marble', 'egg', 'ladder', 'cactus', 'B'),
    (494, 'What cracks before breakfast?', 'egg', 'dollar', 'table', 'helmet', 'A'),
    (495, 'What shows your face without speaking?', 'marble', 'carpet', 'apple', 'mirror', 'D'),
    (496, 'What can copy you instantly?', 'mirror', 'bottle', 'apple', 'vase', 'A'),
    (497, 'What falls white and disappears in warmth?', 'pillow', 'snow', 'vase', 'island', 'B'),
    (498, 'What is soft until the sun meets it?', 'snow', 'apple', 'bucket', 'pillow', 'A'),
    (499, 'What grows when fed and shrinks when denied oxygen?', 'wheel', 'jacket', 'bottle', 'fire', 'D'),
    (500, 'What gives heat and light but can spread fast?', 'apple', 'forest', 'fire', 'window', 'C');

INSERT INTO quiz_questions
    (owner_admin_id, question_text, option_a, option_b, option_c, option_d, correct_option, countdown_seconds, reveal_duration, active, created_at, updated_at)
SELECT
    @owner_admin_id,
    t.question_text,
    t.option_a,
    t.option_b,
    t.option_c,
    t.option_d,
    t.correct_option,
    @countdown_seconds,
    @reveal_duration,
    1,
    @created_at,
    @created_at
FROM tmp_lateral_reasoning_questions_500 t
WHERE NOT EXISTS (
    SELECT 1
    FROM quiz_questions q
    WHERE q.owner_admin_id = @owner_admin_id
      AND q.question_text = t.question_text
);

DROP TEMPORARY TABLE tmp_lateral_reasoning_questions_500;

COMMIT;
