USE cloud_signage_present;

START TRANSACTION;

SET @owner_admin_id := 1;
SET @countdown_seconds := 12;
SET @reveal_duration := 6;
SET @created_at := UTC_TIMESTAMP();

CREATE TEMPORARY TABLE tmp_logic_riddle_reasoning_questions_500 (
    sort_order INT UNSIGNED NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option ENUM('A', 'B', 'C', 'D') NOT NULL
);

INSERT INTO tmp_logic_riddle_reasoning_questions_500
    (sort_order, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
    (1, 'What number comes next in the sequence: 3, 5, 7, 9, 11, ?', '11', '13', '15', '14', 'B'),
    (2, 'What number comes next in the sequence: 4, 12, 36, 108, 324, ?', '975', '969', '973', '972', 'D'),
    (3, 'What number comes next in the sequence: -37, -34, -29, -22, -13, ?', '-1', '-3', '2', '-2', 'D'),
    (4, 'What number comes next in the sequence: -26, -24, -21, -17, -12, ?', '-5', '-3', '-6', '-7', 'C'),
    (5, 'What number comes next in the sequence: 7, 9, 16, 18, 25, 27, ?', '34', '36', '27', '36', 'A'),
    (6, 'What number comes next in the sequence: 6, 7, 13, 20, 33, 53, ?', '139', '86', '53', '88', 'B'),
    (7, 'What number comes next in the sequence: 9, 10, 13, 13, 17, 16, ?', '20', '23', '16', '19', 'D'),
    (8, 'What number comes next in the sequence: 10, 22, 46, 94, 190, 382, ?', '766', '768', '383', '764', 'A'),
    (9, 'What number comes next in the sequence: 11, 13, 16, 20, 25, 31, ?', '39', '38', '45', '37', 'B'),
    (10, 'What number comes next in the sequence: 12, 34, 100, 298, 892, 2674, ?', '8023', '8020', '8022', '8018', 'B'),
    (11, 'What number comes next in the sequence: 13, 15, 17, 19, 21, ?', '23', '21', '25', '24', 'A'),
    (12, 'What number comes next in the sequence: 14, 42, 126, 378, 1134, ?', '3399', '3405', '3403', '3402', 'D'),
    (13, 'What number comes next in the sequence: -27, -24, -19, -12, -3, ?', '12', '9', '7', '8', 'D'),
    (14, 'What number comes next in the sequence: -16, -14, -11, -7, -2, ?', '4', '3', '7', '5', 'A'),
    (15, 'What number comes next in the sequence: 17, 21, 28, 32, 39, 43, ?', '50', '54', '52', '43', 'A'),
    (16, 'What number comes next in the sequence: 16, 17, 33, 50, 83, 133, ?', '133', '349', '218', '216', 'D'),
    (17, 'What number comes next in the sequence: 19, 20, 21, 24, 23, 28, ?', '32', '34', '33', '28', 'A'),
    (18, 'What number comes next in the sequence: 20, 46, 98, 202, 410, 826, ?', '829', '1664', '1652', '1658', 'D'),
    (19, 'What number comes next in the sequence: 21, 25, 30, 36, 43, 51, ?', '60', '69', '61', '59', 'A'),
    (20, 'What number comes next in the sequence: 22, 62, 182, 542, 1622, 4862, ?', '14578', '14585', '14582', '14586', 'C'),
    (21, 'What number comes next in the sequence: 23, 25, 27, 29, 31, ?', '31', '34', '35', '33', 'D'),
    (22, 'What number comes next in the sequence: 24, 72, 216, 648, 1944, ?', '5832', '5835', '5833', '5829', 'A'),
    (23, 'What number comes next in the sequence: -17, -14, -9, -2, 7, ?', '17', '18', '22', '19', 'B'),
    (24, 'What number comes next in the sequence: -6, -4, -1, 3, 8, ?', '14', '13', '17', '15', 'A'),
    (25, 'What number comes next in the sequence: 27, 29, 36, 38, 45, 47, ?', '47', '56', '56', '54', 'D'),
    (26, 'What number comes next in the sequence: 26, 27, 53, 80, 133, 213, ?', '559', '213', '346', '348', 'C'),
    (27, 'What number comes next in the sequence: 29, 30, 33, 35, 37, 40, ?', '46', '49', '45', '40', 'C'),
    (28, 'What number comes next in the sequence: 30, 64, 132, 268, 540, 1084, ?', '1086', '2172', '2168', '2176', 'B'),
    (29, 'What number comes next in the sequence: 31, 33, 36, 40, 45, 51, ?', '57', '59', '65', '58', 'D'),
    (30, 'What number comes next in the sequence: 32, 94, 280, 838, 2512, 7534, ?', '22603', '22598', '22602', '22600', 'D'),
    (31, 'What number comes next in the sequence: 33, 35, 37, 39, 41, ?', '44', '43', '41', '45', 'B'),
    (32, 'What number comes next in the sequence: 34, 102, 306, 918, 2754, ?', '8259', '8263', '8265', '8262', 'D'),
    (33, 'What number comes next in the sequence: -7, -4, 1, 8, 17, ?', '27', '28', '32', '29', 'B'),
    (34, 'What number comes next in the sequence: 4, 6, 9, 13, 18, ?', '23', '27', '24', '25', 'C'),
    (35, 'What number comes next in the sequence: 37, 41, 48, 52, 59, 63, ?', '70', '74', '63', '72', 'A'),
    (36, 'What number comes next in the sequence: 36, 37, 73, 110, 183, 293, ?', '476', '769', '478', '293', 'A'),
    (37, 'What number comes next in the sequence: 39, 40, 41, 43, 43, 46, ?', '50', '49', '51', '46', 'B'),
    (38, 'What number comes next in the sequence: 40, 82, 166, 334, 670, 1342, ?', '2688', '1343', '2686', '2684', 'C'),
    (39, 'What number comes next in the sequence: 41, 45, 50, 56, 63, 71, ?', '81', '89', '79', '80', 'D'),
    (40, 'What number comes next in the sequence: 42, 122, 362, 1082, 3242, 9722, ?', '29158', '29166', '29165', '29162', 'D'),
    (41, 'What number comes next in the sequence: 43, 45, 47, 49, 51, ?', '55', '54', '53', '51', 'C'),
    (42, 'What number comes next in the sequence: 44, 132, 396, 1188, 3564, ?', '10689', '10692', '10695', '10693', 'B'),
    (43, 'What number comes next in the sequence: 3, 6, 11, 18, 27, ?', '38', '37', '42', '39', 'A'),
    (44, 'What number comes next in the sequence: 14, 16, 19, 23, 28, ?', '33', '37', '35', '34', 'D'),
    (45, 'What number comes next in the sequence: 47, 49, 56, 58, 65, 67, ?', '67', '74', '76', '76', 'B'),
    (46, 'What number comes next in the sequence: 46, 47, 93, 140, 233, 373, ?', '979', '373', '608', '606', 'D'),
    (47, 'What number comes next in the sequence: 49, 50, 53, 54, 57, 58, ?', '62', '66', '58', '63', 'A'),
    (48, 'What number comes next in the sequence: 50, 106, 218, 442, 890, 1786, ?', '3572', '3578', '3584', '1789', 'B'),
    (49, 'What number comes next in the sequence: 51, 53, 56, 60, 65, 71, ?', '78', '85', '77', '79', 'A'),
    (50, 'What number comes next in the sequence: 52, 154, 460, 1378, 4132, 12394, ?', '37180', '37178', '37182', '37183', 'A'),
    (51, 'What number comes next in the sequence: 53, 55, 57, 59, 61, ?', '64', '65', '61', '63', 'D'),
    (52, 'What number comes next in the sequence: 54, 162, 486, 1458, 4374, ?', '13122', '13123', '13125', '13119', 'A'),
    (53, 'What number comes next in the sequence: 13, 16, 21, 28, 37, ?', '48', '49', '47', '52', 'A'),
    (54, 'What number comes next in the sequence: 24, 26, 29, 33, 38, ?', '44', '43', '45', '47', 'A'),
    (55, 'What number comes next in the sequence: 57, 61, 68, 72, 79, 83, ?', '90', '83', '92', '94', 'A'),
    (56, 'What number comes next in the sequence: 56, 57, 113, 170, 283, 453, ?', '736', '1189', '453', '738', 'A'),
    (57, 'What number comes next in the sequence: 59, 60, 61, 65, 63, 70, ?', '70', '75', '77', '76', 'B'),
    (58, 'What number comes next in the sequence: 60, 124, 252, 508, 1020, 2044, ?', '4096', '2046', '4092', '4088', 'C'),
    (59, 'What number comes next in the sequence: 61, 65, 70, 76, 83, 91, ?', '100', '99', '101', '109', 'A'),
    (60, 'What number comes next in the sequence: 62, 182, 542, 1622, 4862, 14582, ?', '43746', '43745', '43738', '43742', 'D'),
    (61, 'What number comes next in the sequence: 63, 65, 67, 69, 71, ?', '75', '74', '71', '73', 'D'),
    (62, 'What number comes next in the sequence: 64, 192, 576, 1728, 5184, ?', '15555', '15552', '15553', '15549', 'B'),
    (63, 'What number comes next in the sequence: 23, 26, 31, 38, 47, ?', '59', '58', '57', '62', 'B'),
    (64, 'What number comes next in the sequence: 34, 36, 39, 43, 48, ?', '54', '57', '53', '55', 'A'),
    (65, 'What number comes next in the sequence: 67, 69, 76, 78, 85, 87, ?', '94', '96', '87', '96', 'A'),
    (66, 'What number comes next in the sequence: 66, 67, 133, 200, 333, 533, ?', '1399', '868', '533', '866', 'D'),
    (67, 'What number comes next in the sequence: 69, 70, 73, 73, 77, 76, ?', '79', '76', '80', '83', 'A'),
    (68, 'What number comes next in the sequence: 70, 142, 286, 574, 1150, 2302, ?', '4606', '4608', '4604', '2303', 'A'),
    (69, 'What number comes next in the sequence: 71, 73, 76, 80, 85, 91, ?', '97', '105', '98', '99', 'C'),
    (70, 'What number comes next in the sequence: 72, 214, 640, 1918, 5752, 17254, ?', '51758', '51763', '51762', '51760', 'D'),
    (71, 'What number comes next in the sequence: 73, 75, 77, 79, 81, ?', '85', '83', '81', '84', 'B'),
    (72, 'What number comes next in the sequence: 74, 222, 666, 1998, 5994, ?', '17982', '17979', '17983', '17985', 'A'),
    (73, 'What number comes next in the sequence: 33, 36, 41, 48, 57, ?', '72', '67', '69', '68', 'D'),
    (74, 'What number comes next in the sequence: 44, 46, 49, 53, 58, ?', '65', '63', '67', '64', 'D'),
    (75, 'What number comes next in the sequence: 77, 81, 88, 92, 99, 103, ?', '114', '110', '103', '112', 'B'),
    (76, 'What number comes next in the sequence: 76, 77, 153, 230, 383, 613, ?', '613', '998', '996', '1609', 'C'),
    (77, 'What number comes next in the sequence: 79, 80, 81, 84, 83, 88, ?', '92', '93', '88', '94', 'A'),
    (78, 'What number comes next in the sequence: 80, 166, 338, 682, 1370, 2746, ?', '2749', '5492', '5498', '5504', 'C'),
    (79, 'What number comes next in the sequence: 81, 85, 90, 96, 103, 111, ?', '120', '129', '119', '121', 'A'),
    (80, 'What number comes next in the sequence: 82, 242, 722, 2162, 6482, 19442, ?', '58318', '58325', '58326', '58322', 'D'),
    (81, 'What number comes next in the sequence: 83, 85, 87, 89, 91, ?', '91', '94', '93', '95', 'C'),
    (82, 'What number comes next in the sequence: 84, 252, 756, 2268, 6804, ?', '20409', '20413', '20412', '20415', 'C'),
    (83, 'What number comes next in the sequence: 43, 46, 51, 58, 67, ?', '79', '78', '77', '82', 'B'),
    (84, 'What number comes next in the sequence: 54, 56, 59, 63, 68, ?', '74', '75', '77', '73', 'A'),
    (85, 'What number comes next in the sequence: 87, 89, 96, 98, 105, 107, ?', '116', '116', '114', '107', 'C'),
    (86, 'What number comes next in the sequence: 86, 87, 173, 260, 433, 693, ?', '1819', '1126', '693', '1128', 'B'),
    (87, 'What number comes next in the sequence: 89, 90, 93, 95, 97, 100, ?', '105', '109', '100', '106', 'A'),
    (88, 'What number comes next in the sequence: 90, 184, 372, 748, 1500, 3004, ?', '3006', '6008', '6016', '6012', 'D'),
    (89, 'What number comes next in the sequence: 91, 93, 96, 100, 105, 111, ?', '125', '117', '119', '118', 'D'),
    (90, 'What number comes next in the sequence: 92, 274, 820, 2458, 7372, 22114, ?', '66340', '66338', '66342', '66343', 'A'),
    (91, 'What number comes next in the sequence: 93, 95, 97, 99, 101, ?', '101', '105', '103', '104', 'C'),
    (92, 'What number comes next in the sequence: 94, 282, 846, 2538, 7614, ?', '22839', '22845', '22843', '22842', 'D'),
    (93, 'What number comes next in the sequence: 53, 56, 61, 68, 77, ?', '89', '88', '87', '92', 'B'),
    (94, 'What number comes next in the sequence: 64, 66, 69, 73, 78, ?', '83', '84', '85', '87', 'B'),
    (95, 'What number comes next in the sequence: 97, 101, 108, 112, 119, 123, ?', '130', '132', '134', '123', 'A'),
    (96, 'What number comes next in the sequence: 96, 97, 193, 290, 483, 773, ?', '2029', '1258', '1256', '773', 'C'),
    (97, 'What number comes next in the sequence: 99, 100, 101, 103, 103, 106, ?', '110', '109', '106', '111', 'B'),
    (98, 'What number comes next in the sequence: 100, 202, 406, 814, 1630, 3262, ?', '6526', '6524', '6528', '3263', 'A'),
    (99, 'What number comes next in the sequence: 101, 105, 110, 116, 123, 131, ?', '141', '149', '139', '140', 'D'),
    (100, 'What number comes next in the sequence: 102, 302, 902, 2702, 8102, 24302, ?', '72906', '72898', '72902', '72905', 'C'),
    (101, 'If today is Monday, what day will it be in 8 days?', 'Tuesday', 'Wednesday', 'Sunday', 'Thursday', 'A'),
    (102, 'If today is Thursday, what day was it 9 days ago?', 'Thursday', 'Sunday', 'Tuesday', 'Friday', 'C'),
    (103, 'If today is Sunday, what day will it be in 10 days?', 'Monday', 'Sunday', 'Thursday', 'Wednesday', 'D'),
    (104, 'If today is Wednesday, what day was it 11 days ago?', 'Sunday', 'Saturday', 'Tuesday', 'Thursday', 'B'),
    (105, 'If today is Saturday, what day will it be in 12 days?', 'Saturday', 'Thursday', 'Monday', 'Friday', 'B'),
    (106, 'If today is Tuesday, what day was it 13 days ago?', 'Wednesday', 'Tuesday', 'Sunday', 'Friday', 'A'),
    (107, 'If today is Friday, what day will it be in 14 days?', 'Saturday', 'Tuesday', 'Sunday', 'Friday', 'D'),
    (108, 'If today is Monday, what day was it 15 days ago?', 'Tuesday', 'Sunday', 'Saturday', 'Friday', 'B'),
    (109, 'If today is Thursday, what day will it be in 16 days?', 'Tuesday', 'Thursday', 'Sunday', 'Saturday', 'D'),
    (110, 'If today is Sunday, what day was it 17 days ago?', 'Sunday', 'Tuesday', 'Thursday', 'Friday', 'C'),
    (111, 'If today is Wednesday, what day will it be in 18 days?', 'Sunday', 'Thursday', 'Wednesday', 'Friday', 'A'),
    (112, 'If today is Saturday, what day was it 19 days ago?', 'Friday', 'Tuesday', 'Thursday', 'Monday', 'D'),
    (113, 'If today is Tuesday, what day will it be in 20 days?', 'Friday', 'Tuesday', 'Monday', 'Wednesday', 'C'),
    (114, 'If today is Friday, what day was it 21 days ago?', 'Friday', 'Sunday', 'Saturday', 'Tuesday', 'A'),
    (115, 'If today is Monday, what day will it be in 22 days?', 'Thursday', 'Monday', 'Wednesday', 'Tuesday', 'D'),
    (116, 'If today is Thursday, what day was it 23 days ago?', 'Tuesday', 'Friday', 'Sunday', 'Monday', 'A'),
    (117, 'If today is Sunday, what day will it be in 24 days?', 'Wednesday', 'Sunday', 'Monday', 'Saturday', 'A'),
    (118, 'If today is Wednesday, what day was it 25 days ago?', 'Friday', 'Monday', 'Saturday', 'Sunday', 'C'),
    (119, 'If today is Saturday, what day will it be in 26 days?', 'Saturday', 'Thursday', 'Monday', 'Friday', 'B'),
    (120, 'If today is Tuesday, what day was it 27 days ago?', 'Sunday', 'Tuesday', 'Wednesday', 'Thursday', 'C'),
    (121, 'If today is Friday, what day will it be in 28 days?', 'Thursday', 'Friday', 'Sunday', 'Saturday', 'B'),
    (122, 'If today is Monday, what day was it 29 days ago?', 'Thursday', 'Friday', 'Monday', 'Sunday', 'D'),
    (123, 'If today is Thursday, what day will it be in 30 days?', 'Sunday', 'Saturday', 'Tuesday', 'Wednesday', 'B'),
    (124, 'If today is Sunday, what day was it 31 days ago?', 'Friday', 'Saturday', 'Tuesday', 'Thursday', 'D'),
    (125, 'If today is Wednesday, what day will it be in 32 days?', 'Saturday', 'Sunday', 'Tuesday', 'Wednesday', 'B'),
    (126, 'If today is Saturday, what day was it 33 days ago?', 'Sunday', 'Monday', 'Saturday', 'Tuesday', 'B'),
    (127, 'If today is Tuesday, what day will it be in 34 days?', 'Sunday', 'Friday', 'Monday', 'Thursday', 'C'),
    (128, 'If today is Friday, what day was it 35 days ago?', 'Friday', 'Monday', 'Tuesday', 'Saturday', 'A'),
    (129, 'If today is Monday, what day will it be in 36 days?', 'Wednesday', 'Saturday', 'Friday', 'Tuesday', 'D'),
    (130, 'If today is Thursday, what day was it 37 days ago?', 'Monday', 'Thursday', 'Tuesday', 'Sunday', 'C'),
    (131, 'If today is Sunday, what day will it be in 38 days?', 'Monday', 'Saturday', 'Tuesday', 'Wednesday', 'D'),
    (132, 'If today is Wednesday, what day was it 39 days ago?', 'Wednesday', 'Saturday', 'Thursday', 'Tuesday', 'B'),
    (133, 'If today is Saturday, what day will it be in 40 days?', 'Wednesday', 'Tuesday', 'Thursday', 'Monday', 'C'),
    (134, 'If today is Tuesday, what day was it 41 days ago?', 'Friday', 'Wednesday', 'Thursday', 'Monday', 'B'),
    (135, 'If today is Friday, what day will it be in 42 days?', 'Tuesday', 'Sunday', 'Thursday', 'Friday', 'D'),
    (136, 'If today is Monday, what day was it 43 days ago?', 'Friday', 'Sunday', 'Wednesday', 'Tuesday', 'B'),
    (137, 'If today is Thursday, what day will it be in 44 days?', 'Tuesday', 'Monday', 'Wednesday', 'Saturday', 'D'),
    (138, 'If today is Sunday, what day was it 45 days ago?', 'Thursday', 'Tuesday', 'Monday', 'Sunday', 'A'),
    (139, 'If today is Wednesday, what day will it be in 46 days?', 'Thursday', 'Sunday', 'Saturday', 'Monday', 'B'),
    (140, 'If today is Saturday, what day was it 47 days ago?', 'Sunday', 'Wednesday', 'Tuesday', 'Monday', 'D'),
    (141, 'If today is Tuesday, what day will it be in 48 days?', 'Saturday', 'Sunday', 'Monday', 'Friday', 'C'),
    (142, 'If today is Friday, what day was it 49 days ago?', 'Monday', 'Friday', 'Wednesday', 'Thursday', 'B'),
    (143, 'If today is Monday, what day will it be in 50 days?', 'Tuesday', 'Monday', 'Friday', 'Wednesday', 'A'),
    (144, 'If today is Thursday, what day was it 51 days ago?', 'Sunday', 'Wednesday', 'Tuesday', 'Saturday', 'C'),
    (145, 'If today is Sunday, what day will it be in 52 days?', 'Thursday', 'Tuesday', 'Friday', 'Wednesday', 'D'),
    (146, 'If today is Wednesday, what day was it 53 days ago?', 'Saturday', 'Sunday', 'Friday', 'Tuesday', 'A'),
    (147, 'If today is Saturday, what day will it be in 54 days?', 'Wednesday', 'Saturday', 'Thursday', 'Friday', 'C'),
    (148, 'If today is Tuesday, what day was it 55 days ago?', 'Saturday', 'Wednesday', 'Thursday', 'Friday', 'B'),
    (149, 'If today is Friday, what day will it be in 56 days?', 'Saturday', 'Friday', 'Sunday', 'Monday', 'B'),
    (150, 'If today is Monday, what day was it 57 days ago?', 'Sunday', 'Tuesday', 'Wednesday', 'Saturday', 'A'),
    (151, 'What time is 1 hours and 10 minutes after 1:00 am?', '3:10 am', '2:25 am', '2:10 am', '1:55 am', 'C'),
    (152, 'A film starts at 6:07 pm and lasts 3 hours and 9 minutes. What time does it end?', '9:01 pm', '9:31 pm', '10:16 pm', '9:16 pm', 'D'),
    (153, 'What time is 3 hours and 20 minutes before 11:14 am?', '8:54 am', '7:39 am', '7:54 am', '8:09 am', 'C'),
    (154, 'What time is 4 hours and 19 minutes after 4:21 pm?', '9:40 pm', '8:40 pm', '8:55 pm', '8:25 pm', 'B'),
    (155, 'A film starts at 9:28 am and lasts 3 hours and 21 minutes. What time does it end?', '1:04 pm', '12:34 pm', '12:49 pm', '1:49 pm', 'C'),
    (156, 'What time is 3 hours and 35 minutes before 2:35 pm?', '11:15 am', '12:00 pm', '11:00 am', '10:45 am', 'C'),
    (157, 'What time is 3 hours and 28 minutes after 7:42 am?', '10:55 am', '11:25 am', '12:10 pm', '11:10 am', 'D'),
    (158, 'A film starts at 12:49 pm and lasts 3 hours and 33 minutes. What time does it end?', '4:22 pm', '4:07 pm', '4:37 pm', '5:22 pm', 'A'),
    (159, 'What time is 3 hours and 10 minutes before 5:56 am?', '3:46 am', '2:46 am', '2:31 am', '3:01 am', 'B'),
    (160, 'What time is 2 hours and 37 minutes after 10:03 pm?', '12:55 am', '12:40 am', '12:25 am', '1:40 am', 'B'),
    (161, 'A film starts at 3:10 am and lasts 3 hours and 45 minutes. What time does it end?', '7:10 am', '6:55 am', '6:40 am', '7:55 am', 'B'),
    (162, 'What time is 3 hours and 25 minutes before 8:17 pm?', '5:52 pm', '4:52 pm', '4:37 pm', '5:07 pm', 'B'),
    (163, 'What time is 1 hours and 46 minutes after 1:24 am?', '4:10 am', '2:55 am', '3:10 am', '3:25 am', 'C'),
    (164, 'A film starts at 6:31 pm and lasts 3 hours and 12 minutes. What time does it end?', '10:43 pm', '9:28 pm', '9:43 pm', '9:58 pm', 'C'),
    (165, 'What time is 3 hours and 40 minutes before 11:38 am?', '8:13 am', '7:43 am', '7:58 am', '8:58 am', 'C'),
    (166, 'What time is 4 hours and 55 minutes after 4:45 pm?', '9:25 pm', '9:55 pm', '9:40 pm', '10:40 pm', 'C'),
    (167, 'A film starts at 9:52 am and lasts 3 hours and 24 minutes. What time does it end?', '1:31 pm', '2:16 pm', '1:16 pm', '1:01 pm', 'C'),
    (168, 'What time is 3 hours and 15 minutes before 2:59 pm?', '11:59 am', '12:44 pm', '11:29 am', '11:44 am', 'D'),
    (169, 'What time is 3 hours and 14 minutes after 7:06 am?', '10:35 am', '10:05 am', '10:20 am', '11:20 am', 'C'),
    (170, 'A film starts at 12:13 pm and lasts 3 hours and 36 minutes. What time does it end?', '3:49 pm', '4:49 pm', '4:04 pm', '3:34 pm', 'A'),
    (171, 'What time is 3 hours and 30 minutes before 5:20 am?', '2:50 am', '1:50 am', '2:05 am', '1:35 am', 'B'),
    (172, 'What time is 2 hours and 23 minutes after 10:27 pm?', '1:50 am', '1:05 am', '12:50 am', '12:35 am', 'C'),
    (173, 'A film starts at 3:34 am and lasts 3 hours and 48 minutes. What time does it end?', '7:37 am', '8:22 am', '7:07 am', '7:22 am', 'D'),
    (174, 'What time is 3 hours and 45 minutes before 8:41 pm?', '4:56 pm', '5:56 pm', '4:41 pm', '5:11 pm', 'A'),
    (175, 'What time is 1 hours and 32 minutes after 1:48 am?', '3:20 am', '4:20 am', '3:35 am', '3:05 am', 'A'),
    (176, 'A film starts at 6:55 pm and lasts 3 hours and 15 minutes. What time does it end?', '9:55 pm', '10:25 pm', '10:10 pm', '11:10 pm', 'C'),
    (177, 'What time is 3 hours and 20 minutes before 11:02 am?', '8:42 am', '7:27 am', '7:57 am', '7:42 am', 'D'),
    (178, 'What time is 4 hours and 41 minutes after 4:09 pm?', '9:50 pm', '8:35 pm', '9:05 pm', '8:50 pm', 'D'),
    (179, 'A film starts at 9:16 am and lasts 3 hours and 27 minutes. What time does it end?', '12:43 pm', '12:58 pm', '12:28 pm', '1:43 pm', 'A'),
    (180, 'What time is 3 hours and 35 minutes before 2:23 pm?', '10:48 am', '11:03 am', '10:33 am', '11:48 am', 'A'),
    (181, 'What time is 3 hours and 50 minutes after 7:30 am?', '11:20 am', '11:05 am', '12:20 pm', '11:35 am', 'A'),
    (182, 'A film starts at 12:37 pm and lasts 3 hours and 39 minutes. What time does it end?', '4:31 pm', '4:16 pm', '4:01 pm', '5:16 pm', 'B'),
    (183, 'What time is 3 hours and 10 minutes before 5:44 am?', '2:34 am', '3:34 am', '2:19 am', '2:49 am', 'A'),
    (184, 'What time is 2 hours and 59 minutes after 10:51 pm?', '2:50 am', '1:35 am', '1:50 am', '2:05 am', 'C'),
    (185, 'A film starts at 3:58 am and lasts 3 hours and 6 minutes. What time does it end?', '7:04 am', '6:49 am', '7:19 am', '8:04 am', 'A'),
    (186, 'What time is 3 hours and 25 minutes before 8:05 pm?', '5:40 pm', '4:40 pm', '4:25 pm', '4:55 pm', 'B'),
    (187, 'What time is 1 hours and 18 minutes after 1:12 am?', '2:30 am', '2:45 am', '2:15 am', '3:30 am', 'A'),
    (188, 'A film starts at 6:19 pm and lasts 3 hours and 18 minutes. What time does it end?', '9:22 pm', '9:37 pm', '9:52 pm', '10:37 pm', 'B'),
    (189, 'What time is 3 hours and 40 minutes before 11:26 am?', '8:01 am', '8:46 am', '7:46 am', '7:31 am', 'C'),
    (190, 'What time is 4 hours and 27 minutes after 4:33 pm?', '8:45 pm', '10:00 pm', '9:15 pm', '9:00 pm', 'D'),
    (191, 'A film starts at 9:40 am and lasts 3 hours and 30 minutes. What time does it end?', '2:10 pm', '1:25 pm', '1:10 pm', '12:55 pm', 'C'),
    (192, 'What time is 3 hours and 15 minutes before 2:47 pm?', '11:17 am', '11:47 am', '12:32 pm', '11:32 am', 'D'),
    (193, 'What time is 3 hours and 36 minutes after 7:54 am?', '11:30 am', '11:15 am', '12:30 pm', '11:45 am', 'A'),
    (194, 'A film starts at 12:01 pm and lasts 3 hours and 42 minutes. What time does it end?', '4:43 pm', '3:43 pm', '3:58 pm', '3:28 pm', 'B'),
    (195, 'What time is 3 hours and 30 minutes before 5:08 am?', '2:38 am', '1:38 am', '1:53 am', '1:23 am', 'B'),
    (196, 'What time is 2 hours and 45 minutes after 10:15 pm?', '2:00 am', '1:15 am', '12:45 am', '1:00 am', 'D'),
    (197, 'A film starts at 3:22 am and lasts 3 hours and 9 minutes. What time does it end?', '6:16 am', '6:31 am', '6:46 am', '7:31 am', 'B'),
    (198, 'What time is 3 hours and 45 minutes before 8:29 pm?', '5:44 pm', '4:44 pm', '4:59 pm', '4:29 pm', 'B'),
    (199, 'What time is 1 hours and 54 minutes after 1:36 am?', '4:30 am', '3:45 am', '3:30 am', '3:15 am', 'C'),
    (200, 'A film starts at 6:43 pm and lasts 3 hours and 21 minutes. What time does it end?', '11:04 pm', '10:19 pm', '9:49 pm', '10:04 pm', 'D'),
    (201, 'Which of these words has the most letters: insect, kernel, desert, camera?', 'kernel', 'desert', 'insect', 'camera', 'C'),
    (202, 'Which of these words has the fewest letters: insect, zebra, nectar, camera?', 'camera', 'insect', 'zebra', 'nectar', 'C'),
    (203, 'Which word comes first alphabetically: journey, rocket, utopia, nectar?', 'journey', 'utopia', 'nectar', 'rocket', 'A'),
    (204, 'Which of these words has the most vowels: xylophone, feather, zebra, meteor?', 'xylophone', 'feather', 'meteor', 'zebra', 'A'),
    (205, 'Which of these words has the most letters: zebra, utopia, xylophone, apricot?', 'zebra', 'xylophone', 'apricot', 'utopia', 'B'),
    (206, 'Which of these words has the fewest letters: saturn, yellow, jungle, utopia?', 'utopia', 'yellow', 'saturn', 'jungle', 'C'),
    (207, 'Which word comes first alphabetically: biscuit, falcon, jigsaw, kernel?', 'kernel', 'falcon', 'jigsaw', 'biscuit', 'D'),
    (208, 'Which of these words has the most vowels: eclipse, desert, cactus, zebra?', 'cactus', 'desert', 'zebra', 'eclipse', 'D'),
    (209, 'Which of these words has the most letters: kernel, falcon, tunnel, shadow?', 'shadow', 'falcon', 'kernel', 'tunnel', 'C'),
    (210, 'Which of these words has the fewest letters: anchor, meteor, velvet, engineer?', 'velvet', 'engineer', 'anchor', 'meteor', 'C'),
    (211, 'Which word comes first alphabetically: shelter, saturn, quiver, engine?', 'quiver', 'saturn', 'shelter', 'engine', 'D'),
    (212, 'Which of these words has the most vowels: eclipse, orchid, quartz, planet?', 'orchid', 'planet', 'quartz', 'eclipse', 'D'),
    (213, 'Which of these words has the most letters: zephyr, galaxy, balloon, engine?', 'balloon', 'zephyr', 'galaxy', 'engine', 'A'),
    (214, 'Which of these words has the fewest letters: quilt, insect, anchor, harvest?', 'harvest', 'insect', 'anchor', 'quilt', 'D'),
    (215, 'Which word comes first alphabetically: yellow, orange, bottle, candle?', 'candle', 'orange', 'bottle', 'yellow', 'C'),
    (216, 'Which of these words has the most vowels: ladder, tunnel, harvest, island?', 'tunnel', 'harvest', 'island', 'ladder', 'D'),
    (217, 'Which of these words has the most letters: window, planet, yonder, velvet?', 'velvet', 'planet', 'window', 'yonder', 'C'),
    (218, 'Which of these words has the fewest letters: valley, lantern, desert, kettle?', 'valley', 'desert', 'kettle', 'lantern', 'A'),
    (219, 'Which word comes first alphabetically: quilt, horizon, anchor, dragon?', 'anchor', 'quilt', 'horizon', 'dragon', 'A'),
    (220, 'Which of these words has the most vowels: quiver, valley, glacier, desert?', 'desert', 'quiver', 'valley', 'glacier', 'B'),
    (221, 'Which of these words has the most letters: falcon, iguana, planet, whisper?', 'whisper', 'iguana', 'falcon', 'planet', 'A'),
    (222, 'Which of these words has the fewest letters: whisper, orange, kettle, orchid?', 'orange', 'orchid', 'whisper', 'kettle', 'A'),
    (223, 'Which word comes first alphabetically: xylophone, rocket, lantern, falcon?', 'lantern', 'rocket', 'falcon', 'xylophone', 'C'),
    (224, 'Which of these words has the most vowels: cactus, kernel, ribbon, harvest?', 'ribbon', 'cactus', 'harvest', 'kernel', 'B'),
    (225, 'Which of these words has the most letters: kernel, utopia, orchard, marble?', 'marble', 'utopia', 'orchard', 'kernel', 'C'),
    (226, 'Which of these words has the fewest letters: glacier, engineer, meteor, candle?', 'glacier', 'engineer', 'meteor', 'candle', 'C'),
    (227, 'Which word comes first alphabetically: xylophone, harvest, magnet, glacier?', 'xylophone', 'magnet', 'harvest', 'glacier', 'D'),
    (228, 'Which of these words has the most vowels: quiver, kettle, insect, puzzle?', 'puzzle', 'quiver', 'insect', 'kettle', 'B'),
    (229, 'Which of these words has the most letters: nectar, kernel, laptop, saturn?', 'kernel', 'laptop', 'saturn', 'nectar', 'D'),
    (230, 'Which of these words has the fewest letters: engine, apricot, xylophone, iguana?', 'iguana', 'apricot', 'xylophone', 'engine', 'D'),
    (231, 'Which word comes first alphabetically: lantern, journey, candle, umbrella?', 'journey', 'candle', 'umbrella', 'lantern', 'B'),
    (232, 'Which of these words has the most vowels: quiver, ribbon, orchid, ladder?', 'orchid', 'quiver', 'ladder', 'ribbon', 'B'),
    (233, 'Which of these words has the most letters: jigsaw, quilt, glacier, kettle?', 'kettle', 'glacier', 'quilt', 'jigsaw', 'B'),
    (234, 'Which of these words has the fewest letters: kernel, glacier, dragon, notebook?', 'glacier', 'notebook', 'kernel', 'dragon', 'C'),
    (235, 'Which word comes first alphabetically: saturn, velvet, bottle, rainbow?', 'saturn', 'velvet', 'bottle', 'rainbow', 'C'),
    (236, 'Which of these words has the most vowels: dragon, horizon, bottle, kettle?', 'kettle', 'bottle', 'dragon', 'horizon', 'D'),
    (237, 'Which of these words has the most letters: bottle, notebook, ribbon, camera?', 'camera', 'notebook', 'bottle', 'ribbon', 'B'),
    (238, 'Which of these words has the fewest letters: journey, camera, zebra, whisper?', 'camera', 'zebra', 'whisper', 'journey', 'B'),
    (239, 'Which word comes first alphabetically: dragon, thunder, notion, whisper?', 'whisper', 'thunder', 'notion', 'dragon', 'D'),
    (240, 'Which of these words has the most vowels: eclipse, cactus, jigsaw, falcon?', 'falcon', 'eclipse', 'cactus', 'jigsaw', 'B'),
    (241, 'Which of these words has the most letters: zebra, quilt, quiver, ribbon?', 'quilt', 'zebra', 'quiver', 'ribbon', 'C'),
    (242, 'Which of these words has the fewest letters: cactus, ribbon, tangent, rainbow?', 'rainbow', 'ribbon', 'tangent', 'cactus', 'D'),
    (243, 'Which word comes first alphabetically: horizon, shelter, magnet, glacier?', 'shelter', 'horizon', 'magnet', 'glacier', 'D'),
    (244, 'Which of these words has the most vowels: bottle, nectar, apricot, puzzle?', 'nectar', 'bottle', 'apricot', 'puzzle', 'C'),
    (245, 'Which of these words has the most letters: ladder, engine, garden, zephyr?', 'garden', 'ladder', 'zephyr', 'engine', 'B'),
    (246, 'Which of these words has the fewest letters: zephyr, parade, puzzle, horizon?', 'horizon', 'zephyr', 'puzzle', 'parade', 'B'),
    (247, 'Which word comes first alphabetically: kettle, tunnel, horizon, quartz?', 'horizon', 'kettle', 'quartz', 'tunnel', 'A'),
    (248, 'Which of these words has the most vowels: whisper, nectar, harvest, shadow?', 'whisper', 'shadow', 'nectar', 'harvest', 'A'),
    (249, 'Which of these words has the most letters: vacuum, valley, utopia, quartz?', 'valley', 'quartz', 'vacuum', 'utopia', 'C'),
    (250, 'Which of these words has the fewest letters: cactus, kernel, camera, ladder?', 'camera', 'cactus', 'ladder', 'kernel', 'B'),
    (251, 'Which word comes first alphabetically: xylophone, quartz, candle, galaxy?', 'xylophone', 'quartz', 'galaxy', 'candle', 'D'),
    (252, 'Which of these words has the most vowels: candle, anchor, cactus, orchard?', 'orchard', 'candle', 'cactus', 'anchor', 'B'),
    (253, 'Which of these words has the most letters: saturn, quiver, laptop, notebook?', 'laptop', 'quiver', 'saturn', 'notebook', 'D'),
    (254, 'Which of these words has the fewest letters: jungle, glacier, rainbow, magnet?', 'glacier', 'magnet', 'rainbow', 'jungle', 'D'),
    (255, 'Which word comes first alphabetically: thunder, insect, vacuum, desert?', 'vacuum', 'desert', 'thunder', 'insect', 'B'),
    (256, 'Which of these words has the most vowels: nectar, kettle, tangent, parade?', 'kettle', 'nectar', 'parade', 'tangent', 'C'),
    (257, 'Which of these words has the most letters: desert, tangent, valley, notebook?', 'tangent', 'notebook', 'desert', 'valley', 'B'),
    (258, 'Which of these words has the fewest letters: cactus, nectar, lantern, magnet?', 'lantern', 'cactus', 'magnet', 'nectar', 'B'),
    (259, 'Which word comes first alphabetically: apricot, yellow, iguana, kernel?', 'apricot', 'iguana', 'kernel', 'yellow', 'A'),
    (260, 'Which of these words has the most vowels: garden, meteor, kettle, biscuit?', 'kettle', 'biscuit', 'garden', 'meteor', 'D'),
    (261, 'Which of these words has the most letters: laptop, thunder, falcon, garden?', 'laptop', 'falcon', 'garden', 'thunder', 'D'),
    (262, 'Which of these words has the fewest letters: iguana, ribbon, orange, shelter?', 'ribbon', 'orange', 'iguana', 'shelter', 'C'),
    (263, 'Which word comes first alphabetically: zephyr, ribbon, forest, quiver?', 'zephyr', 'quiver', 'forest', 'ribbon', 'C'),
    (264, 'Which of these words has the most vowels: diamond, rocket, candle, magnet?', 'magnet', 'diamond', 'rocket', 'candle', 'B'),
    (265, 'Which of these words has the most letters: laptop, jigsaw, engine, diamond?', 'engine', 'jigsaw', 'diamond', 'laptop', 'C'),
    (266, 'Which of these words has the fewest letters: tunnel, saturn, zephyr, diamond?', 'zephyr', 'diamond', 'tunnel', 'saturn', 'C'),
    (267, 'Which word comes first alphabetically: glacier, engine, anchor, rainbow?', 'anchor', 'engine', 'rainbow', 'glacier', 'A'),
    (268, 'Which of these words has the most vowels: rainbow, diamond, quartz, jungle?', 'quartz', 'jungle', 'diamond', 'rainbow', 'D'),
    (269, 'Which of these words has the most letters: kernel, hammer, journey, rocket?', 'journey', 'rocket', 'kernel', 'hammer', 'A'),
    (270, 'Which of these words has the fewest letters: vacuum, orange, nectar, valley?', 'orange', 'valley', 'vacuum', 'nectar', 'C'),
    (271, 'Which word comes first alphabetically: rocket, zebra, diamond, orchard?', 'diamond', 'rocket', 'zebra', 'orchard', 'A'),
    (272, 'Which of these words has the most vowels: yellow, rocket, velvet, puzzle?', 'puzzle', 'velvet', 'rocket', 'yellow', 'D'),
    (273, 'Which of these words has the most letters: garden, meteor, kettle, kernel?', 'garden', 'kernel', 'kettle', 'meteor', 'A'),
    (274, 'Which of these words has the fewest letters: balloon, nectar, marble, vacuum?', 'balloon', 'vacuum', 'marble', 'nectar', 'D'),
    (275, 'Which word comes first alphabetically: harvest, horizon, vacuum, velvet?', 'harvest', 'vacuum', 'horizon', 'velvet', 'A'),
    (276, 'Which of these words has the most vowels: jungle, biscuit, engine, laptop?', 'biscuit', 'engine', 'jungle', 'laptop', 'A'),
    (277, 'Which of these words has the most letters: island, insect, planet, shadow?', 'insect', 'island', 'shadow', 'planet', 'B'),
    (278, 'Which of these words has the fewest letters: vacuum, magnet, zephyr, island?', 'zephyr', 'island', 'vacuum', 'magnet', 'C'),
    (279, 'Which word comes first alphabetically: velvet, falcon, thunder, balloon?', 'falcon', 'thunder', 'balloon', 'velvet', 'C'),
    (280, 'Which of these words has the most vowels: laptop, insect, orange, xylophone?', 'xylophone', 'laptop', 'insect', 'orange', 'D'),
    (281, 'Which of these words has the most letters: horizon, glacier, biscuit, window?', 'glacier', 'window', 'biscuit', 'horizon', 'D'),
    (282, 'Which of these words has the fewest letters: puzzle, dragon, candle, utopia?', 'puzzle', 'utopia', 'dragon', 'candle', 'A'),
    (283, 'Which word comes first alphabetically: vacuum, saturn, planet, yonder?', 'planet', 'yonder', 'vacuum', 'saturn', 'A'),
    (284, 'Which of these words has the most vowels: notion, orchard, magnet, kernel?', 'orchard', 'kernel', 'magnet', 'notion', 'D'),
    (285, 'Which of these words has the most letters: feather, garden, magnet, yellow?', 'magnet', 'feather', 'yellow', 'garden', 'B'),
    (286, 'Which of these words has the fewest letters: notion, vacuum, utopia, puzzle?', 'vacuum', 'notion', 'puzzle', 'utopia', 'B'),
    (287, 'Which word comes first alphabetically: eclipse, engineer, journey, utopia?', 'eclipse', 'engineer', 'utopia', 'journey', 'A'),
    (288, 'Which of these words has the most vowels: tangent, zebra, bottle, ribbon?', 'ribbon', 'bottle', 'zebra', 'tangent', 'D'),
    (289, 'Which of these words has the most letters: eclipse, hammer, glacier, dragon?', 'hammer', 'glacier', 'eclipse', 'dragon', 'C'),
    (290, 'Which of these words has the fewest letters: journey, thunder, garden, velvet?', 'velvet', 'journey', 'garden', 'thunder', 'C'),
    (291, 'Which word comes first alphabetically: velvet, shelter, magnet, thunder?', 'velvet', 'magnet', 'thunder', 'shelter', 'B'),
    (292, 'Which of these words has the most vowels: kettle, utopia, xylophone, candle?', 'xylophone', 'candle', 'utopia', 'kettle', 'C'),
    (293, 'Which of these words has the most letters: tangent, thunder, saturn, nectar?', 'saturn', 'thunder', 'nectar', 'tangent', 'D'),
    (294, 'Which of these words has the fewest letters: magnet, garden, harvest, parade?', 'garden', 'harvest', 'parade', 'magnet', 'D'),
    (295, 'Which word comes first alphabetically: orange, tangent, meteor, anchor?', 'meteor', 'anchor', 'tangent', 'orange', 'B'),
    (296, 'Which of these words has the most vowels: iguana, quilt, meteor, dragon?', 'dragon', 'quilt', 'meteor', 'iguana', 'D'),
    (297, 'Which of these words has the most letters: lantern, diamond, candle, horizon?', 'lantern', 'horizon', 'candle', 'diamond', 'A'),
    (298, 'Which of these words has the fewest letters: island, engine, xylophone, cactus?', 'engine', 'xylophone', 'cactus', 'island', 'D'),
    (299, 'Which word comes first alphabetically: marble, glacier, saturn, balloon?', 'balloon', 'saturn', 'glacier', 'marble', 'A'),
    (300, 'Which of these words has the most vowels: journey, galaxy, camera, engineer?', 'camera', 'journey', 'engineer', 'galaxy', 'C'),
    (301, 'All brabcrils are clabfruss. All clabfruss are crabplegs. Which statement must be true?', 'No brabcrils are crabplegs.', 'Some brabcrils are crabplegs.', 'All crabplegs are brabcrils.', 'All brabcrils are crabplegs.', 'D'),
    (302, 'All drabslops are flabspads. No flabspads are frabtwims. Which statement must be true?', 'No drabslops are frabtwims.', 'Some drabslops are frabtwims.', 'All frabtwims are drabslops.', 'All drabslops are frabtwims.', 'A'),
    (303, 'All glabbruts are grabdreks. All plabglors are glabbruts. Which statement must be true?', 'No plabglors are grabdreks.', 'All plabglors are grabdreks.', 'Some plabglors are glabbruts.', 'All grabdreks are plabglors.', 'B'),
    (304, 'No prabprafs are skabsmins. All slabstubs are prabprafs. Which statement must be true?', 'No slabstubs are skabsmins.', 'Some slabstubs are skabsmins.', 'All slabstubs are skabsmins.', 'All skabsmins are slabstubs.', 'A'),
    (305, 'All smabwhels are snabcloss. No spabflags are snabcloss. Which statement must be true?', 'No spabflags are smabwhels.', 'All spabflags are smabwhels.', 'All smabwhels are spabflags.', 'Some spabflags are smabwhels.', 'A'),
    (306, 'All stabgrips are trabskuds. All trabskuds are twabsnems. Which statement must be true?', 'All twabsnems are stabgrips.', 'Some stabgrips are twabsnems.', 'No stabgrips are twabsnems.', 'All stabgrips are twabsnems.', 'D'),
    (307, 'All whabtrots are blebblaks. No blebblaks are brebcrirs. Which statement must be true?', 'No whabtrots are brebcrirs.', 'Some whabtrots are brebcrirs.', 'All brebcrirs are whabtrots.', 'All whabtrots are brebcrirs.', 'A'),
    (308, 'All clebfrufs are crebplens. All drebslobs are clebfrufs. Which statement must be true?', 'Some drebslobs are clebfrufs.', 'All drebslobs are crebplens.', 'All crebplens are drebslobs.', 'No drebslobs are crebplens.', 'B'),
    (309, 'No flebspals are frebtwiss. All glebbrugs are flebspals. Which statement must be true?', 'Some glebbrugs are frebtwiss.', 'All glebbrugs are frebtwiss.', 'All frebtwiss are glebbrugs.', 'No glebbrugs are frebtwiss.', 'D'),
    (310, 'All grebdreps are plebglods. No prebprams are plebglods. Which statement must be true?', 'All prebprams are grebdreps.', 'No prebprams are grebdreps.', 'Some prebprams are grebdreps.', 'All grebdreps are prebprams.', 'B'),
    (311, 'All skebsmits are slebstuks. All slebstuks are smebwhers. Which statement must be true?', 'Some skebsmits are smebwhers.', 'All skebsmits are smebwhers.', 'All smebwhers are skebsmits.', 'No skebsmits are smebwhers.', 'B'),
    (312, 'All snebclofs are spebflans. No spebflans are stebgribs. Which statement must be true?', 'No snebclofs are stebgribs.', 'Some snebclofs are stebgribs.', 'All stebgribs are snebclofs.', 'All snebclofs are stebgribs.', 'A'),
    (313, 'All trebskuls are twebsness. All whebtrogs are trebskuls. Which statement must be true?', 'All twebsness are whebtrogs.', 'All whebtrogs are twebsness.', 'Some whebtrogs are trebskuls.', 'No whebtrogs are twebsness.', 'B'),
    (314, 'No blibblaps are bribcrids. All clibfrums are blibblaps. Which statement must be true?', 'No clibfrums are bribcrids.', 'All clibfrums are bribcrids.', 'All bribcrids are clibfrums.', 'Some clibfrums are bribcrids.', 'A'),
    (315, 'All cribplets are dribsloks. No flibspars are dribsloks. Which statement must be true?', 'All flibspars are cribplets.', 'No flibspars are cribplets.', 'Some flibspars are cribplets.', 'All cribplets are flibspars.', 'B'),
    (316, 'All fribtwifs are glibbruns. All glibbruns are gribdrebs. Which statement must be true?', 'All gribdrebs are fribtwifs.', 'No fribtwifs are gribdrebs.', 'All fribtwifs are gribdrebs.', 'Some fribtwifs are gribdrebs.', 'C'),
    (317, 'All plibglols are pribprass. No pribprass are skibsmigs. Which statement must be true?', 'All plibglols are skibsmigs.', 'No plibglols are skibsmigs.', 'Some plibglols are skibsmigs.', 'All skibsmigs are plibglols.', 'B'),
    (318, 'All slibstups are smibwheds. All snibcloms are slibstups. Which statement must be true?', 'All smibwheds are snibcloms.', 'No snibcloms are smibwheds.', 'Some snibcloms are slibstups.', 'All snibcloms are smibwheds.', 'D'),
    (319, 'No spibflats are stibgriks. All tribskurs are spibflats. Which statement must be true?', 'All tribskurs are stibgriks.', 'Some tribskurs are stibgriks.', 'All stibgriks are tribskurs.', 'No tribskurs are stibgriks.', 'D'),
    (320, 'All twibsnefs are whibtrons. No blobblabs are whibtrons. Which statement must be true?', 'All twibsnefs are blobblabs.', 'All blobblabs are twibsnefs.', 'No blobblabs are twibsnefs.', 'Some blobblabs are twibsnefs.', 'C'),
    (321, 'All brobcrils are clobfruss. All clobfruss are crobplegs. Which statement must be true?', 'Some brobcrils are crobplegs.', 'All brobcrils are crobplegs.', 'All crobplegs are brobcrils.', 'No brobcrils are crobplegs.', 'B'),
    (322, 'All drobslops are flobspads. No flobspads are frobtwims. Which statement must be true?', 'All drobslops are frobtwims.', 'No drobslops are frobtwims.', 'Some drobslops are frobtwims.', 'All frobtwims are drobslops.', 'B'),
    (323, 'All globbruts are grobdreks. All plobglors are globbruts. Which statement must be true?', 'All plobglors are grobdreks.', 'Some plobglors are globbruts.', 'No plobglors are grobdreks.', 'All grobdreks are plobglors.', 'A'),
    (324, 'No probprafs are skobsmins. All slobstubs are probprafs. Which statement must be true?', 'All skobsmins are slobstubs.', 'No slobstubs are skobsmins.', 'All slobstubs are skobsmins.', 'Some slobstubs are skobsmins.', 'B'),
    (325, 'All smobwhels are snobcloss. No spobflags are snobcloss. Which statement must be true?', 'All spobflags are smobwhels.', 'All smobwhels are spobflags.', 'No spobflags are smobwhels.', 'Some spobflags are smobwhels.', 'C'),
    (326, 'All stobgrips are trobskuds. All trobskuds are twobsnems. Which statement must be true?', 'All twobsnems are stobgrips.', 'All stobgrips are twobsnems.', 'Some stobgrips are twobsnems.', 'No stobgrips are twobsnems.', 'B'),
    (327, 'All whobtrots are blubblaks. No blubblaks are brubcrirs. Which statement must be true?', 'All whobtrots are brubcrirs.', 'Some whobtrots are brubcrirs.', 'All brubcrirs are whobtrots.', 'No whobtrots are brubcrirs.', 'D'),
    (328, 'All clubfrufs are crubplens. All drubslobs are clubfrufs. Which statement must be true?', 'All crubplens are drubslobs.', 'Some drubslobs are clubfrufs.', 'All drubslobs are crubplens.', 'No drubslobs are crubplens.', 'C'),
    (329, 'No flubspals are frubtwiss. All glubbrugs are flubspals. Which statement must be true?', 'All glubbrugs are frubtwiss.', 'No glubbrugs are frubtwiss.', 'Some glubbrugs are frubtwiss.', 'All frubtwiss are glubbrugs.', 'B'),
    (330, 'All grubdreps are plubglods. No prubprams are plubglods. Which statement must be true?', 'All prubprams are grubdreps.', 'Some prubprams are grubdreps.', 'No prubprams are grubdreps.', 'All grubdreps are prubprams.', 'C'),
    (331, 'All skubsmits are slubstuks. All slubstuks are smubwhers. Which statement must be true?', 'No skubsmits are smubwhers.', 'All smubwhers are skubsmits.', 'Some skubsmits are smubwhers.', 'All skubsmits are smubwhers.', 'D'),
    (332, 'All snubclofs are spubflans. No spubflans are stubgribs. Which statement must be true?', 'All stubgribs are snubclofs.', 'Some snubclofs are stubgribs.', 'All snubclofs are stubgribs.', 'No snubclofs are stubgribs.', 'D'),
    (333, 'All trubskuls are twubsness. All whubtrogs are trubskuls. Which statement must be true?', 'All twubsness are whubtrogs.', 'No whubtrogs are twubsness.', 'All whubtrogs are twubsness.', 'Some whubtrogs are trubskuls.', 'C'),
    (334, 'No bladblaps are bradcrids. All cladfrums are bladblaps. Which statement must be true?', 'All bradcrids are cladfrums.', 'Some cladfrums are bradcrids.', 'No cladfrums are bradcrids.', 'All cladfrums are bradcrids.', 'C'),
    (335, 'All cradplets are dradsloks. No fladspars are dradsloks. Which statement must be true?', 'All fladspars are cradplets.', 'No fladspars are cradplets.', 'All cradplets are fladspars.', 'Some fladspars are cradplets.', 'B'),
    (336, 'All fradtwifs are gladbruns. All gladbruns are graddrebs. Which statement must be true?', 'All fradtwifs are graddrebs.', 'No fradtwifs are graddrebs.', 'Some fradtwifs are graddrebs.', 'All graddrebs are fradtwifs.', 'A'),
    (337, 'All pladglols are pradprass. No pradprass are skadsmigs. Which statement must be true?', 'No pladglols are skadsmigs.', 'All skadsmigs are pladglols.', 'All pladglols are skadsmigs.', 'Some pladglols are skadsmigs.', 'A'),
    (338, 'All sladstups are smadwheds. All snadcloms are sladstups. Which statement must be true?', 'No snadcloms are smadwheds.', 'All smadwheds are snadcloms.', 'Some snadcloms are sladstups.', 'All snadcloms are smadwheds.', 'D'),
    (339, 'No spadflats are stadgriks. All tradskurs are spadflats. Which statement must be true?', 'Some tradskurs are stadgriks.', 'No tradskurs are stadgriks.', 'All tradskurs are stadgriks.', 'All stadgriks are tradskurs.', 'B'),
    (340, 'All twadsnefs are whadtrons. No bledblabs are whadtrons. Which statement must be true?', 'Some bledblabs are twadsnefs.', 'No bledblabs are twadsnefs.', 'All bledblabs are twadsnefs.', 'All twadsnefs are bledblabs.', 'B'),
    (341, 'All bredcrils are cledfruss. All cledfruss are credplegs. Which statement must be true?', 'Some bredcrils are credplegs.', 'All credplegs are bredcrils.', 'No bredcrils are credplegs.', 'All bredcrils are credplegs.', 'D'),
    (342, 'All dredslops are fledspads. No fledspads are fredtwims. Which statement must be true?', 'All fredtwims are dredslops.', 'Some dredslops are fredtwims.', 'No dredslops are fredtwims.', 'All dredslops are fredtwims.', 'C'),
    (343, 'All gledbruts are greddreks. All pledglors are gledbruts. Which statement must be true?', 'Some pledglors are gledbruts.', 'No pledglors are greddreks.', 'All greddreks are pledglors.', 'All pledglors are greddreks.', 'D'),
    (344, 'No predprafs are skedsmins. All sledstubs are predprafs. Which statement must be true?', 'Some sledstubs are skedsmins.', 'No sledstubs are skedsmins.', 'All sledstubs are skedsmins.', 'All skedsmins are sledstubs.', 'B'),
    (345, 'All smedwhels are snedcloss. No spedflags are snedcloss. Which statement must be true?', 'Some spedflags are smedwhels.', 'All spedflags are smedwhels.', 'No spedflags are smedwhels.', 'All smedwhels are spedflags.', 'C'),
    (346, 'All stedgrips are tredskuds. All tredskuds are twedsnems. Which statement must be true?', 'No stedgrips are twedsnems.', 'All twedsnems are stedgrips.', 'All stedgrips are twedsnems.', 'Some stedgrips are twedsnems.', 'C'),
    (347, 'All whedtrots are blidblaks. No blidblaks are bridcrirs. Which statement must be true?', 'All bridcrirs are whedtrots.', 'All whedtrots are bridcrirs.', 'No whedtrots are bridcrirs.', 'Some whedtrots are bridcrirs.', 'C'),
    (348, 'All clidfrufs are cridplens. All dridslobs are clidfrufs. Which statement must be true?', 'No dridslobs are cridplens.', 'Some dridslobs are clidfrufs.', 'All cridplens are dridslobs.', 'All dridslobs are cridplens.', 'D'),
    (349, 'No flidspals are fridtwiss. All glidbrugs are flidspals. Which statement must be true?', 'All fridtwiss are glidbrugs.', 'All glidbrugs are fridtwiss.', 'Some glidbrugs are fridtwiss.', 'No glidbrugs are fridtwiss.', 'D'),
    (350, 'All griddreps are plidglods. No pridprams are plidglods. Which statement must be true?', 'Some pridprams are griddreps.', 'All griddreps are pridprams.', 'All pridprams are griddreps.', 'No pridprams are griddreps.', 'D'),
    (351, 'All skidsmits are slidstuks. All slidstuks are smidwhers. Which statement must be true?', 'All smidwhers are skidsmits.', 'No skidsmits are smidwhers.', 'All skidsmits are smidwhers.', 'Some skidsmits are smidwhers.', 'C'),
    (352, 'All snidclofs are spidflans. No spidflans are stidgribs. Which statement must be true?', 'All stidgribs are snidclofs.', 'All snidclofs are stidgribs.', 'No snidclofs are stidgribs.', 'Some snidclofs are stidgribs.', 'C'),
    (353, 'All tridskuls are twidsness. All whidtrogs are tridskuls. Which statement must be true?', 'Some whidtrogs are tridskuls.', 'All twidsness are whidtrogs.', 'All whidtrogs are twidsness.', 'No whidtrogs are twidsness.', 'C'),
    (354, 'No blodblaps are brodcrids. All clodfrums are blodblaps. Which statement must be true?', 'All brodcrids are clodfrums.', 'Some clodfrums are brodcrids.', 'No clodfrums are brodcrids.', 'All clodfrums are brodcrids.', 'C'),
    (355, 'All crodplets are drodsloks. No flodspars are drodsloks. Which statement must be true?', 'Some flodspars are crodplets.', 'All flodspars are crodplets.', 'All crodplets are flodspars.', 'No flodspars are crodplets.', 'D'),
    (356, 'All frodtwifs are glodbruns. All glodbruns are groddrebs. Which statement must be true?', 'All frodtwifs are groddrebs.', 'Some frodtwifs are groddrebs.', 'No frodtwifs are groddrebs.', 'All groddrebs are frodtwifs.', 'A'),
    (357, 'All plodglols are prodprass. No prodprass are skodsmigs. Which statement must be true?', 'All skodsmigs are plodglols.', 'No plodglols are skodsmigs.', 'All plodglols are skodsmigs.', 'Some plodglols are skodsmigs.', 'B'),
    (358, 'All slodstups are smodwheds. All snodcloms are slodstups. Which statement must be true?', 'No snodcloms are smodwheds.', 'Some snodcloms are slodstups.', 'All smodwheds are snodcloms.', 'All snodcloms are smodwheds.', 'D'),
    (359, 'No spodflats are stodgriks. All trodskurs are spodflats. Which statement must be true?', 'All stodgriks are trodskurs.', 'Some trodskurs are stodgriks.', 'All trodskurs are stodgriks.', 'No trodskurs are stodgriks.', 'D'),
    (360, 'All twodsnefs are whodtrons. No bludblabs are whodtrons. Which statement must be true?', 'Some bludblabs are twodsnefs.', 'All bludblabs are twodsnefs.', 'No bludblabs are twodsnefs.', 'All twodsnefs are bludblabs.', 'C'),
    (361, 'All brudcrils are cludfruss. All cludfruss are crudplegs. Which statement must be true?', 'No brudcrils are crudplegs.', 'All brudcrils are crudplegs.', 'Some brudcrils are crudplegs.', 'All crudplegs are brudcrils.', 'B'),
    (362, 'All drudslops are fludspads. No fludspads are frudtwims. Which statement must be true?', 'No drudslops are frudtwims.', 'All drudslops are frudtwims.', 'All frudtwims are drudslops.', 'Some drudslops are frudtwims.', 'A'),
    (363, 'All gludbruts are gruddreks. All pludglors are gludbruts. Which statement must be true?', 'No pludglors are gruddreks.', 'All gruddreks are pludglors.', 'Some pludglors are gludbruts.', 'All pludglors are gruddreks.', 'D'),
    (364, 'No prudprafs are skudsmins. All sludstubs are prudprafs. Which statement must be true?', 'All sludstubs are skudsmins.', 'No sludstubs are skudsmins.', 'All skudsmins are sludstubs.', 'Some sludstubs are skudsmins.', 'B'),
    (365, 'All smudwhels are snudcloss. No spudflags are snudcloss. Which statement must be true?', 'All spudflags are smudwhels.', 'No spudflags are smudwhels.', 'All smudwhels are spudflags.', 'Some spudflags are smudwhels.', 'B'),
    (366, 'All studgrips are trudskuds. All trudskuds are twudsnems. Which statement must be true?', 'Some studgrips are twudsnems.', 'No studgrips are twudsnems.', 'All twudsnems are studgrips.', 'All studgrips are twudsnems.', 'D'),
    (367, 'All whudtrots are blafblaks. No blafblaks are brafcrirs. Which statement must be true?', 'All whudtrots are brafcrirs.', 'All brafcrirs are whudtrots.', 'Some whudtrots are brafcrirs.', 'No whudtrots are brafcrirs.', 'D'),
    (368, 'All claffrufs are crafplens. All drafslobs are claffrufs. Which statement must be true?', 'All crafplens are drafslobs.', 'Some drafslobs are claffrufs.', 'No drafslobs are crafplens.', 'All drafslobs are crafplens.', 'D'),
    (369, 'No flafspals are fraftwiss. All glafbrugs are flafspals. Which statement must be true?', 'All fraftwiss are glafbrugs.', 'All glafbrugs are fraftwiss.', 'Some glafbrugs are fraftwiss.', 'No glafbrugs are fraftwiss.', 'D'),
    (370, 'All grafdreps are plafglods. No prafprams are plafglods. Which statement must be true?', 'All prafprams are grafdreps.', 'Some prafprams are grafdreps.', 'All grafdreps are prafprams.', 'No prafprams are grafdreps.', 'D'),
    (371, 'All skafsmits are slafstuks. All slafstuks are smafwhers. Which statement must be true?', 'All smafwhers are skafsmits.', 'No skafsmits are smafwhers.', 'Some skafsmits are smafwhers.', 'All skafsmits are smafwhers.', 'D'),
    (372, 'All snafclofs are spafflans. No spafflans are stafgribs. Which statement must be true?', 'All stafgribs are snafclofs.', 'Some snafclofs are stafgribs.', 'All snafclofs are stafgribs.', 'No snafclofs are stafgribs.', 'D'),
    (373, 'All trafskuls are twafsness. All whaftrogs are trafskuls. Which statement must be true?', 'All twafsness are whaftrogs.', 'All whaftrogs are twafsness.', 'No whaftrogs are twafsness.', 'Some whaftrogs are trafskuls.', 'B'),
    (374, 'No blefblaps are brefcrids. All cleffrums are blefblaps. Which statement must be true?', 'Some cleffrums are brefcrids.', 'All cleffrums are brefcrids.', 'All brefcrids are cleffrums.', 'No cleffrums are brefcrids.', 'D'),
    (375, 'All crefplets are drefsloks. No flefspars are drefsloks. Which statement must be true?', 'All crefplets are flefspars.', 'Some flefspars are crefplets.', 'All flefspars are crefplets.', 'No flefspars are crefplets.', 'D'),
    (376, 'All freftwifs are glefbruns. All glefbruns are grefdrebs. Which statement must be true?', 'No freftwifs are grefdrebs.', 'All freftwifs are grefdrebs.', 'All grefdrebs are freftwifs.', 'Some freftwifs are grefdrebs.', 'B'),
    (377, 'All plefglols are prefprass. No prefprass are skefsmigs. Which statement must be true?', 'All plefglols are skefsmigs.', 'Some plefglols are skefsmigs.', 'No plefglols are skefsmigs.', 'All skefsmigs are plefglols.', 'C'),
    (378, 'All slefstups are smefwheds. All snefcloms are slefstups. Which statement must be true?', 'All snefcloms are smefwheds.', 'No snefcloms are smefwheds.', 'Some snefcloms are slefstups.', 'All smefwheds are snefcloms.', 'A'),
    (379, 'No spefflats are stefgriks. All trefskurs are spefflats. Which statement must be true?', 'All stefgriks are trefskurs.', 'All trefskurs are stefgriks.', 'Some trefskurs are stefgriks.', 'No trefskurs are stefgriks.', 'D'),
    (380, 'All twefsnefs are wheftrons. No blifblabs are wheftrons. Which statement must be true?', 'No blifblabs are twefsnefs.', 'All blifblabs are twefsnefs.', 'All twefsnefs are blifblabs.', 'Some blifblabs are twefsnefs.', 'A'),
    (381, 'All brifcrils are cliffruss. All cliffruss are crifplegs. Which statement must be true?', 'All brifcrils are crifplegs.', 'All crifplegs are brifcrils.', 'No brifcrils are crifplegs.', 'Some brifcrils are crifplegs.', 'A'),
    (382, 'All drifslops are flifspads. No flifspads are friftwims. Which statement must be true?', 'All friftwims are drifslops.', 'Some drifslops are friftwims.', 'All drifslops are friftwims.', 'No drifslops are friftwims.', 'D'),
    (383, 'All glifbruts are grifdreks. All plifglors are glifbruts. Which statement must be true?', 'All grifdreks are plifglors.', 'No plifglors are grifdreks.', 'Some plifglors are glifbruts.', 'All plifglors are grifdreks.', 'D'),
    (384, 'No prifprafs are skifsmins. All slifstubs are prifprafs. Which statement must be true?', 'Some slifstubs are skifsmins.', 'No slifstubs are skifsmins.', 'All slifstubs are skifsmins.', 'All skifsmins are slifstubs.', 'B'),
    (385, 'All smifwhels are snifcloss. No spifflags are snifcloss. Which statement must be true?', 'All smifwhels are spifflags.', 'Some spifflags are smifwhels.', 'All spifflags are smifwhels.', 'No spifflags are smifwhels.', 'D'),
    (386, 'All stifgrips are trifskuds. All trifskuds are twifsnems. Which statement must be true?', 'All stifgrips are twifsnems.', 'Some stifgrips are twifsnems.', 'All twifsnems are stifgrips.', 'No stifgrips are twifsnems.', 'A'),
    (387, 'All whiftrots are blofblaks. No blofblaks are brofcrirs. Which statement must be true?', 'All brofcrirs are whiftrots.', 'Some whiftrots are brofcrirs.', 'No whiftrots are brofcrirs.', 'All whiftrots are brofcrirs.', 'C'),
    (388, 'All cloffrufs are crofplens. All drofslobs are cloffrufs. Which statement must be true?', 'All crofplens are drofslobs.', 'Some drofslobs are cloffrufs.', 'All drofslobs are crofplens.', 'No drofslobs are crofplens.', 'C'),
    (389, 'No flofspals are froftwiss. All glofbrugs are flofspals. Which statement must be true?', 'All froftwiss are glofbrugs.', 'No glofbrugs are froftwiss.', 'All glofbrugs are froftwiss.', 'Some glofbrugs are froftwiss.', 'B'),
    (390, 'All grofdreps are plofglods. No profprams are plofglods. Which statement must be true?', 'Some profprams are grofdreps.', 'All grofdreps are profprams.', 'All profprams are grofdreps.', 'No profprams are grofdreps.', 'D'),
    (391, 'All skofsmits are slofstuks. All slofstuks are smofwhers. Which statement must be true?', 'All skofsmits are smofwhers.', 'All smofwhers are skofsmits.', 'No skofsmits are smofwhers.', 'Some skofsmits are smofwhers.', 'A'),
    (392, 'All snofclofs are spofflans. No spofflans are stofgribs. Which statement must be true?', 'No snofclofs are stofgribs.', 'All stofgribs are snofclofs.', 'Some snofclofs are stofgribs.', 'All snofclofs are stofgribs.', 'A'),
    (393, 'All trofskuls are twofsness. All whoftrogs are trofskuls. Which statement must be true?', 'All twofsness are whoftrogs.', 'All whoftrogs are twofsness.', 'Some whoftrogs are trofskuls.', 'No whoftrogs are twofsness.', 'B'),
    (394, 'No blufblaps are brufcrids. All cluffrums are blufblaps. Which statement must be true?', 'All cluffrums are brufcrids.', 'All brufcrids are cluffrums.', 'Some cluffrums are brufcrids.', 'No cluffrums are brufcrids.', 'D'),
    (395, 'All crufplets are drufsloks. No flufspars are drufsloks. Which statement must be true?', 'All crufplets are flufspars.', 'Some flufspars are crufplets.', 'No flufspars are crufplets.', 'All flufspars are crufplets.', 'C'),
    (396, 'All fruftwifs are glufbruns. All glufbruns are grufdrebs. Which statement must be true?', 'Some fruftwifs are grufdrebs.', 'All fruftwifs are grufdrebs.', 'All grufdrebs are fruftwifs.', 'No fruftwifs are grufdrebs.', 'B'),
    (397, 'All plufglols are prufprass. No prufprass are skufsmigs. Which statement must be true?', 'All plufglols are skufsmigs.', 'Some plufglols are skufsmigs.', 'No plufglols are skufsmigs.', 'All skufsmigs are plufglols.', 'C'),
    (398, 'All slufstups are smufwheds. All snufcloms are slufstups. Which statement must be true?', 'All smufwheds are snufcloms.', 'No snufcloms are smufwheds.', 'Some snufcloms are slufstups.', 'All snufcloms are smufwheds.', 'D'),
    (399, 'No spufflats are stufgriks. All trufskurs are spufflats. Which statement must be true?', 'All trufskurs are stufgriks.', 'No trufskurs are stufgriks.', 'All stufgriks are trufskurs.', 'Some trufskurs are stufgriks.', 'B'),
    (400, 'All twufsnefs are whuftrons. No blagblabs are whuftrons. Which statement must be true?', 'No blagblabs are twufsnefs.', 'All twufsnefs are blagblabs.', 'All blagblabs are twufsnefs.', 'Some blagblabs are twufsnefs.', 'A'),
    (401, 'A doctor gives you 3 pills and says to take one every half hour. How long do the pills last?', '0 hours', '1 hours', '2 hours', '1 hours', 'B'),
    (402, 'A farmer has 21 sheep. All but 15 die. How many sheep are left?', '16 sheep', '15 sheep', '21 sheep', '14 sheep', 'B'),
    (403, 'How many times can you subtract 5 from 32?', 'once', 'twice', 'never', 'three times', 'A'),
    (404, 'If you have 13 oranges and take away 11, how many oranges do you have?', '11 oranges', '13 oranges', '0 oranges', '10 oranges', 'A'),
    (405, 'A room has 8 corners and a chair in each corner. How many chairs are there?', '8 chairs', '9 chairs', '7 chairs', '1 chair', 'A'),
    (406, 'How many letters are in the word Fladspar?', '9', '8', '10', '7', 'B'),
    (407, 'What time is 3 hours and 28 minutes after 8:42 am?', '12:10 pm', '1:10 pm', '11:55 am', '12:25 pm', 'A'),
    (408, 'A train leaves at 1:59 am and travels for 4 hours. What time does it arrive?', '5:29 am', '5:59 am', '6:59 am', '6:29 am', 'B'),
    (409, 'If a book has 10 pages and you read 2 pages a day, how many days will it take to finish?', '6', '5', '6', '5', 'B'),
    (410, 'If a rooster lays an egg on a roof, which way does it roll?', 'It does not roll', 'Left', 'Down', 'Right', 'A'),
    (411, 'A doctor gives you 23 pills and says to take one every half hour. How long do the pills last?', '11 hours', '11 hours', '12 hours', '10 hours', 'A'),
    (412, 'A farmer has 31 sheep. All but 25 die. How many sheep are left?', '25 sheep', '31 sheep', '24 sheep', '26 sheep', 'A'),
    (413, 'How many times can you subtract 5 from 42?', 'three times', 'once', 'never', 'twice', 'B'),
    (414, 'If you have 23 oranges and take away 21, how many oranges do you have?', '20 oranges', '21 oranges', '23 oranges', '0 oranges', 'B'),
    (415, 'A room has 18 corners and a chair in each corner. How many chairs are there?', '1 chair', '17 chairs', '19 chairs', '18 chairs', 'D'),
    (416, 'How many letters are in the word Spadflat?', '7', '10', '9', '8', 'D'),
    (417, 'What time is 1 hours and 58 minutes after 9:52 am?', '12:05 pm', '12:50 pm', '11:35 am', '11:50 am', 'D'),
    (418, 'A train leaves at 4:49 am and travels for 4 hours. What time does it arrive?', '9:49 am', '9:19 am', '8:19 am', '8:49 am', 'D'),
    (419, 'If a book has 20 pages and you read 2 pages a day, how many days will it take to finish?', '10', '11', '10', '11', 'A'),
    (420, 'If a duck lays an egg on a shed roof, which way does it roll?', 'Left', 'Right', 'Down', 'It does not roll', 'D'),
    (421, 'A doctor gives you 43 pills and says to take one every half hour. How long do the pills last?', '21 hours', '20 hours', '22 hours', '21 hours', 'D'),
    (422, 'A farmer has 41 sheep. All but 35 die. How many sheep are left?', '41 sheep', '35 sheep', '36 sheep', '34 sheep', 'B'),
    (423, 'How many times can you subtract 5 from 52?', 'never', 'once', 'three times', 'twice', 'B'),
    (424, 'If you have 33 oranges and take away 31, how many oranges do you have?', '30 oranges', '31 oranges', '33 oranges', '0 oranges', 'B'),
    (425, 'A room has 28 corners and a chair in each corner. How many chairs are there?', '28 chairs', '27 chairs', '1 chair', '29 chairs', 'A'),
    (426, 'How many letters are in the word Fledspad?', '8', '9', '10', '7', 'A'),
    (427, 'What time is 3 hours and 38 minutes after 8:02 am?', '11:55 am', '11:25 am', '11:40 am', '12:40 pm', 'C'),
    (428, 'A train leaves at 7:39 am and travels for 4 hours. What time does it arrive?', '11:39 am', '11:09 am', '12:39 pm', '12:09 pm', 'A'),
    (429, 'If a book has 30 pages and you read 2 pages a day, how many days will it take to finish?', '16', '16', '15', '15', 'C'),
    (430, 'If a hen lays an egg on a barn roof, which way does it roll?', 'Down', 'Left', 'It does not roll', 'Right', 'C'),
    (431, 'A doctor gives you 63 pills and says to take one every half hour. How long do the pills last?', '30 hours', '31 hours', '31 hours', '32 hours', 'B'),
    (432, 'A farmer has 51 sheep. All but 45 die. How many sheep are left?', '51 sheep', '44 sheep', '45 sheep', '46 sheep', 'C'),
    (433, 'How many times can you subtract 5 from 62?', 'never', 'twice', 'three times', 'once', 'D'),
    (434, 'If you have 43 oranges and take away 41, how many oranges do you have?', '43 oranges', '40 oranges', '0 oranges', '41 oranges', 'D'),
    (435, 'A room has 38 corners and a chair in each corner. How many chairs are there?', '39 chairs', '37 chairs', '1 chair', '38 chairs', 'D'),
    (436, 'How many letters are in the word Spedflag?', '9', '8', '10', '7', 'B'),
    (437, 'What time is 1 hours and 18 minutes after 9:12 am?', '10:45 am', '10:15 am', '10:30 am', '11:30 am', 'C'),
    (438, 'A train leaves at 10:29 am and travels for 4 hours. What time does it arrive?', '2:59 pm', '2:29 pm', '3:29 pm', '1:59 pm', 'B'),
    (439, 'If a book has 40 pages and you read 2 pages a day, how many days will it take to finish?', '21', '21', '20', '20', 'D'),
    (440, 'If a goose lays an egg on a garage roof, which way does it roll?', 'Right', 'Left', 'It does not roll', 'Down', 'C'),
    (441, 'A doctor gives you 83 pills and says to take one every half hour. How long do the pills last?', '41 hours', '40 hours', '42 hours', '41 hours', 'D'),
    (442, 'A farmer has 61 sheep. All but 55 die. How many sheep are left?', '54 sheep', '55 sheep', '56 sheep', '61 sheep', 'B'),
    (443, 'How many times can you subtract 5 from 72?', 'twice', 'never', 'once', 'three times', 'C'),
    (444, 'If you have 53 oranges and take away 51, how many oranges do you have?', '51 oranges', '50 oranges', '53 oranges', '0 oranges', 'A'),
    (445, 'A room has 48 corners and a chair in each corner. How many chairs are there?', '1 chair', '47 chairs', '48 chairs', '49 chairs', 'C'),
    (446, 'How many letters are in the word Flidspal?', '9', '8', '10', '7', 'B'),
    (447, 'What time is 3 hours and 48 minutes after 10:22 am?', '2:10 pm', '1:55 pm', '3:10 pm', '2:25 pm', 'A'),
    (448, 'A train leaves at 1:19 pm and travels for 4 hours. What time does it arrive?', '4:49 pm', '5:19 pm', '6:19 pm', '5:49 pm', 'B'),
    (449, 'If a book has 50 pages and you read 2 pages a day, how many days will it take to finish?', '25', '26', '25', '26', 'C'),
    (450, 'If a turkey lays an egg on a porch roof, which way does it roll?', 'Down', 'It does not roll', 'Left', 'Right', 'B'),
    (451, 'A doctor gives you 103 pills and says to take one every half hour. How long do the pills last?', '52 hours', '51 hours', '51 hours', '50 hours', 'C'),
    (452, 'A farmer has 71 sheep. All but 65 die. How many sheep are left?', '66 sheep', '71 sheep', '64 sheep', '65 sheep', 'D'),
    (453, 'How many times can you subtract 5 from 82?', 'three times', 'once', 'twice', 'never', 'B'),
    (454, 'If you have 63 oranges and take away 61, how many oranges do you have?', '0 oranges', '63 oranges', '61 oranges', '60 oranges', 'C'),
    (455, 'A room has 58 corners and a chair in each corner. How many chairs are there?', '58 chairs', '57 chairs', '1 chair', '59 chairs', 'A'),
    (456, 'How many letters are in the word Spidflan?', '10', '8', '9', '7', 'B'),
    (457, 'What time is 1 hours and 28 minutes after 8:32 am?', '10:00 am', '9:45 am', '11:00 am', '10:15 am', 'A'),
    (458, 'A train leaves at 4:09 pm and travels for 4 hours. What time does it arrive?', '8:39 pm', '7:39 pm', '8:09 pm', '9:09 pm', 'C'),
    (459, 'If a book has 60 pages and you read 2 pages a day, how many days will it take to finish?', '30', '31', '31', '30', 'D'),
    (460, 'If a emu lays an egg on a lean-to roof, which way does it roll?', 'Left', 'It does not roll', 'Down', 'Right', 'B'),
    (461, 'A doctor gives you 123 pills and says to take one every half hour. How long do the pills last?', '61 hours', '61 hours', '60 hours', '62 hours', 'A'),
    (462, 'A farmer has 81 sheep. All but 75 die. How many sheep are left?', '74 sheep', '76 sheep', '75 sheep', '81 sheep', 'C'),
    (463, 'How many times can you subtract 5 from 92?', 'twice', 'three times', 'once', 'never', 'C'),
    (464, 'If you have 73 oranges and take away 71, how many oranges do you have?', '0 oranges', '71 oranges', '73 oranges', '70 oranges', 'B'),
    (465, 'A room has 68 corners and a chair in each corner. How many chairs are there?', '1 chair', '68 chairs', '69 chairs', '67 chairs', 'B'),
    (466, 'How many letters are in the word Flodspar?', '10', '9', '8', '7', 'C'),
    (467, 'What time is 3 hours and 58 minutes after 9:42 am?', '1:55 pm', '1:40 pm', '1:25 pm', '2:40 pm', 'B'),
    (468, 'A train leaves at 6:59 pm and travels for 4 hours. What time does it arrive?', '11:59 pm', '10:59 pm', '10:29 pm', '11:29 pm', 'B'),
    (469, 'If a book has 70 pages and you read 2 pages a day, how many days will it take to finish?', '36', '35', '36', '35', 'B'),
    (470, 'If a ostrich lays an egg on a glass roof, which way does it roll?', 'Right', 'Down', 'Left', 'It does not roll', 'D'),
    (471, 'A doctor gives you 143 pills and says to take one every half hour. How long do the pills last?', '71 hours', '72 hours', '71 hours', '70 hours', 'A'),
    (472, 'A farmer has 91 sheep. All but 85 die. How many sheep are left?', '86 sheep', '85 sheep', '91 sheep', '84 sheep', 'B'),
    (473, 'How many times can you subtract 5 from 102?', 'twice', 'three times', 'once', 'never', 'C'),
    (474, 'If you have 83 oranges and take away 81, how many oranges do you have?', '83 oranges', '80 oranges', '81 oranges', '0 oranges', 'C'),
    (475, 'A room has 78 corners and a chair in each corner. How many chairs are there?', '78 chairs', '79 chairs', '1 chair', '77 chairs', 'A'),
    (476, 'How many letters are in the word Spodflat?', '8', '7', '9', '10', 'A'),
    (477, 'What time is 1 hours and 38 minutes after 10:52 am?', '1:30 pm', '12:45 pm', '12:30 pm', '12:15 pm', 'C'),
    (478, 'A train leaves at 9:49 pm and travels for 4 hours. What time does it arrive?', '1:49 am', '2:49 am', '2:19 am', '1:19 am', 'A'),
    (479, 'If a book has 80 pages and you read 2 pages a day, how many days will it take to finish?', '41', '40', '40', '41', 'C'),
    (480, 'If a parrot lays an egg on a slate roof, which way does it roll?', 'Down', 'Left', 'It does not roll', 'Right', 'C'),
    (481, 'A doctor gives you 163 pills and says to take one every half hour. How long do the pills last?', '81 hours', '80 hours', '81 hours', '82 hours', 'A'),
    (482, 'A farmer has 101 sheep. All but 95 die. How many sheep are left?', '95 sheep', '94 sheep', '96 sheep', '101 sheep', 'A'),
    (483, 'How many times can you subtract 5 from 112?', 'twice', 'never', 'once', 'three times', 'C'),
    (484, 'If you have 93 oranges and take away 91, how many oranges do you have?', '0 oranges', '93 oranges', '90 oranges', '91 oranges', 'D'),
    (485, 'A room has 88 corners and a chair in each corner. How many chairs are there?', '89 chairs', '1 chair', '87 chairs', '88 chairs', 'D'),
    (486, 'How many letters are in the word Fludspad?', '10', '9', '7', '8', 'D'),
    (487, 'What time is 3 hours and 18 minutes after 9:02 am?', '12:05 pm', '12:20 pm', '1:20 pm', '12:35 pm', 'B'),
    (488, 'A train leaves at 12:39 am and travels for 4 hours. What time does it arrive?', '5:09 am', '5:39 am', '4:39 am', '4:09 am', 'C'),
    (489, 'If a book has 90 pages and you read 2 pages a day, how many days will it take to finish?', '46', '45', '46', '45', 'B'),
    (490, 'If a pheasant lays an egg on a tin roof, which way does it roll?', 'Left', 'Down', 'Right', 'It does not roll', 'D'),
    (491, 'A doctor gives you 183 pills and says to take one every half hour. How long do the pills last?', '91 hours', '91 hours', '90 hours', '92 hours', 'A'),
    (492, 'A farmer has 111 sheep. All but 105 die. How many sheep are left?', '106 sheep', '105 sheep', '104 sheep', '111 sheep', 'B'),
    (493, 'How many times can you subtract 5 from 122?', 'twice', 'once', 'three times', 'never', 'B'),
    (494, 'If you have 103 oranges and take away 101, how many oranges do you have?', '100 oranges', '103 oranges', '101 oranges', '0 oranges', 'C'),
    (495, 'A room has 98 corners and a chair in each corner. How many chairs are there?', '97 chairs', '99 chairs', '98 chairs', '1 chair', 'C'),
    (496, 'How many letters are in the word Spudflag?', '9', '7', '10', '8', 'D'),
    (497, 'What time is 1 hours and 48 minutes after 10:12 am?', '11:45 am', '12:15 pm', '1:00 pm', '12:00 pm', 'D'),
    (498, 'A train leaves at 3:29 am and travels for 4 hours. What time does it arrive?', '7:59 am', '8:29 am', '6:59 am', '7:29 am', 'D'),
    (499, 'If a book has 100 pages and you read 2 pages a day, how many days will it take to finish?', '51', '51', '50', '50', 'C'),
    (500, 'If a swan lays an egg on a thatched roof, which way does it roll?', 'Left', 'It does not roll', 'Down', 'Right', 'B');

INSERT INTO quiz_questions
    (owner_admin_id, question_text, option_a, option_b, option_c, option_d, correct_option, countdown_seconds, reveal_duration, active, created_at, updated_at)
SELECT
    @owner_admin_id,
    t.question_text,
    t.option_a,
    t.option_b,
    t.option_c,
    t.option_d,
    t.correct_option,
    @countdown_seconds,
    @reveal_duration,
    1,
    @created_at,
    @created_at
FROM tmp_logic_riddle_reasoning_questions_500 t
WHERE NOT EXISTS (
    SELECT 1
    FROM quiz_questions q
    WHERE q.owner_admin_id = @owner_admin_id
      AND q.question_text = t.question_text
);

DROP TEMPORARY TABLE tmp_logic_riddle_reasoning_questions_500;

COMMIT;
