USE cloud_signage_present;

START TRANSACTION;

SET @owner_admin_id := 1;
SET @countdown_seconds := 12;
SET @reveal_duration := 6;
SET @created_at := UTC_TIMESTAMP();

CREATE TEMPORARY TABLE tmp_film_tv_questions_200 (
    sort_order INT UNSIGNED NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option ENUM('A', 'B', 'C', 'D') NOT NULL
);

INSERT INTO tmp_film_tv_questions_200
    (sort_order, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
    (1, 'Who played Jack Dawson in Titanic?', 'Brad Pitt', 'Leonardo da Vinci', 'Leonardo DiCaprio', 'Matt Damon', 'C'),
    (2, 'Which TV series features the character Walter White?', 'Breaking Bad', 'Better Call Saul', 'Ozark', 'The Wire', 'A'),
    (3, 'What is the name of the wizarding school in Harry Potter?', 'Durmstrang', 'Beauxbatons', 'Hogwarts', 'Ilvermorny', 'C'),
    (4, 'Who directed Jurassic Park?', 'Steven Spielberg', 'James Cameron', 'Ridley Scott', 'George Lucas', 'A'),
    (5, 'Which actor played Iron Man in the Marvel Cinematic Universe?', 'Chris Evans', 'Mark Ruffalo', 'Robert Downey Jr.', 'Chris Hemsworth', 'C'),
    (6, 'What is the fictional continent in Game of Thrones called?', 'Westeros', 'Middle-earth', 'Narnia', 'Pandora', 'A'),
    (7, 'Which film won Best Picture at the Oscars for 1997 films?', 'Titanic', 'L.A. Confidential', 'Good Will Hunting', 'The Full Monty', 'A'),
    (8, 'Who played Rachel Green on Friends?', 'Courteney Cox', 'Jennifer Aniston', 'Lisa Kudrow', 'Julia Roberts', 'B'),
    (9, 'Which actor voiced Woody in Toy Story?', 'Tom Hanks', 'Tim Allen', 'Billy Crystal', 'Robin Williams', 'A'),
    (10, 'What is the name of Batman''s butler?', 'Alfred', 'Gordon', 'Lucius', 'Harvey', 'A'),
    (11, 'Which TV show is set in the paper company Dunder Mifflin?', 'Parks and Recreation', 'Brooklyn Nine-Nine', 'The Office', 'Superstore', 'C'),
    (12, 'Who directed E.T. the Extra-Terrestrial?', 'Steven Spielberg', 'Tim Burton', 'Ron Howard', 'Peter Jackson', 'A'),
    (13, 'Which actress played Hermione Granger in the Harry Potter films?', 'Emma Stone', 'Emma Watson', 'Keira Knightley', 'Natalie Portman', 'B'),
    (14, 'What is the name of the kingdom in Frozen?', 'Arendelle', 'Corona', 'Agrabah', 'Genovia', 'A'),
    (15, 'Which actor played Captain Jack Sparrow?', 'Orlando Bloom', 'Johnny Depp', 'Javier Bardem', 'Geoffrey Rush', 'B'),
    (16, 'Which TV series follows the Shelby crime family?', 'Peaky Blinders', 'Boardwalk Empire', 'Sons of Anarchy', 'Narcos', 'A'),
    (17, 'Who played Forrest Gump?', 'Tom Cruise', 'Tom Hanks', 'Kevin Costner', 'Robin Williams', 'B'),
    (18, 'Which film features the quote “I’ll be back”?', 'Predator', 'The Terminator', 'Commando', 'Total Recall', 'B'),
    (19, 'What is the name of the coffee shop in Friends?', 'Central Cafe', 'Coffee House', 'Central Perk', 'Bean Scene', 'C'),
    (20, 'Which actor played the Joker in The Dark Knight?', 'Joaquin Phoenix', 'Heath Ledger', 'Jack Nicholson', 'Jared Leto', 'B'),
    (21, 'Which TV series is about a high school chemistry teacher turned drug maker?', 'Ozark', 'Breaking Bad', 'Weeds', 'Narcos', 'B'),
    (22, 'Who directed The Lord of the Rings trilogy?', 'Peter Jackson', 'James Cameron', 'Guillermo del Toro', 'Ridley Scott', 'A'),
    (23, 'Which actress played Katniss Everdeen in The Hunger Games?', 'Shailene Woodley', 'Jennifer Lawrence', 'Kristen Stewart', 'Emma Stone', 'B'),
    (24, 'What is the subtitle of the second Star Wars film released in 1980?', 'A New Hope', 'Return of the Jedi', 'The Empire Strikes Back', 'The Phantom Menace', 'C'),
    (25, 'Which animated film features the song Let It Go?', 'Moana', 'Frozen', 'Tangled', 'Brave', 'B'),
    (26, 'Which TV show features the character Eleven?', 'Dark', 'The X-Files', 'Stranger Things', 'Lost', 'C'),
    (27, 'Who played Indiana Jones?', 'Harrison Ford', 'Mel Gibson', 'Bruce Willis', 'Tom Selleck', 'A'),
    (28, 'Which film won Best Picture at the Oscars for 2003 films?', 'Mystic River', 'The Lord of the Rings: The Return of the King', 'Lost in Translation', 'Master and Commander', 'B'),
    (29, 'What is the name of the clownfish in Finding Nemo?', 'Marlin', 'Dory', 'Nemo', 'Bruce', 'C'),
    (30, 'Which actor played Wolverine in the X-Men films?', 'Hugh Jackman', 'Patrick Stewart', 'Ryan Reynolds', 'Chris Pratt', 'A'),
    (31, 'Which TV comedy is set in the fictional town of Pawnee?', 'The Office', 'Parks and Recreation', 'Community', '30 Rock', 'B'),
    (32, 'Who directed Avatar?', 'James Cameron', 'Steven Spielberg', 'George Lucas', 'Ridley Scott', 'A'),
    (33, 'Which actress played Carrie Bradshaw in Sex and the City?', 'Kim Cattrall', 'Sarah Jessica Parker', 'Cynthia Nixon', 'Kristin Davis', 'B'),
    (34, 'What is the name of the hotel in The Shining?', 'Bates Motel', 'Overlook Hotel', 'Grand Budapest Hotel', 'Stanley Hotel', 'B'),
    (35, 'Which actor played Neo in The Matrix?', 'Keanu Reeves', 'Laurence Fishburne', 'Brad Pitt', 'Johnny Depp', 'A'),
    (36, 'Which TV series follows a dysfunctional family called the Bluths?', 'Succession', 'Shameless', 'Arrested Development', 'Modern Family', 'C'),
    (37, 'Who played the title role in Wonder Woman (2017)?', 'Gal Gadot', 'Brie Larson', 'Scarlett Johansson', 'Emily Blunt', 'A'),
    (38, 'Which film features a DeLorean time machine?', 'Back to the Future', 'Bill and Ted''s Excellent Adventure', 'Looper', 'The Time Machine', 'A'),
    (39, 'Which TV show features the phrase “Winter is coming”?', 'Vikings', 'The Witcher', 'Game of Thrones', 'House of the Dragon', 'C'),
    (40, 'Who directed Pulp Fiction?', 'Martin Scorsese', 'Quentin Tarantino', 'David Fincher', 'Guy Ritchie', 'B'),
    (41, 'Which actress voiced Elsa in Frozen?', 'Kristen Bell', 'Idina Menzel', 'Mandy Moore', 'Amy Adams', 'B'),
    (42, 'Which TV series features a group called the Hellfire Club?', 'Buffy the Vampire Slayer', 'Riverdale', 'Stranger Things', 'Wednesday', 'C'),
    (43, 'Who played Black Panther in the MCU?', 'Michael B. Jordan', 'Chadwick Boseman', 'Anthony Mackie', 'John Boyega', 'B'),
    (44, 'What is the name of the shark in Jaws?', 'Bruce', 'Finn', 'Jabber', 'Chomper', 'A'),
    (45, 'Which actor played Don Vito Corleone in The Godfather?', 'Al Pacino', 'Robert De Niro', 'Marlon Brando', 'James Caan', 'C'),
    (46, 'Which sitcom features the character Sheldon Cooper?', 'Friends', 'The Big Bang Theory', 'How I Met Your Mother', 'Seinfeld', 'B'),
    (47, 'Who directed The Grand Budapest Hotel?', 'Wes Anderson', 'Noah Baumbach', 'Edgar Wright', 'David O. Russell', 'A'),
    (48, 'Which actor played Spider-Man in the MCU first?', 'Tobey Maguire', 'Andrew Garfield', 'Tom Holland', 'Jake Gyllenhaal', 'C'),
    (49, 'Which TV series is set in Hawkins, Indiana?', 'Riverdale', 'Stranger Things', 'Twin Peaks', 'Smallville', 'B'),
    (50, 'Which animated film features a house lifted by balloons?', 'Up', 'Wall-E', 'Coco', 'Inside Out', 'A'),
    (51, 'Who played Elle Woods in Legally Blonde?', 'Cameron Diaz', 'Reese Witherspoon', 'Kate Hudson', 'Drew Barrymore', 'B'),
    (52, 'Which TV series follows the Roy family?', 'Billions', 'Succession', 'Dynasty', 'Empire', 'B'),
    (53, 'What is the name of Han Solo''s ship?', 'Star Destroyer', 'Serenity', 'Millennium Falcon', 'Razor Crest', 'C'),
    (54, 'Which actor played Deadpool?', 'Ryan Reynolds', 'Chris Evans', 'Paul Rudd', 'Chris Pratt', 'A'),
    (55, 'Which TV show features the Springfield family the Simpsons?', 'Family Guy', 'The Simpsons', 'Bob''s Burgers', 'Futurama', 'B'),
    (56, 'Who directed Jaws?', 'Steven Spielberg', 'George Lucas', 'Francis Ford Coppola', 'Brian De Palma', 'A'),
    (57, 'Which actress played Belle in the 2017 live-action Beauty and the Beast?', 'Emma Watson', 'Lily Collins', 'Anne Hathaway', 'Emma Stone', 'A'),
    (58, 'Which TV series follows a group of doctors at Seattle Grace Hospital?', 'House', 'Grey''s Anatomy', 'ER', 'Scrubs', 'B'),
    (59, 'Which actor played Maverick in Top Gun?', 'Tom Hanks', 'Tom Cruise', 'Val Kilmer', 'Kevin Bacon', 'B'),
    (60, 'What is the name of the toy cowboy in Toy Story?', 'Jessie', 'Bullseye', 'Woody', 'Buzz', 'C'),
    (61, 'Which TV series is about a serial killer who works for Miami Metro?', 'You', 'Dexter', 'Barry', 'Mindhunter', 'B'),
    (62, 'Who directed Inception?', 'Christopher Nolan', 'Denis Villeneuve', 'David Fincher', 'Ridley Scott', 'A'),
    (63, 'Which actress played Daenerys Targaryen in Game of Thrones?', 'Sophie Turner', 'Emilia Clarke', 'Lena Headey', 'Maisie Williams', 'B'),
    (64, 'Which film features the character Maximus Decimus Meridius?', 'Troy', 'Gladiator', 'Braveheart', 'Kingdom of Heaven', 'B'),
    (65, 'Which TV show features a paper company branch in Scranton?', 'The Office', 'Parks and Recreation', '30 Rock', 'Community', 'A'),
    (66, 'Who played the Genie in the 1992 animated Aladdin?', 'Robin Williams', 'Will Smith', 'Eddie Murphy', 'Billy Crystal', 'A'),
    (67, 'Which actor played Thor in the MCU?', 'Chris Evans', 'Chris Hemsworth', 'Tom Hiddleston', 'Sam Worthington', 'B'),
    (68, 'Which TV series features the character Saul Goodman?', 'Breaking Bad', 'Better Call Saul', 'Billions', 'Mad Men', 'B'),
    (69, 'Who directed The Dark Knight?', 'Christopher Nolan', 'Tim Burton', 'Zack Snyder', 'Matt Reeves', 'A'),
    (70, 'Which actress played Wednesday Addams in the Netflix series Wednesday?', 'Jenna Ortega', 'Emma Myers', 'Christina Ricci', 'Millie Bobby Brown', 'A'),
    (71, 'Which film series features Ethan Hunt?', 'Jason Bourne', 'Mission: Impossible', 'James Bond', 'Jack Ryan', 'B'),
    (72, 'Which TV sitcom features the Dunphy family?', 'Modern Family', 'Black-ish', 'Full House', 'Frasier', 'A'),
    (73, 'Who played Aragorn in The Lord of the Rings trilogy?', 'Orlando Bloom', 'Viggo Mortensen', 'Sean Bean', 'Hugo Weaving', 'B'),
    (74, 'Which film features a ship called the Black Pearl?', 'Pirates of the Caribbean', 'Master and Commander', 'Titanic', 'Hook', 'A'),
    (75, 'Which TV series is set in the world of Dunder Mifflin?', 'The Office', 'Superstore', 'Parks and Recreation', 'Abbott Elementary', 'A'),
    (76, 'Which actress played Princess Leia in Star Wars?', 'Carrie Fisher', 'Natalie Portman', 'Felicity Jones', 'Daisy Ridley', 'A'),
    (77, 'Who directed Schindler''s List?', 'Steven Spielberg', 'Roman Polanski', 'Martin Scorsese', 'Stanley Kubrick', 'A'),
    (78, 'Which TV series features the phrase “Suit up”?', 'Friends', 'How I Met Your Mother', 'New Girl', 'The Mindy Project', 'B'),
    (79, 'Which actor played The Dude in The Big Lebowski?', 'Jeff Bridges', 'John Goodman', 'Steve Buscemi', 'Philip Seymour Hoffman', 'A'),
    (80, 'What is the name of the dragon in Shrek?', 'Dragon', 'Fiona', 'Doris', 'Mushu', 'A'),
    (81, 'Which TV series features the Gallaghers?', 'Shameless', 'Succession', 'The Bear', 'Nurse Jackie', 'A'),
    (82, 'Who played the Joker in Joker (2019)?', 'Jared Leto', 'Heath Ledger', 'Joaquin Phoenix', 'Willem Dafoe', 'C'),
    (83, 'Which film features the quote “Why so serious?”', 'Joker', 'Batman Begins', 'The Dark Knight', 'Suicide Squad', 'C'),
    (84, 'Which TV series features agents Mulder and Scully?', 'Fringe', 'The X-Files', 'Lost', 'Supernatural', 'B'),
    (85, 'Who directed Fight Club?', 'David Fincher', 'Guy Ritchie', 'Danny Boyle', 'Brett Ratner', 'A'),
    (86, 'Which actress played Black Widow in the MCU?', 'Emily Blunt', 'Scarlett Johansson', 'Charlize Theron', 'Brie Larson', 'B'),
    (87, 'Which TV sitcom features the bar MacLaren''s Pub?', 'Friends', 'Cheers', 'How I Met Your Mother', 'New Girl', 'C'),
    (88, 'Which actor played Rocky Balboa?', 'Arnold Schwarzenegger', 'Sylvester Stallone', 'Jean-Claude Van Damme', 'Bruce Willis', 'B'),
    (89, 'What is the name of the shark hunter in Jaws?', 'Hooper', 'Quint', 'Brody', 'Chief', 'B'),
    (90, 'Which TV series is about a medieval fantasy family called the Targaryens in a prequel?', 'Game of Thrones', 'The Witcher', 'House of the Dragon', 'Merlin', 'C'),
    (91, 'Which actor played Gandalf in The Lord of the Rings films?', 'Ian McKellen', 'Patrick Stewart', 'Michael Gambon', 'Christopher Lee', 'A'),
    (92, 'Which film features a giant great white shark terrorizing Amity Island?', 'Deep Blue Sea', 'Jaws', 'The Meg', 'Open Water', 'B'),
    (93, 'Which TV show features the study group at Greendale?', 'Community', 'Scrubs', 'New Girl', 'The Good Place', 'A'),
    (94, 'Who directed The Shawshank Redemption?', 'Frank Darabont', 'Rob Reiner', 'Clint Eastwood', 'Ron Howard', 'A'),
    (95, 'Which actress played Monica Geller on Friends?', 'Jennifer Aniston', 'Lisa Kudrow', 'Courteney Cox', 'Maggie Wheeler', 'C'),
    (96, 'What is the subtitle of the first Avengers movie?', 'Infinity War', 'Assemble', 'It has no subtitle', 'Endgame', 'C'),
    (97, 'Which TV series features the character BoJack Horseman?', 'Big Mouth', 'BoJack Horseman', 'Rick and Morty', 'Tuca & Bertie', 'B'),
    (98, 'Who played James Bond in Skyfall?', 'Pierce Brosnan', 'Daniel Craig', 'Sean Connery', 'Roger Moore', 'B'),
    (99, 'Which animated film features the emotions Joy and Sadness?', 'Soul', 'Up', 'Inside Out', 'Turning Red', 'C'),
    (100, 'Which TV series follows the Pearson family across timelines?', 'This Is Us', 'Parenthood', 'A Million Little Things', 'Brothers & Sisters', 'A'),
    (101, 'Who directed The Silence of the Lambs?', 'Jonathan Demme', 'David Fincher', 'Ridley Scott', 'Michael Mann', 'A'),
    (102, 'Which actor played Loki in the MCU?', 'Tom Hiddleston', 'Benedict Cumberbatch', 'Tom Holland', 'Richard Madden', 'A'),
    (103, 'Which TV series features a chemistry teacher named Mr. White?', 'Breaking Bad', 'Fargo', 'Ozark', 'Narcos', 'A'),
    (104, 'Which film features the quote “Here''s Johnny!”', 'Psycho', 'The Shining', 'Misery', 'The Exorcist', 'B'),
    (105, 'Which actress played Mia Thermopolis in The Princess Diaries?', 'Anne Hathaway', 'Mandy Moore', 'Lindsay Lohan', 'Hilary Duff', 'A'),
    (106, 'Which TV series features the USS Enterprise?', 'Battlestar Galactica', 'The Orville', 'Star Trek', 'Firefly', 'C'),
    (107, 'Who played Captain America in the MCU?', 'Chris Evans', 'Sebastian Stan', 'Chris Pine', 'John Krasinski', 'A'),
    (108, 'Which film features the song My Heart Will Go On?', 'The Bodyguard', 'Titanic', 'Moulin Rouge!', 'Ghost', 'B'),
    (109, 'Which TV series features the hospital Sacred Heart?', 'Grey''s Anatomy', 'House', 'ER', 'Scrubs', 'D'),
    (110, 'Who directed The Social Network?', 'Aaron Sorkin', 'David Fincher', 'Danny Boyle', 'Spike Jonze', 'B'),
    (111, 'Which actor played Hagrid in the Harry Potter films?', 'Robbie Coltrane', 'Brendan Gleeson', 'Jim Broadbent', 'Ralph Fiennes', 'A'),
    (112, 'Which TV series features the character Villanelle?', 'Killing Eve', 'Homeland', 'Alias', 'Nikita', 'A'),
    (113, 'Which film features a hotel called the Continental?', 'Taken', 'The Equalizer', 'John Wick', 'Atomic Blonde', 'C'),
    (114, 'Who played Barbie in the 2023 film Barbie?', 'Margot Robbie', 'Emma Stone', 'Florence Pugh', 'Anya Taylor-Joy', 'A'),
    (115, 'Which TV series features the phrase “Live long and prosper”?', 'The Mandalorian', 'Star Trek', 'Doctor Who', 'The Expanse', 'B'),
    (116, 'Which actor played Obi-Wan Kenobi in the Star Wars prequels?', 'Liam Neeson', 'Ewan McGregor', 'Alec Guinness', 'Hayden Christensen', 'B'),
    (117, 'Which film features the Kingdom of Wakanda?', 'Black Panther', 'Thor: Ragnarok', 'Doctor Strange', 'Eternals', 'A'),
    (118, 'Which TV show features an island crash in the pilot episode?', 'Lost', 'Manifest', 'The Leftovers', 'From', 'A'),
    (119, 'Who directed The Departed?', 'Martin Scorsese', 'Steven Soderbergh', 'Michael Mann', 'Ridley Scott', 'A'),
    (120, 'Which actress played Meredith Grey?', 'Sandra Oh', 'Katherine Heigl', 'Ellen Pompeo', 'Kate Walsh', 'C'),
    (121, 'Which film features the quote “You can''t handle the truth!”', 'A Few Good Men', 'Top Gun', 'The Firm', 'Jerry Maguire', 'A'),
    (122, 'Which TV series features the Addams family daughter Wednesday?', 'Wednesday', 'Riverdale', 'The Chilling Adventures of Sabrina', 'Locke & Key', 'A'),
    (123, 'Who played Thor''s brother Loki?', 'Tom Hiddleston', 'Cillian Murphy', 'Jude Law', 'Matt Smith', 'A'),
    (124, 'Which film features a park filled with cloned dinosaurs?', 'King Kong', 'Jurassic Park', 'Godzilla', 'The Lost World', 'B'),
    (125, 'Which TV sitcom features the character Ross Geller?', 'Seinfeld', 'Friends', 'Frasier', 'Cheers', 'B'),
    (126, 'Who directed Goodfellas?', 'Francis Ford Coppola', 'Martin Scorsese', 'Brian De Palma', 'Oliver Stone', 'B'),
    (127, 'Which actress played Lara Croft in Lara Croft: Tomb Raider (2001)?', 'Charlize Theron', 'Angelina Jolie', 'Milla Jovovich', 'Kate Beckinsale', 'B'),
    (128, 'Which TV show features a zombie apocalypse led by Rick Grimes?', 'Fear the Walking Dead', 'The Walking Dead', 'The Last of Us', 'Z Nation', 'B'),
    (129, 'Which actor played Maximus in Gladiator?', 'Russell Crowe', 'Gerard Butler', 'Joaquin Phoenix', 'Colin Farrell', 'A'),
    (130, 'Which animated film features the Madrigal family?', 'Encanto', 'Coco', 'Moana', 'Luca', 'A'),
    (131, 'Which TV series features the “Red Wedding”?', 'The Witcher', 'Game of Thrones', 'Vikings', 'House of the Dragon', 'B'),
    (132, 'Who directed Alien?', 'Ridley Scott', 'James Cameron', 'John Carpenter', 'Paul Verhoeven', 'A'),
    (133, 'Which actor played Ron Weasley in Harry Potter?', 'Tom Felton', 'Rupert Grint', 'Daniel Radcliffe', 'Matthew Lewis', 'B'),
    (134, 'Which TV show features the Belcher family?', 'Family Guy', 'Bob''s Burgers', 'The Great North', 'American Dad!', 'B'),
    (135, 'Which film features a boxer named Apollo Creed?', 'Raging Bull', 'Rocky', 'Million Dollar Baby', 'Creed II', 'B'),
    (136, 'Which actress played Cersei Lannister?', 'Lena Headey', 'Emilia Clarke', 'Gwendoline Christie', 'Natalie Dormer', 'A'),
    (137, 'Who directed The Matrix?', 'The Wachowskis', 'James Cameron', 'Christopher Nolan', 'Alex Proyas', 'A'),
    (138, 'Which TV series follows a teacher named Ted Lasso coaching soccer?', 'Ted Lasso', 'Welcome to Wrexham', 'Shoresy', 'Trying', 'A'),
    (139, 'Which actor played Doctor Strange in the MCU?', 'Tom Hiddleston', 'Benedict Cumberbatch', 'Martin Freeman', 'Andrew Garfield', 'B'),
    (140, 'Which film features the quote “To infinity and beyond!”', 'Lightyear', 'Toy Story', 'Wall-E', 'Big Hero 6', 'B'),
    (141, 'Which TV show features the Tanner family?', 'Full House', 'Family Matters', 'Step by Step', 'The Wonder Years', 'A'),
    (142, 'Who directed The Godfather?', 'Martin Scorsese', 'Francis Ford Coppola', 'Brian De Palma', 'William Friedkin', 'B'),
    (143, 'Which actress played Sarah Connor in Terminator 2: Judgment Day?', 'Sigourney Weaver', 'Linda Hamilton', 'Jamie Lee Curtis', 'Geena Davis', 'B'),
    (144, 'Which TV show features the phrase “How you doin’?”', 'Seinfeld', 'Friends', 'Cheers', 'Frasier', 'B'),
    (145, 'Which film features a sinking ocean liner on its maiden voyage?', 'Poseidon', 'Titanic', 'A Night to Remember', 'The Perfect Storm', 'B'),
    (146, 'Which actor played R2-D2 in the original Star Wars trilogy?', 'Anthony Daniels', 'Kenny Baker', 'Peter Mayhew', 'Frank Oz', 'B'),
    (147, 'Which TV series follows a football team called AFC Richmond?', 'Ted Lasso', 'Dream Team', 'The Game', 'Friday Night Lights', 'A'),
    (148, 'Who directed Saving Private Ryan?', 'Steven Spielberg', 'Ridley Scott', 'Clint Eastwood', 'Oliver Stone', 'A'),
    (149, 'Which actor played Han Solo?', 'Mark Hamill', 'Harrison Ford', 'Alec Guinness', 'Bill Paxton', 'B'),
    (150, 'Which TV show features the hospital Princeton-Plainsboro?', 'ER', 'Grey''s Anatomy', 'House', 'Chicago Med', 'C'),
    (151, 'Which film features the quote “I see dead people”?', 'The Sixth Sense', 'The Others', 'Poltergeist', 'Ghost', 'A'),
    (152, 'Which actress played Princess Diana in The Crown seasons 5 and 6?', 'Emma Corrin', 'Claire Foy', 'Elizabeth Debicki', 'Olivia Colman', 'C'),
    (153, 'Who directed Blade Runner?', 'Ridley Scott', 'Denis Villeneuve', 'Paul Verhoeven', 'James Cameron', 'A'),
    (154, 'Which TV show features a science teacher named Mr. Feeny?', 'Saved by the Bell', 'Boy Meets World', 'Step by Step', 'Family Matters', 'B'),
    (155, 'Which actor played the T-800 in The Terminator?', 'Sylvester Stallone', 'Arnold Schwarzenegger', 'Jean-Claude Van Damme', 'Dolph Lundgren', 'B'),
    (156, 'Which animated film features a robot named Wall-E?', 'Big Hero 6', 'Wall-E', 'Robots', 'Treasure Planet', 'B'),
    (157, 'Which TV show features the character Omar Little?', 'The Wire', 'Breaking Bad', 'Oz', 'Power', 'A'),
    (158, 'Who directed Casino Royale (2006)?', 'Martin Campbell', 'Sam Mendes', 'Cary Fukunaga', 'Marc Forster', 'A'),
    (159, 'Which actress played Neytiri in Avatar?', 'Sigourney Weaver', 'Zoe Saldana', 'Michelle Rodriguez', 'Thandie Newton', 'B'),
    (160, 'Which TV show features the phrase “Save the cheerleader, save the world”?', 'Heroes', 'Smallville', 'Lost', 'Alias', 'A'),
    (161, 'Which actor played Shrek?', 'Mike Myers', 'Eddie Murphy', 'John Lithgow', 'Cameron Diaz', 'A'),
    (162, 'Which film features a boxer named Adonis Creed?', 'Creed', 'Southpaw', 'Rocky Balboa', 'Warrior', 'A'),
    (163, 'Which TV series follows teenagers in a town called Riverdale?', 'Riverdale', 'Dawson''s Creek', 'One Tree Hill', 'Gossip Girl', 'A'),
    (164, 'Who directed La La Land?', 'Damien Chazelle', 'Baz Luhrmann', 'Tom Hooper', 'Greta Gerwig', 'A'),
    (165, 'Which actress played Buffy in Buffy the Vampire Slayer?', 'Alyson Hannigan', 'Sarah Michelle Gellar', 'Charisma Carpenter', 'Eliza Dushku', 'B'),
    (166, 'Which film features the quote “You shall not pass!”', 'Harry Potter and the Philosopher''s Stone', 'The Lord of the Rings: The Fellowship of the Ring', 'The Hobbit', 'Willow', 'B'),
    (167, 'Which TV series features the prison Fox River?', 'Oz', 'Prison Break', 'Wentworth', 'Orange Is the New Black', 'B'),
    (168, 'Which actor played James Bond in GoldenEye?', 'Pierce Brosnan', 'Timothy Dalton', 'Sean Connery', 'Roger Moore', 'A'),
    (169, 'Which film features the family name Parr?', 'The Incredibles', 'Inside Out', 'Cars', 'Big Hero 6', 'A'),
    (170, 'Which TV show features a teacher named Mr. Schuester?', 'Glee', 'Smash', 'Fame', 'High School Musical: The Musical: The Series', 'A'),
    (171, 'Who directed Mad Max: Fury Road?', 'George Miller', 'James Wan', 'Peter Weir', 'Baz Luhrmann', 'A'),
    (172, 'Which actress played Regina George in Mean Girls?', 'Rachel McAdams', 'Amanda Seyfried', 'Lindsay Lohan', 'Lacey Chabert', 'A'),
    (173, 'Which TV series features a motel called the Rosebud Motel?', 'Schitt''s Creek', 'New Girl', 'The Good Place', 'Kim''s Convenience', 'A'),
    (174, 'Which film features a clown named Pennywise?', 'It', 'Saw', 'Sinister', 'Terrifier', 'A'),
    (175, 'Which actor played Buzz Lightyear in Toy Story?', 'Tom Hanks', 'Tim Allen', 'Don Rickles', 'John Ratzenberger', 'B'),
    (176, 'Which TV series features the phrase “XOXO, Gossip Girl”?', 'Pretty Little Liars', 'Gossip Girl', '90210', 'The O.C.', 'B'),
    (177, 'Who directed Whiplash?', 'Damien Chazelle', 'David Fincher', 'Denis Villeneuve', 'Edgar Wright', 'A'),
    (178, 'Which actress played Sabrina Spellman in Chilling Adventures of Sabrina?', 'Kiernan Shipka', 'Emma Roberts', 'Lucy Hale', 'Maia Mitchell', 'A'),
    (179, 'Which film features the quote “Just keep swimming”?', 'Finding Dory', 'Finding Nemo', 'Shark Tale', 'The Little Mermaid', 'B'),
    (180, 'Which TV show features detectives Jake Peralta and Amy Santiago?', 'Brooklyn Nine-Nine', 'Castle', 'The Rookie', 'Psych', 'A'),
    (181, 'Which actor played the Genie in the 2019 live-action Aladdin?', 'Will Smith', 'Jamie Foxx', 'Kevin Hart', 'Chris Rock', 'A'),
    (182, 'Which film features a character named Ferris Bueller?', 'Risky Business', 'Ferris Bueller''s Day Off', 'Pretty in Pink', 'The Breakfast Club', 'B'),
    (183, 'Which TV series features the phrase “Clear eyes, full hearts, can’t lose”?', 'Friday Night Lights', 'All American', 'One Tree Hill', 'Ted Lasso', 'A'),
    (184, 'Who directed Parasite?', 'Park Chan-wook', 'Bong Joon-ho', 'Kim Jee-woon', 'Lee Chang-dong', 'B'),
    (185, 'Which actress played Olivia Pope in Scandal?', 'Kerry Washington', 'Viola Davis', 'Taraji P. Henson', 'Angela Bassett', 'A'),
    (186, 'Which film features the quote “Hasta la vista, baby”?', 'The Terminator', 'Predator', 'Terminator 2: Judgment Day', 'True Lies', 'C'),
    (187, 'Which TV series features the phrase “Winterfell”?', 'Game of Thrones', 'The Witcher', 'Vikings', 'Merlin', 'A'),
    (188, 'Which actor played Caesar in the recent Planet of the Apes trilogy via performance capture?', 'Andy Serkis', 'Toby Kebbell', 'Woody Harrelson', 'Jason Clarke', 'A'),
    (189, 'Which film features a toy space ranger named Buzz Lightyear?', 'Toy Story', 'Small Soldiers', 'Lightyear', 'Cars', 'A'),
    (190, 'Which TV show features the family name Bridgerton?', 'The Crown', 'Bridgerton', 'Downton Abbey', 'Outlander', 'B'),
    (191, 'Who directed No Country for Old Men?', 'The Coen Brothers', 'Quentin Tarantino', 'Paul Thomas Anderson', 'David Fincher', 'A'),
    (192, 'Which actress played Phoebe Buffay on Friends?', 'Courteney Cox', 'Lisa Kudrow', 'Jennifer Aniston', 'Helen Baxendale', 'B'),
    (193, 'Which film features a villain named Hans Gruber?', 'Die Hard', 'Lethal Weapon', 'Speed', 'Face/Off', 'A'),
    (194, 'Which TV series features a football coach named Eric Taylor?', 'Ted Lasso', 'Friday Night Lights', 'All American', 'The Game', 'B'),
    (195, 'Which actor played the titular character in Edward Scissorhands?', 'Winona Ryder', 'Johnny Depp', 'Christian Slater', 'Tom Cruise', 'B'),
    (196, 'Which film features a wizard called Gandalf?', 'Harry Potter and the Goblet of Fire', 'The Lord of the Rings', 'Willow', 'The Chronicles of Narnia', 'B'),
    (197, 'Which TV show features the town Stars Hollow?', 'Gilmore Girls', 'Dawson''s Creek', 'Everwood', 'Hart of Dixie', 'A'),
    (198, 'Who directed The Wolf of Wall Street?', 'Martin Scorsese', 'Adam McKay', 'David O. Russell', 'Oliver Stone', 'A'),
    (199, 'Which actress played Nancy Wheeler in Stranger Things?', 'Sadie Sink', 'Natalia Dyer', 'Millie Bobby Brown', 'Maya Hawke', 'B'),
    (200, 'Which film features a character named Donkey voiced by Eddie Murphy?', 'Shrek', 'Mulan', 'The Princess and the Frog', 'Hercules', 'A');

INSERT INTO quiz_questions
    (owner_admin_id, question_text, option_a, option_b, option_c, option_d, correct_option, countdown_seconds, reveal_duration, active, created_at, updated_at)
SELECT
    @owner_admin_id,
    t.question_text,
    t.option_a,
    t.option_b,
    t.option_c,
    t.option_d,
    t.correct_option,
    @countdown_seconds,
    @reveal_duration,
    1,
    @created_at,
    @created_at
FROM tmp_film_tv_questions_200 t
WHERE NOT EXISTS (
    SELECT 1
    FROM quiz_questions q
    WHERE q.owner_admin_id = @owner_admin_id
      AND q.question_text = t.question_text
);

DROP TEMPORARY TABLE tmp_film_tv_questions_200;

COMMIT;
