USE cloud_signage_present;

START TRANSACTION;

SET @owner_admin_id := 1;
SET @countdown_seconds := 12;
SET @reveal_duration := 6;
SET @created_at := UTC_TIMESTAMP();

CREATE TEMPORARY TABLE tmp_general_knowledge_questions_200 (
    sort_order INT UNSIGNED NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option ENUM('A', 'B', 'C', 'D') NOT NULL
);

INSERT INTO tmp_general_knowledge_questions_200
    (sort_order, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
    (1, 'What is the capital of Hungary?', 'Budapest', 'Bucharest', 'Belgrade', 'Bratislava', 'A'),
    (2, 'Which instrument measures air pressure?', 'Thermometer', 'Barometer', 'Speedometer', 'Voltmeter', 'B'),
    (3, 'Who wrote The Great Gatsby?', 'F. Scott Fitzgerald', 'John Steinbeck', 'Ernest Hemingway', 'William Faulkner', 'A'),
    (4, 'Which planet is famous for having the hottest surface temperature?', 'Mercury', 'Venus', 'Mars', 'Jupiter', 'B'),
    (5, 'What is the capital of Finland?', 'Oslo', 'Stockholm', 'Helsinki', 'Reykjavik', 'C'),
    (6, 'How many hours are in two days?', '36', '42', '48', '60', 'C'),
    (7, 'Which country is home to the city of Krakow?', 'Poland', 'Czech Republic', 'Austria', 'Germany', 'A'),
    (8, 'What is the largest planet in our solar system?', 'Saturn', 'Jupiter', 'Neptune', 'Uranus', 'B'),
    (9, 'Who painted The Last Supper?', 'Leonardo da Vinci', 'Raphael', 'Michelangelo', 'Titian', 'A'),
    (10, 'What is the main gas found in the Sun?', 'Oxygen', 'Hydrogen', 'Nitrogen', 'Carbon dioxide', 'B'),
    (11, 'Which city is the capital of Denmark?', 'Copenhagen', 'Aarhus', 'Oslo', 'Malmo', 'A'),
    (12, 'How many sides does an octagon have?', 'Six', 'Seven', 'Eight', 'Nine', 'C'),
    (13, 'Which ocean is east of Africa?', 'Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Southern Ocean', 'B'),
    (14, 'Who is known for writing Hamlet?', 'William Shakespeare', 'Christopher Marlowe', 'Ben Jonson', 'John Milton', 'A'),
    (15, 'What is the capital of Chile?', 'Santiago', 'Lima', 'Bogota', 'Quito', 'A'),
    (16, 'Which animal is known for having a trunk?', 'Rhino', 'Elephant', 'Hippo', 'Tapir', 'B'),
    (17, 'What is 11 multiplied by 11?', '111', '121', '131', '141', 'B'),
    (18, 'Which country uses the krona as its currency?', 'Sweden', 'France', 'Spain', 'Italy', 'A'),
    (19, 'What is the longest river in the world by many traditional quiz standards?', 'Amazon', 'Yangtze', 'Mississippi', 'Nile', 'D'),
    (20, 'Which planet has the most moons currently known among common quiz answers?', 'Earth', 'Jupiter', 'Venus', 'Mercury', 'B'),
    (21, 'What is the capital of Vietnam?', 'Ho Chi Minh City', 'Bangkok', 'Hanoi', 'Phnom Penh', 'C'),
    (22, 'Which organ helps the body balance?', 'Eye', 'Ear', 'Liver', 'Pancreas', 'B'),
    (23, 'Who discovered America for Europe in 1492?', 'Christopher Columbus', 'Ferdinand Magellan', 'Vasco da Gama', 'James Cook', 'A'),
    (24, 'What is the freezing point of water in Fahrenheit?', '0', '16', '32', '64', 'C'),
    (25, 'Which country has the city of Prague?', 'Poland', 'Czech Republic', 'Slovakia', 'Slovenia', 'B'),
    (26, 'Which famous clock tower is in London?', 'Big Ben', 'Clock of the World', 'Royal Bell', 'Westminster Dial', 'A'),
    (27, 'What is the capital of Argentina?', 'Buenos Aires', 'Montevideo', 'Santiago', 'Cordoba', 'A'),
    (28, 'How many players are on a baseball team on the field?', '7', '8', '9', '10', 'C'),
    (29, 'Which scientist developed the polio vaccine?', 'Jonas Salk', 'Louis Pasteur', 'Edward Jenner', 'Alexander Fleming', 'A'),
    (30, 'What is the capital of Thailand?', 'Phuket', 'Bangkok', 'Chiang Mai', 'Hanoi', 'B'),
    (31, 'Which mountain range contains Mount Everest?', 'Andes', 'Rockies', 'Himalayas', 'Alps', 'C'),
    (32, 'What is the name of the Greek goddess of wisdom?', 'Hera', 'Athena', 'Artemis', 'Demeter', 'B'),
    (33, 'Which country has the city of Lisbon?', 'Spain', 'Portugal', 'Italy', 'Greece', 'B'),
    (34, 'How many cards are in a standard deck without jokers?', '48', '50', '52', '54', 'C'),
    (35, 'Which blood vessel carries blood away from the heart?', 'Vein', 'Artery', 'Capillary', 'Valve', 'B'),
    (36, 'What is the capital of Egypt?', 'Alexandria', 'Cairo', 'Giza', 'Luxor', 'B'),
    (37, 'Who wrote To Kill a Mockingbird?', 'Harper Lee', 'Toni Morrison', 'J.D. Salinger', 'Maya Angelou', 'A'),
    (38, 'Which country is home to the city of Zurich?', 'Austria', 'Switzerland', 'Germany', 'Belgium', 'B'),
    (39, 'What is the smallest country in the world?', 'Monaco', 'San Marino', 'Vatican City', 'Liechtenstein', 'C'),
    (40, 'Which element is essential for pencil lead?', 'Carbon', 'Graphite', 'Iron', 'Silicon', 'B'),
    (41, 'What is the capital of Peru?', 'Lima', 'Cusco', 'Quito', 'La Paz', 'A'),
    (42, 'Which planet is known for its blue appearance due to methane?', 'Neptune', 'Mars', 'Venus', 'Mercury', 'A'),
    (43, 'How many weeks are in a year?', '50', '51', '52', '53', 'C'),
    (44, 'Which country is famous for the city of Salzburg?', 'Austria', 'Germany', 'Switzerland', 'Hungary', 'A'),
    (45, 'What is the capital of Pakistan?', 'Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'C'),
    (46, 'Which famous scientist studied black holes and wrote A Brief History of Time?', 'Stephen Hawking', 'Carl Sagan', 'Richard Feynman', 'Max Planck', 'A'),
    (47, 'What is 144 divided by 12?', '10', '11', '12', '13', 'C'),
    (48, 'Which country has the city of Reykjavik?', 'Iceland', 'Norway', 'Finland', 'Greenland', 'A'),
    (49, 'What is the capital of South Africa in administrative terms?', 'Cape Town', 'Pretoria', 'Johannesburg', 'Durban', 'B'),
    (50, 'Which organ filters blood to make urine?', 'Heart', 'Kidney', 'Pancreas', 'Stomach', 'B'),
    (51, 'Who wrote Moby-Dick?', 'Herman Melville', 'Mark Twain', 'Nathaniel Hawthorne', 'Jack London', 'A'),
    (52, 'Which country is home to the city of Manila?', 'Malaysia', 'Philippines', 'Indonesia', 'Singapore', 'B'),
    (53, 'How many centimeters are in two meters?', '20', '200', '2000', '20000', 'B'),
    (54, 'What is the capital of Romania?', 'Sofia', 'Bucharest', 'Budapest', 'Belgrade', 'B'),
    (55, 'Which desert is located in Mongolia and northern China?', 'Sahara', 'Gobi', 'Atacama', 'Mojave', 'B'),
    (56, 'Which country has the city of Dublin?', 'Ireland', 'Scotland', 'Wales', 'Northern Ireland', 'A'),
    (57, 'What is the capital of Colombia?', 'Bogota', 'Medellin', 'Quito', 'Caracas', 'A'),
    (58, 'Which part of the body contains the ulna?', 'Leg', 'Arm', 'Spine', 'Foot', 'B'),
    (59, 'Who composed the Moonlight Sonata?', 'Mozart', 'Chopin', 'Beethoven', 'Schubert', 'C'),
    (60, 'Which country has the city of Nairobi?', 'Kenya', 'Tanzania', 'Uganda', 'Ethiopia', 'A'),
    (61, 'How many months are in a decade of years?', '100', '110', '120', '140', 'C'),
    (62, 'What is the capital of Venezuela?', 'Lima', 'Caracas', 'Bogota', 'Quito', 'B'),
    (63, 'Which gas is represented by the chemical formula O2?', 'Ozone', 'Oxygen', 'Hydrogen', 'Nitrogen', 'B'),
    (64, 'Which country is home to the city of Doha?', 'Qatar', 'Bahrain', 'Kuwait', 'Oman', 'A'),
    (65, 'What is the capital of Malaysia?', 'Kuala Lumpur', 'Jakarta', 'Manila', 'Singapore', 'A'),
    (66, 'Which sea creature has eight arms?', 'Squid', 'Octopus', 'Starfish', 'Jellyfish', 'B'),
    (67, 'Who wrote The Catcher in the Rye?', 'J.D. Salinger', 'John Updike', 'John Steinbeck', 'Kurt Vonnegut', 'A'),
    (68, 'Which country has the city of Brussels?', 'Belgium', 'Netherlands', 'Luxembourg', 'France', 'A'),
    (69, 'What is the capital of Bangladesh?', 'Dhaka', 'Chittagong', 'Kathmandu', 'Colombo', 'A'),
    (70, 'How many minutes are in a quarter of an hour?', '10', '12', '15', '20', 'C'),
    (71, 'Which country has the city of Lima?', 'Peru', 'Chile', 'Ecuador', 'Bolivia', 'A'),
    (72, 'What is the capital of Sri Lanka in common quiz usage?', 'Colombo', 'Kandy', 'Galle', 'Jaffna', 'A'),
    (73, 'Which ancient wonder was located in Babylon?', 'Colossus of Rhodes', 'Hanging Gardens', 'Temple of Artemis', 'Lighthouse of Alexandria', 'B'),
    (74, 'Which country has the city of Kampala?', 'Uganda', 'Kenya', 'Rwanda', 'Zambia', 'A'),
    (75, 'What is the capital of Ecuador?', 'Quito', 'Guayaquil', 'Lima', 'La Paz', 'A'),
    (76, 'Which instrument has valves and is made of brass?', 'Clarinet', 'Trumpet', 'Cello', 'Oboe', 'B'),
    (77, 'Who wrote War and Peace?', 'Leo Tolstoy', 'Fyodor Dostoevsky', 'Anton Chekhov', 'Ivan Turgenev', 'A'),
    (78, 'Which country has the city of Havana?', 'Cuba', 'Dominican Republic', 'Jamaica', 'Mexico', 'A'),
    (79, 'What is the capital of Greece?', 'Athens', 'Sparta', 'Thessaloniki', 'Corinth', 'A'),
    (80, 'How many legs does an insect have?', '4', '6', '8', '10', 'B'),
    (81, 'Which country has the city of Oslo?', 'Norway', 'Sweden', 'Finland', 'Denmark', 'A'),
    (82, 'What is the capital of Indonesia?', 'Bali', 'Jakarta', 'Bandung', 'Surabaya', 'B'),
    (83, 'Which scientist is famous for the three laws of planetary motion?', 'Kepler', 'Newton', 'Galileo', 'Copernicus', 'A'),
    (84, 'Which country has the city of Beirut?', 'Jordan', 'Lebanon', 'Syria', 'Cyprus', 'B'),
    (85, 'What is the capital of Cuba?', 'Havana', 'Santiago de Cuba', 'Kingston', 'San Juan', 'A'),
    (86, 'Which continent is Madagascar near?', 'Asia', 'Europe', 'Africa', 'Australia', 'C'),
    (87, 'Which country has the city of Amman?', 'Jordan', 'Egypt', 'Israel', 'Iraq', 'A'),
    (88, 'What is the capital of Croatia?', 'Zagreb', 'Split', 'Dubrovnik', 'Ljubljana', 'A'),
    (89, 'Which famous female scientist worked on X-ray crystallography and DNA structure?', 'Marie Curie', 'Rosalind Franklin', 'Ada Lovelace', 'Rachel Carson', 'B'),
    (90, 'Which country has the city of Casablanca?', 'Morocco', 'Tunisia', 'Algeria', 'Libya', 'A'),
    (91, 'What is the capital of Serbia?', 'Belgrade', 'Sarajevo', 'Skopje', 'Sofia', 'A'),
    (92, 'How many zeros are in one million?', '5', '6', '7', '8', 'B'),
    (93, 'Which country has the city of Tallinn?', 'Latvia', 'Lithuania', 'Estonia', 'Finland', 'C'),
    (94, 'What is the capital of Slovakia?', 'Bratislava', 'Prague', 'Budapest', 'Ljubljana', 'A'),
    (95, 'Which branch of science studies living organisms?', 'Geology', 'Biology', 'Physics', 'Astronomy', 'B'),
    (96, 'Which country has the city of Riga?', 'Latvia', 'Estonia', 'Lithuania', 'Belarus', 'A'),
    (97, 'What is the capital of Slovenia?', 'Ljubljana', 'Zagreb', 'Brno', 'Sarajevo', 'A'),
    (98, 'Which planet is second from the Sun?', 'Mercury', 'Venus', 'Earth', 'Mars', 'B'),
    (99, 'Which country has the city of Vilnius?', 'Latvia', 'Estonia', 'Lithuania', 'Poland', 'C'),
    (100, 'What is the capital of Bolivia in many quiz contexts?', 'La Paz', 'Sucre', 'Santa Cruz', 'Cochabamba', 'A'),
    (101, 'Which country has the city of Muscat?', 'Oman', 'Yemen', 'Qatar', 'UAE', 'A'),
    (102, 'What is the capital of Nepal?', 'Thimphu', 'Kathmandu', 'Dhaka', 'Colombo', 'B'),
    (103, 'Which famous explorer reached India by sea from Europe via the Cape route?', 'Magellan', 'Vasco da Gama', 'Cook', 'Drake', 'B'),
    (104, 'Which country has the city of Tbilisi?', 'Georgia', 'Armenia', 'Azerbaijan', 'Kazakhstan', 'A'),
    (105, 'What is the capital of Ghana?', 'Accra', 'Lagos', 'Abuja', 'Kumasi', 'A'),
    (106, 'How many days are there in April?', '29', '30', '31', '28', 'B'),
    (107, 'Which country has the city of Baku?', 'Armenia', 'Georgia', 'Azerbaijan', 'Turkey', 'C'),
    (108, 'What is the capital of Nigeria?', 'Lagos', 'Abuja', 'Kano', 'Accra', 'B'),
    (109, 'Which metal is the primary component of steel?', 'Iron', 'Copper', 'Zinc', 'Lead', 'A'),
    (110, 'Which country has the city of Yerevan?', 'Georgia', 'Azerbaijan', 'Armenia', 'Iran', 'C'),
    (111, 'What is the capital of Ethiopia?', 'Addis Ababa', 'Nairobi', 'Kampala', 'Asmara', 'A'),
    (112, 'Which famous structure was built as a tomb by Emperor Shah Jahan?', 'Red Fort', 'Taj Mahal', 'Qutub Minar', 'Hawa Mahal', 'B'),
    (113, 'Which country has the city of Algiers?', 'Morocco', 'Algeria', 'Tunisia', 'Libya', 'B'),
    (114, 'What is the capital of Zimbabwe?', 'Harare', 'Lusaka', 'Maputo', 'Gaborone', 'A'),
    (115, 'Which body part contains the patella?', 'Arm', 'Knee', 'Shoulder', 'Ankle', 'B'),
    (116, 'Which country has the city of Tunis?', 'Tunisia', 'Algeria', 'Morocco', 'Libya', 'A'),
    (117, 'What is the capital of Tanzania?', 'Dar es Salaam', 'Dodoma', 'Arusha', 'Mombasa', 'B'),
    (118, 'Which animal is famous for changing color to blend in?', 'Iguana', 'Chameleon', 'Koala', 'Meerkat', 'B'),
    (119, 'Which country has the city of Tripoli?', 'Tunisia', 'Libya', 'Egypt', 'Sudan', 'B'),
    (120, 'What is the capital of Zambia?', 'Lusaka', 'Harare', 'Lilongwe', 'Windhoek', 'A'),
    (121, 'Who wrote The Adventures of Tom Sawyer?', 'Mark Twain', 'Jack London', 'Jules Verne', 'Charles Dickens', 'A'),
    (122, 'Which country has the city of Windhoek?', 'Namibia', 'Botswana', 'South Africa', 'Angola', 'A'),
    (123, 'What is the capital of Uganda?', 'Kampala', 'Kigali', 'Nairobi', 'Dodoma', 'A'),
    (124, 'How many continents cross the equator?', '2', '3', '4', '5', 'B'),
    (125, 'Which country has the city of Gaborone?', 'Botswana', 'Namibia', 'Lesotho', 'Eswatini', 'A'),
    (126, 'What is the capital of Namibia?', 'Windhoek', 'Lusaka', 'Gaborone', 'Maputo', 'A'),
    (127, 'Which scientist proposed the heliocentric model before Galileo supported it?', 'Copernicus', 'Newton', 'Einstein', 'Faraday', 'A'),
    (128, 'Which country has the city of Kigali?', 'Rwanda', 'Burundi', 'Uganda', 'Kenya', 'A'),
    (129, 'What is the capital of Rwanda?', 'Kigali', 'Bujumbura', 'Kampala', 'Nairobi', 'A'),
    (130, 'Which country has the city of Dakar?', 'Senegal', 'Mali', 'Niger', 'Ghana', 'A'),
    (131, 'What is the capital of Senegal?', 'Dakar', 'Accra', 'Lome', 'Bamako', 'A'),
    (132, 'What is the name of the longest day of the year in the northern hemisphere?', 'Equinox', 'Solstice', 'Perihelion', 'Zenith', 'B'),
    (133, 'Which country has the city of Bamako?', 'Mali', 'Niger', 'Chad', 'Benin', 'A'),
    (134, 'What is the capital of Mali?', 'Bamako', 'Niamey', 'Ouagadougou', 'Dakar', 'A'),
    (135, 'Which organ produces insulin?', 'Liver', 'Kidney', 'Pancreas', 'Spleen', 'C'),
    (136, 'Which country has the city of Niamey?', 'Chad', 'Mali', 'Niger', 'Togo', 'C'),
    (137, 'What is the capital of Niger?', 'Niamey', 'Bamako', 'Nairobi', 'Lome', 'A'),
    (138, 'Which country has the city of Lome?', 'Togo', 'Benin', 'Ghana', 'Ivory Coast', 'A'),
    (139, 'What is the capital of Togo?', 'Lome', 'Accra', 'Porto-Novo', 'Abidjan', 'A'),
    (140, 'Which famous artist painted Guernica?', 'Picasso', 'Dali', 'Miro', 'Goya', 'A'),
    (141, 'Which country has the city of Porto-Novo?', 'Benin', 'Togo', 'Ghana', 'Cameroon', 'A'),
    (142, 'What is the capital of Benin?', 'Cotonou', 'Porto-Novo', 'Lome', 'Libreville', 'B'),
    (143, 'Which country has the city of Libreville?', 'Gabon', 'Congo', 'Cameroon', 'Benin', 'A'),
    (144, 'What is the capital of Gabon?', 'Libreville', 'Kinshasa', 'Brazzaville', 'Yaounde', 'A'),
    (145, 'Which country has the city of Yaounde?', 'Cameroon', 'Gabon', 'Angola', 'Sudan', 'A'),
    (146, 'What is the capital of Cameroon?', 'Yaounde', 'Douala', 'Lusaka', 'Kigali', 'A'),
    (147, 'Which sea lies between Saudi Arabia and northeast Africa?', 'Arabian Sea', 'Caspian Sea', 'Red Sea', 'Black Sea', 'C'),
    (148, 'Which country has the city of Luanda?', 'Mozambique', 'Angola', 'Namibia', 'Zimbabwe', 'B'),
    (149, 'What is the capital of Angola?', 'Luanda', 'Maputo', 'Harare', 'Lusaka', 'A'),
    (150, 'Which country has the city of Maputo?', 'Angola', 'Mozambique', 'Botswana', 'Namibia', 'B'),
    (151, 'What is the capital of Mozambique?', 'Maputo', 'Lusaka', 'Harare', 'Lilongwe', 'A'),
    (152, 'How many letters are in the English alphabet?', '24', '25', '26', '27', 'C'),
    (153, 'Which country has the city of Lilongwe?', 'Malawi', 'Zambia', 'Zimbabwe', 'Kenya', 'A'),
    (154, 'What is the capital of Malawi?', 'Lilongwe', 'Blantyre', 'Lusaka', 'Maputo', 'A'),
    (155, 'Which country has the city of Bujumbura?', 'Burundi', 'Rwanda', 'Uganda', 'Tanzania', 'A'),
    (156, 'What is the capital of Burundi?', 'Gitega', 'Bujumbura', 'Kigali', 'Dodoma', 'A'),
    (157, 'Which famous ship did Ferdinand Magellan begin his circumnavigation voyage with?', 'Santa Maria', 'Trinidad', 'Victory', 'Mayflower', 'B'),
    (158, 'Which country has the city of Asmara?', 'Eritrea', 'Ethiopia', 'Somalia', 'Sudan', 'A'),
    (159, 'What is the capital of Eritrea?', 'Asmara', 'Addis Ababa', 'Khartoum', 'Mogadishu', 'A'),
    (160, 'Which country has the city of Mogadishu?', 'Somalia', 'Sudan', 'Eritrea', 'Djibouti', 'A'),
    (161, 'What is the capital of Somalia?', 'Mogadishu', 'Hargeisa', 'Asmara', 'Nairobi', 'A'),
    (162, 'Which planet is farthest from the Sun among the eight planets?', 'Saturn', 'Uranus', 'Neptune', 'Jupiter', 'C'),
    (163, 'Which country has the city of Khartoum?', 'South Sudan', 'Sudan', 'Ethiopia', 'Chad', 'B'),
    (164, 'What is the capital of Sudan?', 'Khartoum', 'Juba', 'Cairo', 'Asmara', 'A'),
    (165, 'Which country has the city of Juba?', 'Sudan', 'South Sudan', 'Uganda', 'Kenya', 'B'),
    (166, 'What is the capital of South Sudan?', 'Juba', 'Khartoum', 'Kampala', 'Addis Ababa', 'A'),
    (167, 'Which instrument is used for looking at stars and planets?', 'Microscope', 'Telescope', 'Periscope', 'Stethoscope', 'B'),
    (168, 'Which country has the city of Nouakchott?', 'Mauritania', 'Morocco', 'Mali', 'Algeria', 'A'),
    (169, 'What is the capital of Mauritania?', 'Nouakchott', 'Rabat', 'Dakar', 'Bamako', 'A'),
    (170, 'Which country has the city of Rabat?', 'Morocco', 'Tunisia', 'Algeria', 'Jordan', 'A'),
    (171, 'What is the capital of Morocco?', 'Rabat', 'Casablanca', 'Marrakech', 'Fez', 'A'),
    (172, 'Which famous author created Winnie-the-Pooh?', 'Beatrix Potter', 'A.A. Milne', 'Roald Dahl', 'Kenneth Grahame', 'B'),
    (173, 'Which country has the city of Valletta?', 'Cyprus', 'Malta', 'Italy', 'Greece', 'B'),
    (174, 'What is the capital of Malta?', 'Valletta', 'Nicosia', 'Athens', 'Naples', 'A'),
    (175, 'Which country has the city of Nicosia?', 'Cyprus', 'Malta', 'Greece', 'Turkey', 'A'),
    (176, 'What is the capital of Cyprus?', 'Nicosia', 'Limassol', 'Valletta', 'Larnaca', 'A'),
    (177, 'Which scientist is associated with the laws of inheritance and pea plants?', 'Darwin', 'Mendel', 'Pasteur', 'Bohr', 'B'),
    (178, 'Which country has the city of Minsk?', 'Ukraine', 'Belarus', 'Poland', 'Lithuania', 'B'),
    (179, 'What is the capital of Belarus?', 'Minsk', 'Kiev', 'Warsaw', 'Riga', 'A'),
    (180, 'Which country has the city of Chisinau?', 'Romania', 'Moldova', 'Belarus', 'Ukraine', 'B'),
    (181, 'What is the capital of Moldova?', 'Chisinau', 'Bucharest', 'Sofia', 'Kyiv', 'A'),
    (182, 'How many days are in February during a leap year?', '27', '28', '29', '30', 'C'),
    (183, 'Which country has the city of Sarajevo?', 'Croatia', 'Bosnia and Herzegovina', 'Serbia', 'Montenegro', 'B'),
    (184, 'What is the capital of Bosnia and Herzegovina?', 'Sarajevo', 'Belgrade', 'Skopje', 'Podgorica', 'A'),
    (185, 'Which country has the city of Skopje?', 'North Macedonia', 'Albania', 'Kosovo', 'Serbia', 'A'),
    (186, 'What is the capital of North Macedonia?', 'Skopje', 'Sofia', 'Tirana', 'Pristina', 'A'),
    (187, 'Which country has the city of Tirana?', 'North Macedonia', 'Albania', 'Montenegro', 'Kosovo', 'B'),
    (188, 'What is the capital of Albania?', 'Tirana', 'Skopje', 'Pristina', 'Podgorica', 'A'),
    (189, 'Which country has the city of Podgorica?', 'Serbia', 'Montenegro', 'Albania', 'Croatia', 'B'),
    (190, 'What is the capital of Montenegro?', 'Podgorica', 'Sarajevo', 'Belgrade', 'Tirana', 'A'),
    (191, 'Which country has the city of Pristina?', 'Albania', 'Kosovo', 'Serbia', 'Croatia', 'B'),
    (192, 'What is the capital of Kosovo?', 'Pristina', 'Podgorica', 'Skopje', 'Tirana', 'A'),
    (193, 'Which organ helps oxygenate blood?', 'Stomach', 'Lungs', 'Liver', 'Pancreas', 'B'),
    (194, 'Which country has the city of Luxembourg?', 'Belgium', 'Luxembourg', 'Netherlands', 'France', 'B'),
    (195, 'What is the capital of Luxembourg?', 'Luxembourg', 'Brussels', 'Amsterdam', 'Liege', 'A'),
    (196, 'Which country has the city of Andorra la Vella?', 'Spain', 'Andorra', 'Portugal', 'France', 'B'),
    (197, 'What is the capital of Andorra?', 'Andorra la Vella', 'Barcelona', 'Madrid', 'Lisbon', 'A'),
    (198, 'Which famous composer became deaf later in life?', 'Mozart', 'Beethoven', 'Bach', 'Vivaldi', 'B'),
    (199, 'Which country has the city of San Marino?', 'Italy', 'San Marino', 'Vatican City', 'Malta', 'B'),
    (200, 'What is the capital of San Marino?', 'San Marino', 'Valletta', 'Rome', 'Andorra la Vella', 'A');

INSERT INTO quiz_questions
    (owner_admin_id, question_text, option_a, option_b, option_c, option_d, correct_option, countdown_seconds, reveal_duration, active, created_at, updated_at)
SELECT
    @owner_admin_id,
    t.question_text,
    t.option_a,
    t.option_b,
    t.option_c,
    t.option_d,
    t.correct_option,
    @countdown_seconds,
    @reveal_duration,
    1,
    @created_at,
    @created_at
FROM tmp_general_knowledge_questions_200 t
WHERE NOT EXISTS (
    SELECT 1
    FROM quiz_questions q
    WHERE q.owner_admin_id = @owner_admin_id
      AND q.question_text = t.question_text
);

DROP TEMPORARY TABLE tmp_general_knowledge_questions_200;

COMMIT;
