USE cloud_signage_present;

START TRANSACTION;

SET @owner_admin_id := 1;
SET @countdown_seconds := 12;
SET @reveal_duration := 6;
SET @created_at := UTC_TIMESTAMP();

CREATE TEMPORARY TABLE tmp_sports_knowledge_questions_200 (
    sort_order INT UNSIGNED NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option ENUM('A', 'B', 'C', 'D') NOT NULL
);

INSERT INTO tmp_sports_knowledge_questions_200
    (sort_order, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
    (1, 'How many players from one team are on the court in basketball at a time?', '4', '5', '6', '7', 'B'),
    (2, 'In soccer, how many points is a win worth in most league systems?', '1', '2', '3', '4', 'C'),
    (3, 'Which country won the FIFA World Cup in 2018?', 'Germany', 'Argentina', 'France', 'Brazil', 'C'),
    (4, 'How many innings are there in a standard professional baseball game?', '7', '8', '9', '10', 'C'),
    (5, 'In tennis, what score comes after 30?', '35', '40', '45', '50', 'B'),
    (6, 'Which sport uses the terms birdie and eagle?', 'Tennis', 'Baseball', 'Golf', 'Cricket', 'C'),
    (7, 'How many players are on the field for one team in American football during a play?', '10', '11', '12', '9', 'B'),
    (8, 'Which country hosted the 2016 Summer Olympics?', 'China', 'Brazil', 'United Kingdom', 'Japan', 'B'),
    (9, 'In volleyball, how many players are on court for one team?', '5', '6', '7', '8', 'B'),
    (10, 'What color card means a player is sent off in soccer?', 'Blue', 'Yellow', 'Black', 'Red', 'D'),
    (11, 'Which sport features the Stanley Cup?', 'Baseball', 'Ice hockey', 'Basketball', 'Lacrosse', 'B'),
    (12, 'How many holes are played in a standard full round of golf?', '9', '12', '18', '24', 'C'),
    (13, 'Which athlete is known as Lightning Bolt?', 'Carl Lewis', 'Usain Bolt', 'Yohan Blake', 'Noah Lyles', 'B'),
    (14, 'In cricket, how many stumps make up one wicket?', '2', '3', '4', '5', 'B'),
    (15, 'Which country won the Cricket World Cup in 2019?', 'India', 'Australia', 'England', 'New Zealand', 'C'),
    (16, 'In baseball, how many strikes usually make an out?', '2', '3', '4', '5', 'B'),
    (17, 'Which sport uses a pommel horse?', 'Wrestling', 'Gymnastics', 'Fencing', 'Diving', 'B'),
    (18, 'How many points is a touchdown worth in American football before the extra-point attempt?', '3', '5', '6', '7', 'C'),
    (19, 'Which country has won the most men''s FIFA World Cups?', 'Germany', 'Italy', 'Argentina', 'Brazil', 'D'),
    (20, 'In tennis, what is the term for a score of zero?', 'Nil', 'Love', 'Blank', 'Duck', 'B'),
    (21, 'Which sport is associated with Wimbledon?', 'Cricket', 'Rugby', 'Tennis', 'Polo', 'C'),
    (22, 'How many players are on the ice for one hockey team during normal play, including the goalie?', '5', '6', '7', '8', 'B'),
    (23, 'Which golfer has won the most major championships in men''s golf?', 'Arnold Palmer', 'Tiger Woods', 'Jack Nicklaus', 'Gary Player', 'C'),
    (24, 'In boxing, what does TKO stand for?', 'Technical Knockout', 'Timed Knockout', 'Total Knockout', 'Triple Knockout', 'A'),
    (25, 'Which country won the UEFA Euro 2020 tournament, played in 2021?', 'England', 'Spain', 'Italy', 'France', 'C'),
    (26, 'How many sets must a team usually win to claim an indoor volleyball match best-of-five?', '2', '3', '4', '5', 'B'),
    (27, 'What is the national sport of Japan?', 'Judo', 'Karate', 'Baseball', 'Sumo', 'D'),
    (28, 'Which NBA team plays its home games at Madison Square Garden?', 'Brooklyn Nets', 'Chicago Bulls', 'New York Knicks', 'Boston Celtics', 'C'),
    (29, 'In Formula 1, what flag indicates the race has ended?', 'Yellow', 'Black', 'Red', 'Checkered', 'D'),
    (30, 'How many players are on a standard soccer team on the field, including the goalkeeper?', '10', '11', '12', '9', 'B'),
    (31, 'Which country won the Women''s FIFA World Cup in 2019?', 'England', 'United States', 'Netherlands', 'Germany', 'B'),
    (32, 'In baseball, what is it called when a batter circles all bases on one hit?', 'Grand slam', 'Triple play', 'Home run', 'Double', 'C'),
    (33, 'Which sport uses a shuttlecock?', 'Squash', 'Tennis', 'Badminton', 'Table tennis', 'C'),
    (34, 'How many points is a safety worth in American football?', '1', '2', '3', '6', 'B'),
    (35, 'Which tennis tournament is played on a clay surface?', 'Wimbledon', 'US Open', 'Australian Open', 'French Open', 'D'),
    (36, 'In snooker, which ball is worth the most points?', 'Blue', 'Pink', 'Black', 'Green', 'C'),
    (37, 'Which country hosted the 2022 FIFA World Cup?', 'Russia', 'Qatar', 'United Arab Emirates', 'Saudi Arabia', 'B'),
    (38, 'How long is a standard marathon race?', '26.2 miles', '24.2 miles', '25 miles', '30 miles', 'A'),
    (39, 'In rugby union, how many points is a try worth?', '3', '4', '5', '6', 'C'),
    (40, 'Which athlete won eight gold medals at the 2008 Beijing Olympics?', 'Usain Bolt', 'Michael Phelps', 'Ryan Lochte', 'Mark Spitz', 'B'),
    (41, 'Which sport awards the Davis Cup?', 'Golf', 'Tennis', 'Cricket', 'Rugby', 'B'),
    (42, 'In baseball, which defensive player usually calls pitches with hand signals?', 'Pitcher', 'Catcher', 'Shortstop', 'First baseman', 'B'),
    (43, 'Which country won the Rugby World Cup in 2023?', 'New Zealand', 'South Africa', 'England', 'France', 'B'),
    (44, 'How many minutes are in a standard soccer match before stoppage time?', '80', '85', '90', '100', 'C'),
    (45, 'Which sport uses the term scrum?', 'Field hockey', 'Rugby', 'Lacrosse', 'Polo', 'B'),
    (46, 'In basketball, how many points is a free throw worth?', '1', '2', '3', '4', 'A'),
    (47, 'Which country has won the most Olympic gold medals in men''s basketball?', 'Spain', 'Soviet Union', 'United States', 'Argentina', 'C'),
    (48, 'In cricket, what is the maximum number of runs scored from one legal delivery without overthrows?', '4', '5', '6', '7', 'C'),
    (49, 'Which race is known as the Run for the Roses?', 'Belmont Stakes', 'Kentucky Derby', 'Preakness Stakes', 'Breeders'' Cup Classic', 'B'),
    (50, 'What is the diameter of a basketball hoop in inches?', '16', '18', '20', '22', 'B'),
    (51, 'Which sport features the Tour de France?', 'Motor racing', 'Cycling', 'Rowing', 'Triathlon', 'B'),
    (52, 'In tennis, what is the term for winning a game without losing a point?', 'Shutout game', 'Perfect game', 'Love game', 'Clean game', 'C'),
    (53, 'Which NFL team won Super Bowl LVIII played in February 2024?', 'San Francisco 49ers', 'Kansas City Chiefs', 'Philadelphia Eagles', 'Baltimore Ravens', 'B'),
    (54, 'How many bases are there on a baseball field?', '3', '4', '5', '6', 'B'),
    (55, 'Which sport uses a vaulting table?', 'Gymnastics', 'Weightlifting', 'Wrestling', 'Fencing', 'A'),
    (56, 'Which country won the men''s UEFA European Championship in 2016?', 'Portugal', 'France', 'Germany', 'Spain', 'A'),
    (57, 'In table tennis, what is another common name for the sport?', 'Whiff-whiff', 'Ping-pong', 'Paddleball', 'Mini tennis', 'B'),
    (58, 'How many rounds are there in a professional heavyweight title boxing bout?', '10', '11', '12', '15', 'C'),
    (59, 'Which team won the 2023-24 English Premier League title?', 'Arsenal', 'Liverpool', 'Manchester City', 'Aston Villa', 'C'),
    (60, 'In American football, how many points is a field goal worth?', '2', '3', '4', '5', 'B'),
    (61, 'Which athlete has won the most Olympic medals overall?', 'Larisa Latynina', 'Michael Phelps', 'Paavo Nurmi', 'Mark Spitz', 'B'),
    (62, 'Which sport features the Ashes?', 'Rugby', 'Cricket', 'Baseball', 'Tennis', 'B'),
    (63, 'In soccer, what body part can the goalkeeper use inside their penalty area that other players usually cannot?', 'Head', 'Shoulder', 'Hand', 'Knee', 'C'),
    (64, 'Which country hosted the 2023 Rugby World Cup?', 'England', 'France', 'South Africa', 'Australia', 'B'),
    (65, 'In basketball, how many players are on an NBA roster on game day at most in the active lineup?', '12', '13', '15', '18', 'B'),
    (66, 'Which sport uses the term albatross for a rare scoring achievement?', 'Cricket', 'Golf', 'Tennis', 'Skiing', 'B'),
    (67, 'Which nation won the men''s hockey gold medal at the Tokyo 2020 Olympics held in 2021?', 'Germany', 'Belgium', 'Australia', 'India', 'B'),
    (68, 'What is the maximum break in snooker?', '147', '155', '167', '180', 'A'),
    (69, 'Which sport features a balance beam?', 'Gymnastics', 'Figure skating', 'Diving', 'Surfing', 'A'),
    (70, 'In baseball, what is the term for three outs that end a team''s turn at bat?', 'Quarter', 'Frame', 'Inning half', 'Set', 'C'),
    (71, 'Which country won the Copa America in 2021?', 'Brazil', 'Argentina', 'Uruguay', 'Chile', 'B'),
    (72, 'In ice hockey, how many periods are played in regulation time?', '2', '3', '4', '5', 'B'),
    (73, 'Which track-and-field event combines pole vault, javelin, and 8 other disciplines for men?', 'Decathlon', 'Heptathlon', 'Pentathlon', 'Triathlon', 'A'),
    (74, 'Which club competition is the top annual tournament in European men''s football?', 'Europa League', 'Champions League', 'Conference League', 'UEFA Super Cup', 'B'),
    (75, 'How many points is a conversion worth in rugby union after a try?', '1', '2', '3', '5', 'B'),
    (76, 'Which country won the ICC Men''s T20 World Cup in 2024?', 'India', 'South Africa', 'England', 'Australia', 'A'),
    (77, 'What does LBW stand for in cricket?', 'Leg Before Wicket', 'Long Boundary Wicket', 'Late Bat Warning', 'Line Behind Wicket', 'A'),
    (78, 'Which athlete was nicknamed The Greatest and was born Cassius Clay?', 'Joe Frazier', 'Muhammad Ali', 'George Foreman', 'Sonny Liston', 'B'),
    (79, 'In golf, what is one stroke under par on a hole called?', 'Bogey', 'Birdie', 'Eagle', 'Condor', 'B'),
    (80, 'Which country won the men''s Olympic football gold medal at Tokyo 2020?', 'Spain', 'Brazil', 'Mexico', 'Argentina', 'B'),
    (81, 'In tennis, how many games must a player usually win to take a set, with a two-game margin?', '4', '5', '6', '7', 'C'),
    (82, 'Which sport uses stones and sweeping on ice?', 'Bobsleigh', 'Curling', 'Luge', 'Skeleton', 'B'),
    (83, 'What is a hat-trick in soccer?', 'Three saves in a half', 'Three goals by one player in a game', 'Three yellow cards', 'Three consecutive corners', 'B'),
    (84, 'Which MLB team is famous for the Green Monster?', 'Boston Red Sox', 'Chicago Cubs', 'New York Yankees', 'Los Angeles Dodgers', 'A'),
    (85, 'In boxing, which weight class is above lightweight and below welterweight in the traditional sequence?', 'Featherweight', 'Middleweight', 'Light welterweight', 'Heavyweight', 'C'),
    (86, 'Which nation won the women''s singles title at Wimbledon 2023 through Marketa Vondrousova?', 'Poland', 'Czech Republic', 'Tunisia', 'United States', 'B'),
    (87, 'Which sport is associated with the term hole in one?', 'Croquet', 'Golf', 'Bowls', 'Darts', 'B'),
    (88, 'How many players start for one baseball team on defense?', '8', '9', '10', '11', 'B'),
    (89, 'Which country won the men''s singles title at the 2024 Australian Open through Jannik Sinner?', 'Spain', 'Italy', 'Serbia', 'Russia', 'B'),
    (90, 'In American football, what is the line called that a team must reach to earn a new first down?', 'Goal line', 'Scrimmage line', 'Marker line', 'Line to gain', 'D'),
    (91, 'Which sport features the Biles and Yurchenko vault families?', 'Diving', 'Figure skating', 'Gymnastics', 'Pole vault', 'C'),
    (92, 'How many darts are thrown in one turn in standard darts?', '2', '3', '4', '6', 'B'),
    (93, 'Which country won the UEFA Champions League final in 2024 through Real Madrid?', 'England', 'Spain', 'Germany', 'Italy', 'B'),
    (94, 'In cricket, what is it called when a bowler takes three wickets in three consecutive balls?', 'Triple wicket', 'Hat-trick', 'Golden over', 'Clean sweep', 'B'),
    (95, 'Which sport uses a saddle, reins, and stirrups in competition?', 'Polo', 'Equestrian', 'Cycling', 'Rowing', 'B'),
    (96, 'What is the standard distance of an Olympic swimming pool?', '25 meters', '40 meters', '50 meters', '100 meters', 'C'),
    (97, 'Which country won the men''s EuroBasket 2022 tournament?', 'Spain', 'France', 'Germany', 'Greece', 'A'),
    (98, 'In soccer, what is awarded for a foul inside the defending team''s penalty area?', 'Free kick', 'Drop ball', 'Penalty kick', 'Corner kick', 'C'),
    (99, 'Which sport features the Lombardi Trophy?', 'College football', 'NFL', 'CFL', 'Rugby league', 'B'),
    (100, 'In tennis, what is a serve that lands in play and is untouched by the receiver called?', 'Volley', 'Ace', 'Lob', 'Winner', 'B'),
    (101, 'Which country hosted the 2024 Summer Olympics?', 'Japan', 'United States', 'France', 'Australia', 'C'),
    (102, 'How many players are in a standard rugby union team on the field?', '13', '14', '15', '16', 'C'),
    (103, 'Which sport includes the apparatus called rings?', 'Weightlifting', 'Gymnastics', 'Wrestling', 'Fencing', 'B'),
    (104, 'Which nation won the Copa Libertadores in 2023 through Fluminense?', 'Argentina', 'Brazil', 'Uruguay', 'Chile', 'B'),
    (105, 'What is the highest possible checkout in standard 501 darts?', '160', '170', '180', '190', 'B'),
    (106, 'Which golf major is played at Augusta National?', 'US Open', 'The Open Championship', 'PGA Championship', 'The Masters', 'D'),
    (107, 'In baseball, what is a pitcher credited with after allowing no hits in a complete game?', 'Perfect game', 'No-hitter', 'Shutout only', 'Save', 'B'),
    (108, 'Which country won the women''s Cricket World Cup in 2022?', 'India', 'Australia', 'England', 'South Africa', 'B'),
    (109, 'In basketball, what is a shot made from beyond the arc worth?', '2 points', '3 points', '4 points', '1 point', 'B'),
    (110, 'Which sport uses the term bullpen?', 'Ice hockey', 'Baseball', 'Tennis', 'Rugby', 'B'),
    (111, 'How many rounds are in a PGA Tour event after the cut, assuming standard format?', '2', '3', '4', '5', 'C'),
    (112, 'Which nation won the men''s singles title at Wimbledon 2024 through Carlos Alcaraz?', 'Spain', 'Serbia', 'Italy', 'United Kingdom', 'A'),
    (113, 'In volleyball, what is a serve that lands untouched in bounds called?', 'Spike', 'Ace', 'Kill', 'Block', 'B'),
    (114, 'Which sport features the Ryder Cup?', 'Cricket', 'Golf', 'Tennis', 'Sailing', 'B'),
    (115, 'How many points is a drop goal worth in rugby union?', '1', '2', '3', '4', 'C'),
    (116, 'Which country won the men''s Olympic 100 meters title in Paris 2024 through Noah Lyles?', 'Canada', 'Jamaica', 'United States', 'Botswana', 'C'),
    (117, 'In soccer, what is the name of the area in front of each goal where the goalkeeper has special handling privileges?', 'Six-yard box', 'Penalty area', 'Center circle', 'Technical area', 'B'),
    (118, 'Which sport is played for the America''s Cup?', 'Rowing', 'Sailing', 'Surfing', 'Water polo', 'B'),
    (119, 'In cricket, how many runs are awarded for a ball hit over the boundary without bouncing?', '4', '5', '6', '8', 'C'),
    (120, 'Which nation won the men''s basketball gold medal at the Paris 2024 Olympics?', 'France', 'Serbia', 'United States', 'Germany', 'C'),
    (121, 'Which sport features a pommel, cantle, and girth on its equipment?', 'Cycling', 'Equestrian', 'Rowing', 'Skiing', 'B'),
    (122, 'What is the standard number of players in a beach volleyball team on court?', '2', '4', '5', '6', 'A'),
    (123, 'Which country won the men''s hockey gold medal at the Paris 2024 Olympics?', 'Germany', 'Netherlands', 'Belgium', 'India', 'B'),
    (124, 'In baseball scoring, how many outs are in one full inning?', '4', '5', '6', '8', 'C'),
    (125, 'Which sport uses the term power play?', 'Cricket', 'Ice hockey', 'Athletics', 'Tennis', 'B'),
    (126, 'Who holds the men''s record for the most Grand Slam singles titles as of March 23, 2026?', 'Roger Federer', 'Rafael Nadal', 'Novak Djokovic', 'Carlos Alcaraz', 'C'),
    (127, 'In basketball, what violation is called for taking too many steps without dribbling?', 'Charging', 'Traveling', 'Double dribble', 'Goaltending', 'B'),
    (128, 'Which nation won the women''s soccer gold medal at the Paris 2024 Olympics?', 'Brazil', 'Spain', 'United States', 'Germany', 'C'),
    (129, 'Which sport features the Calcutta Cup?', 'Cricket', 'Rugby union', 'Field hockey', 'Polo', 'B'),
    (130, 'How many balls are used in an over in modern international cricket?', '5', '6', '7', '8', 'B'),
    (131, 'Which country won the World Baseball Classic in 2023?', 'United States', 'Japan', 'Dominican Republic', 'Cuba', 'B'),
    (132, 'In tennis, what do you call a score of 40-40?', 'Advantage', 'Break point', 'Deuce', 'Set point', 'C'),
    (133, 'Which sport features the floor exercise?', 'Gymnastics', 'Figure skating', 'Wrestling', 'Fencing', 'A'),
    (134, 'What is the maximum score with three darts in one turn if all hit treble 20?', '120', '140', '160', '180', 'D'),
    (135, 'Which country won the UEFA Women''s Euro 2022?', 'Germany', 'England', 'Spain', 'Sweden', 'B'),
    (136, 'In American football, what is the term for a pass caught in the opponent''s end zone for a score?', 'Touchback', 'Touchdown', 'Conversion', 'Safety', 'B'),
    (137, 'Which sport uses a scrum-half position?', 'Rugby', 'Baseball', 'Cricket', 'Handball', 'A'),
    (138, 'Which country won the 2024 Copa America?', 'Argentina', 'Colombia', 'Uruguay', 'Brazil', 'A'),
    (139, 'In golf, what is two strokes under par on a hole called?', 'Birdie', 'Eagle', 'Bogey', 'Condor', 'B'),
    (140, 'Which sport features a crease in front of the goal used by the goalie?', 'Lacrosse', 'Ice hockey', 'Soccer', 'Rugby', 'B'),
    (141, 'Which nation won the men''s singles title at the 2024 French Open through Carlos Alcaraz?', 'Serbia', 'Italy', 'Spain', 'Germany', 'C'),
    (142, 'How many minutes is one quarter in an NBA game?', '10', '11', '12', '15', 'C'),
    (143, 'Which sport includes the positions prop, hooker, and lock?', 'Rugby union', 'Cricket', 'Baseball', 'Water polo', 'A'),
    (144, 'Which country won the men''s handball gold medal at the Paris 2024 Olympics?', 'Germany', 'Denmark', 'France', 'Sweden', 'B'),
    (145, 'In soccer, what is it called when a player is caught beyond the second-last defender before receiving the ball?', 'Icing', 'Offside', 'Obstruction', 'Encroachment', 'B'),
    (146, 'Which sport uses a coxswain?', 'Rowing', 'Cycling', 'Sailing', 'Canoeing', 'A'),
    (147, 'What is the center position called in soccer''s defensive line when paired with another central defender?', 'Wing-back', 'Center-back', 'Sweeper only', 'Stopper only', 'B'),
    (148, 'Which country won the men''s volleyball gold medal at the Paris 2024 Olympics?', 'Italy', 'France', 'Poland', 'Brazil', 'B'),
    (149, 'In baseball, what is the term for a reliever who finishes a close game successfully?', 'Starter', 'Closer', 'Utility man', 'DH', 'B'),
    (150, 'Which sport features the terms chukker and mallet?', 'Polo', 'Croquet', 'Hurling', 'Lacrosse', 'A'),
    (151, 'Which nation won the men''s road race at the 2024 Olympic Games through Remco Evenepoel?', 'France', 'Belgium', 'Netherlands', 'Slovenia', 'B'),
    (152, 'In basketball, what is an illegal screen that causes contact called?', 'Reach-in', 'Blocking foul', 'Charging', 'Loose-ball foul', 'B'),
    (153, 'Which sport uses a neutral zone and blue lines?', 'Baseball', 'Ice hockey', 'Rugby', 'Cricket', 'B'),
    (154, 'Which country won the 2023 Ballon d''Or in the men''s category through Lionel Messi''s nationality?', 'Argentina', 'Portugal', 'France', 'Spain', 'A'),
    (155, 'How many points is a penalty kick worth in rugby union?', '2', '3', '4', '5', 'B'),
    (156, 'Which sport features the terms bogey, par, and fairway?', 'Cricket', 'Golf', 'Baseball', 'Tennis', 'B'),
    (157, 'Which nation won the women''s basketball gold medal at the Paris 2024 Olympics?', 'France', 'Australia', 'United States', 'Belgium', 'C'),
    (158, 'In tennis, what is it called when the server loses the game while serving?', 'Break of serve', 'Service fault', 'Double fault', 'Net loss', 'A'),
    (159, 'Which sport uses a red ball in test matches and a white ball in most day-night limited-overs internationals?', 'Baseball', 'Cricket', 'Lacrosse', 'Handball', 'B'),
    (160, 'Which country won the men''s singles tennis gold medal at the Paris 2024 Olympics through Novak Djokovic''s nationality?', 'Croatia', 'Serbia', 'Spain', 'Italy', 'B'),
    (161, 'How many players are on the field for one baseball team including pitcher and catcher?', '8', '9', '10', '11', 'B'),
    (162, 'Which sport features a green jacket for its champion?', 'Horse racing', 'Golf', 'Snooker', 'Tennis', 'B'),
    (163, 'Which nation won the women''s rugby sevens gold medal at the Paris 2024 Olympics?', 'Australia', 'New Zealand', 'France', 'Canada', 'B'),
    (164, 'In American football, what is the term for tackling the quarterback behind the line of scrimmage on a passing play?', 'Stuff', 'Sack', 'Blitz', 'Pick', 'B'),
    (165, 'Which sport uses the term maul?', 'Rugby', 'Ice hockey', 'Baseball', 'Basketball', 'A'),
    (166, 'Which country won the UEFA Europa League in 2024 through Atalanta''s nationality?', 'Spain', 'Germany', 'Italy', 'England', 'C'),
    (167, 'In soccer, what is the term for restarting play with a kick from the corner arc?', 'Goal kick', 'Corner kick', 'Free kick', 'Penalty kick', 'B'),
    (168, 'Which sport includes sabre, foil, and epee?', 'Fencing', 'Archery', 'Shooting', 'Modern pentathlon', 'A'),
    (169, 'Which nation won the men''s decathlon at the Paris 2024 Olympics through Markus Rooth''s nationality?', 'Germany', 'Norway', 'Sweden', 'Estonia', 'B'),
    (170, 'How many points is a successful extra-point kick usually worth in the NFL?', '1', '2', '3', '6', 'A'),
    (171, 'Which sport uses a breakaway, faceoff, and slap shot?', 'Field hockey', 'Ice hockey', 'Lacrosse', 'Rugby', 'B'),
    (172, 'Which country won the 2024 ICC Women''s T20 World Cup?', 'Australia', 'South Africa', 'India', 'New Zealand', 'D'),
    (173, 'In golf, what is the area of very short grass around the hole called?', 'Rough', 'Green', 'Fairway', 'Tee box', 'B'),
    (174, 'Which sport uses the terms libero and setter?', 'Handball', 'Volleyball', 'Basketball', 'Netball', 'B'),
    (175, 'Which nation won the men''s team pursuit gold medal in track cycling at Paris 2024 through its national team?', 'Australia', 'Great Britain', 'Italy', 'Denmark', 'A'),
    (176, 'In baseball, what does RBI stand for?', 'Run Batted In', 'Runner Becomes In', 'Right Base Indicator', 'Rapid Batting Index', 'A'),
    (177, 'Which sport features the positions skip, lead, second, and third?', 'Curling', 'Rowing', 'Polo', 'Badminton', 'A'),
    (178, 'Which country won the men''s all-around gymnastics gold medal at Paris 2024 through Shinnosuke Oka''s nationality?', 'China', 'Japan', 'United States', 'Ukraine', 'B'),
    (179, 'In soccer, what is the term for moving the ball between teammates to keep possession and build an attack?', 'Marking', 'Passing', 'Tackling', 'Throwing', 'B'),
    (180, 'Which sport uses the term frame for one unit of play?', 'Snooker', 'Rugby', 'Baseball', 'Cycling', 'A'),
    (181, 'Which nation won the women''s singles title at the 2024 US Open through Aryna Sabalenka''s nationality?', 'Belarus', 'Poland', 'United States', 'Kazakhstan', 'A'),
    (182, 'How many players are there per side in water polo during active play, including the goalkeeper?', '6', '7', '8', '9', 'B'),
    (183, 'Which sport uses pommel horse, rings, and parallel bars?', 'Weightlifting', 'Gymnastics', 'Diving', 'Karate', 'B'),
    (184, 'Which country won the men''s water polo gold medal at the Paris 2024 Olympics?', 'Spain', 'Serbia', 'Hungary', 'Croatia', 'B'),
    (185, 'In cricket, what is the term for a score of zero by a batter?', 'Love', 'Duck', 'Blank', 'Goose', 'B'),
    (186, 'Which sport features the Vuelta a Espana?', 'Motorcycling', 'Cycling', 'Athletics', 'Equestrian', 'B'),
    (187, 'Which nation won the men''s Ballon d''Or in 2024 through Rodri''s nationality?', 'Spain', 'Portugal', 'England', 'Brazil', 'A'),
    (188, 'In basketball, what is it called when a player illegally dribbles, stops, and then dribbles again?', 'Traveling', 'Double dribble', 'Carrying', 'Charging', 'B'),
    (189, 'Which sport uses a yorker and bouncer?', 'Baseball', 'Cricket', 'Tennis', 'Lacrosse', 'B'),
    (190, 'Which country won the men''s singles title at the 2024 US Open through Jannik Sinner''s nationality?', 'Italy', 'Spain', 'United States', 'Germany', 'A'),
    (191, 'How many players from one team are on the court in netball at a time?', '5', '6', '7', '8', 'C'),
    (192, 'Which sport uses the terms putt, chip, and bunker?', 'Baseball', 'Golf', 'Bowls', 'Polo', 'B'),
    (193, 'Which nation won the women''s volleyball gold medal at the Paris 2024 Olympics?', 'Brazil', 'United States', 'Italy', 'Turkey', 'C'),
    (194, 'In tennis, what is a second consecutive serving fault called?', 'Foot fault', 'Net fault', 'Double fault', 'Service break', 'C'),
    (195, 'Which sport features the Bundesliga, Serie A, and La Liga as major leagues?', 'Basketball', 'Soccer', 'Baseball', 'Rugby', 'B'),
    (196, 'Which country won the men''s Olympic high jump gold medal at Paris 2024 through Hamish Kerr''s nationality?', 'Australia', 'Canada', 'New Zealand', 'Great Britain', 'C'),
    (197, 'In baseball, which base must a runner touch first after leaving home plate?', 'Second base', 'Third base', 'First base', 'Pitcher''s mound', 'C'),
    (198, 'Which sport uses the terms checkmate, gambit, and rook in official competitions?', 'Bridge', 'Chess', 'Go', 'Draughts', 'B'),
    (199, 'Which nation won the women''s UEFA Champions League in 2024 through Barcelona''s country?', 'Spain', 'England', 'France', 'Germany', 'A'),
    (200, 'How many periods are in a standard NHL game?', '2', '3', '4', '5', 'B');

INSERT INTO quiz_questions
    (owner_admin_id, question_text, option_a, option_b, option_c, option_d, correct_option, countdown_seconds, reveal_duration, active, created_at, updated_at)
SELECT
    @owner_admin_id,
    t.question_text,
    t.option_a,
    t.option_b,
    t.option_c,
    t.option_d,
    t.correct_option,
    @countdown_seconds,
    @reveal_duration,
    1,
    @created_at,
    @created_at
FROM tmp_sports_knowledge_questions_200 t
WHERE NOT EXISTS (
    SELECT 1
    FROM quiz_questions q
    WHERE q.owner_admin_id = @owner_admin_id
      AND q.question_text = t.question_text
);

DROP TEMPORARY TABLE tmp_sports_knowledge_questions_200;

COMMIT;
